### ISSUE TITLE
extract or rasterize?

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#10]
How should the abundance of each feature in each planning unit be calculated when the features are a `RasterStack` object and the planning units are a `SpatialPolygons` object? 

At the moment, we're essentially using the `raster::extract` function. The package has a few tricks to speed this up (like parallel processing), and using the velox package's extract function if its installed. However, this can still be very slow for polygons that have complex geometry.

In the `marxan` package, I did this by rasterizing the planning units and using zonal statistics to calculate abundances. This approach was much faster than `raster::extract`. I found the best performance using `gdalUtils` to do the rasterization (though this may no longer be the case). The issue with this approach is that it makes a few assumptions about the data that may not be valid.

Do you think we should stick with the slower extract and tell users that they should rasterize their planning unit data where possible, or use the faster rasterization approach and tell users the limitation of this approach?

**Comment by ricschuster** [comment]
Now I understand why features are always rasters. You are doing the pre-processing with the package.

Call me crazy, but why don't we by default assume that users will provide processed data? In my opinion R just isn't the most efficient way to summarize rasters to the e.g. polygon planning unit level. Today I played around with a really modest dataset of 18k planning units and creating the conservation problem using a ```SpatialPolygons``` object and a ```RasterStack``` of only 7 rasters took several minutes. 

I think in terms of workflow we could provide helper functions to do the ```raster::extract``` step, but I think the default for creating a ```problem``` should be that the data is already processed. But maybe I'm too stuck in the Marxan way of thinking. What do you think?

**Comment by jeffreyhanson** [comment]
Yeah, the package does the pre-processing of the spatial data.

Personally, I think having the package interface directly with spatial data is one of its best features. 

1. It means that users don't have to convert their data into a new format, and then learn how to use the new format. I think a good deal--if not most--of the questions on the Marxan emailing list tend to be about getting spatial data into the right format for Marxan. By using the spatial data formats that users are already familiar with, we can avoid these issues.

2. Storing the spatial data in the `problem` object is going to make it much easier for users to tune their problems using the shiny apps. They won't have to re-specify all the spatial data since the object already contains it all.

3. Storing the spatial data in the `problem` object allows users to add any constraint they want on the fly. For example, if a user wants to add boundary length constraints, they can just add `add_boundary_constraints` to their problem.  If the problem object didn't store the spatial data, then they would have pre-process the spatial data, and then add the constraint. I can imagine users accidentally specifying a different spatial object from the one they used in originally specifying the problem, resulting in incompatibility issues or odd outputs.

4. It reduces the difficulty involved in creating new constraints. Ideally we want researchers contributing new constraints and objectives to this package. If some one puts out a new paper on formulating a constraint, I think we want to make it relatively easy for them to add that functionality to the package. If we retain all the spatial data in the `problem` object then they don't have to worry about implementing a separate pre-processor function along with the main `add_XXXX_constraints` function.

5. Although the spatial data processing in R can be slow, it's only going to get better. The `sf` package is becoming the new weapon of choice for processing vector data. Additionally, from what I've heard, the `raster` package is currently being overhauled to use `Rcpp` for most of its functions. In the mean time,  we have packages like [`velox`](https://cran.r-project.org/web/packages/velox/README.html) and [`fasterize`](https://github.com/ecohealthalliance/fasterize) that we could use to speed up processing.  The user also has the option to use parallel processing to speed up spatial analyses ([`set_number_of_threads`](https://prioritizr.github.io/prioritizr/reference/parallel.html)).  Also, we could update the [`fast_extract`](https://prioritizr.github.io/prioritizr/reference/fast_extract.html) function--which is the responsible for planning unit vs feature data extraction--to use the `arcpy` python library to process data using ArcGIS if possible.

I agree we should add the ability to use `data.frames` in the problem specification, but I don't think this should be the recommended use-case.

If users copy objects, this can help avoid unnecessary computation. For example, this is discouraged because the computation of the amount of each feature in each planning unit is performed twice.

```
p1 <- problem(x, y) %>%
          add_min_set_objective() %>%
          add_relative_targets(0.1)
p2 <- problem(x, y) %>%
          add_min_set_objective() %>%
          add_relative_targets(0.2)
```

Instead, this could be used to avoid recomputing the values.

```
p0 <- problem(x, y) %>% add_min_set_objective()
p1 <- p0 %>% add_relative_targets(0.1)
p2 <- p0 %>% add_relative_targets(0.2)
```

The [`run_calculations`](https://prioritizr.github.io/prioritizr/reference/run_calculations.html) function can be used to cache boundary length and neighbourhood data too.

Does that makes sense? What do you think?

**Comment by ricschuster** [comment]
Thanks very much Jeff, that does make a lot of sense.

What do you think about a pre-```problem``` function that deals with the spatial processing? Something similar to the ```ingest``` type functions that both Matt W and I had thought about in previous Shiny packages? On the one hand I like the separation of pre-processing spatial data and problem formulation, but on the other I also see the benefit for users to be able to supply their spatial data directly to the ```problem``` function. What do you think?

One feature that's currently not available (other than the data.frame input), but that I work with almost exclusively, is the option to provide features as vector input, either as part of the pu shapefile, or if we want to also allow processing on this end, in a separate, not necessarily matching shapefile. I'm not sure how much progress on shapefile processing has been made in R lately. Last I tried to do this kind of thing in R (probably 2 years ago) it was still very sluggish and nowhere close to the processing speed of ArcGIS or QGIS.

re: ```arcpy``` we should also be thinking about a link or utilization of the RQGIS package to use QGIS for processing.

**Comment by jeffreyhanson** [comment]
Whats the status on this issue?

From what I can tell, it looks like we kept using `raster::extract` because of its guaranteed correctness than then `raster::rasterize` and then `raster::zonalStats`.

You raised some good points about the allowing aspatial data in `problem` and now prioritizr supports `data.frames` for inputs to `problem`  and users can also specify feature data as columns in `data.frame` and `Spatial*DataFrame` planning unit data.

**Comment by ricschuster** [comment]
I think we can close this for now, as users have several options of how to incorporate data into a `problem`.
