### ISSUE TITLE
Update add_connectivity_penalties example with more efficient distance matrix calcs

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#107]
As per discussion with @magalicombes in #97 , it would be good to update the example code for `add_connectivity_penalties` to provide more efficient code for calculating the planning unit by planning unit connectivity matrix.

**Comment by jeffreyhanson** [comment]
I'm not so sure if adding more a more memory efficient example to the `add_connectivity_penalties` manual entry is such a good idea anymore. This would mean that we have to add another package to prioritzr's Suggests (i.e. fields R package) and this would further increase installation times. What do you think @ricschuster?

**Comment by ricschuster** [comment]
I agree @jeffreyhanson. Best to keep number of suggests down and not add more.

**Comment by jeffreyhanson** [comment]
Ok. I'll close this issue then.
