### ISSUE TITLE
maximum reasonable BLM

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#109]

**Comment by jeffreyhanson** [comment]
I just thought I would document our progress (or lack thereof) on this issue that we made over emails, so it doesn't get lost. @ricschuster, can please let me know if I'm missing anything, or if I've got anything wrong?

-----

We had this idea that you could estimate the maximum BLM penalty value based on the (1) boundary data values and (2) the planning unit cost values. Specifically, the method for calculating the maximum BLM value might look like this:

```
# load package
library(prioritizr)

# load data
data(sim_pu_raster, sim_features)

# create boundary matrix
bm <- boundary_matrix(sim_pu_raster)

# create baseline problem
p1 <-
  problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions()

# max BLM value
m <- (sum(c(p1$planning_unit_costs())) / min(bm@x)) + 1e-5

# create problem with boundaries
p2 <- p1 %>% add_boundary_penalties(m, data = bm)

# solve problems
s1 <- solve(p1)
s2 <- solve(p2)

# plot solutions
plot(stack(s1, s2))
```

To see if this would actually work, @ricschuster tried applying this to a real conservation planning dataset (i.e. the one from his PeerJ paper). Unfortunately, his results showed that the maximum BLM value this method estimated was much, much, much higher than the "real BLM maximum value" that we know would clump all the planning units together. In other words, this approach massively over-estimates the "maximum BLM" value by so much that it is effectively useless. So, we need to keep looking for a method to find a useful upper limit for calibrating BLM values.

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson. This covers what we have tried so far.

**Comment by jeffreyhanson** [comment]
Just an idea, what if we tried using `sum(...)` instead of `min(...)`? E.g. something like this:

```
m <- (sum(c(p1$planning_unit_costs())) / sum(bm@x)) + 1e-5
```

**Comment by ricschuster** [comment]
Good idea. For the PeerJ paper data its certainly the right ballpark number: 4860.59
The highest number we tried was 1000 and that clumped pretty well.

Maybe you just solved this!

**Comment by jeffreyhanson** [comment]
Ah - neat! I just updated the example code above and it looks like sum method doesn't provide maximal clumping. E.g. see here with simulated data:

```
# load package
library(prioritizr)

# load data
data(sim_pu_raster, sim_features)

# create boundary matrix
bm <- boundary_matrix(sim_pu_raster)

# create baseline problem
p1 <-
  problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions()

# max BLM value
m1 <- (sum(c(p1$planning_unit_costs())) / min(bm@x)) + 1e-5
m2 <- (sum(c(p1$planning_unit_costs())) / sum(bm@x)) + 1e-5

# create problem with boundaries
p2 <- p1 %>% add_boundary_penalties(m1, data = bm)
p3 <- p1 %>% add_boundary_penalties(m2, data = bm)

# solve problems
s1 <- solve(p1)
s2 <- solve(p2)
s3 <- solve(p3)

# plot solutions
plot(stack(s1, s2, s3))
```

I guess it depends how we define "reasonable" in "maximum reasonable BLM"?

**Comment by ricschuster** [comment]
`s2` and `s3` do have the same boundary length in both cases (18), but `s3` is able to grab more cells. 
The `s2` figure looks very reasonable to me.

Maybe we should test with a couple more datasets?
The Salt Spring one could be a good test case as well.

**Comment by ricschuster** [comment]
I do think however that you solved it Jeff.

**Comment by jeffreyhanson** [comment]
> s2 and s3 do have the same boundary length in both cases (18), but s3 is able to grab more cells.

Ah - I didn't realize that  - thanks for verifying it!

> The s2 figure looks very reasonable to me.

Yeah I agree

> Maybe we should test with a couple more datasets?

Yeah that's a great idea! Can you give that a go and see what happens?

**Comment by ricschuster** [comment]
Will do.

Also looked at `eval_cost_summary` and `eval_feature_representation_summary` and `s3` is doing very well compared to `s1` and `s2` is loads more expensive.

**Comment by jeffreyhanson** [comment]
> I do think however that you solved it Jeff.

Maybe - I'm not 100% convinced yet. But assuming it does work, it would be good to implement a function that calculates this number. We could even include this function as a check in the `add_boundary_penalties` function so that users don't waste time trying to solve problems with really high BLM values? What should be name such a function? We could follow the `eval_something_something` format? 

Perhaps something like `eval_max_boundary_penalty(x, data, zones)`? Where `x` is the problem, `data` is the boundary matrix data, and `zones` is the zones argument for `add_boundary_penalties` (following same defaults)? What do you think?

**Comment by jeffreyhanson** [comment]
Perhaps `max` would give the wrong idea though? Maybe there's a better term?

**Comment by ricschuster** [comment]
Good idea about the function. 

I think you are right `max` by itself might give the wrong idea. 
How about `max-recommended` or `max_recommended`? Or is that too long?

btw: `p2` for Salt Spring is taking a really long time to solve.

**Comment by jeffreyhanson** [comment]
Yeah, I think `max_recommended` is too long. Maybe we could emphasize in the documentation and the warning/error message for `add_boundary_penalties` that this is a recommendation, rather than the function name?

**Comment by jeffreyhanson** [comment]
> btw: p2 for Salt Spring is taking a really long time to solve.

Do you mean this code?

```
  titles <- c(titles, "Rsymphony (5s)")
  p2 <- p1 %>% add_rsymphony_solver(time_limit = 5)
  s1 <- addLayer(s1, solve(p2))
```

**Comment by ricschuster** [comment]
The max BLM value code for p2:

```
m1 <- (sum(c(p1$planning_unit_costs())) / min(bm@x)) + 1e-5
p2 <- p1 %>% add_boundary_penalties(m1, data = bm)
s2 <- solve(p2)
```

s3 solved reasonably quickly.

**Comment by ricschuster** [comment]
and `s3` is pretty much as clumped up as it gets:

![image](https://user-images.githubusercontent.com/3445092/109362377-bf23cf80-783f-11eb-8d0f-74eb2869ce74.png)

**Comment by ricschuster** [comment]
The code I used:

```
# load package
library(prioritizr)
library(prioritizrdata)

# load data
data(salt_pu, salt_features)

# create boundary matrix
bm <- boundary_matrix(salt_pu)

# create baseline problem
p1 <-
  problem(salt_pu, salt_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(threads = 40)

# max BLM value
m1 <- (sum(c(p1$planning_unit_costs())) / min(bm@x)) + 1e-5
m2 <- (sum(c(p1$planning_unit_costs())) / sum(bm@x)) + 1e-5

# create problem with boundaries
p2 <- p1 %>% add_boundary_penalties(m1, data = bm)
p3 <- p1 %>% add_boundary_penalties(m2, data = bm)

# solve problems
s1 <- solve(p1)
s2 <- solve(p2)
s3 <- solve(p3)

# compare solution costs
eval_cost_summary(p1, s1)
eval_cost_summary(p1, s2)
eval_cost_summary(p1, s3)

# compare feature representation
eval_feature_representation_summary(p1, s1)
eval_feature_representation_summary(p1, s2)
eval_feature_representation_summary(p1, s3)

# plot solutions
plot(stack(s1, s2, s3))
```

**Comment by jeffreyhanson** [comment]
Ohh, right - sorry, I should have realized you meant `s2`  from the example code.

Ok, so it looks like this method might actually work then? Shall I have a go at implementing it? I could also apply this logic for the connectivity penalties too.

**Comment by ricschuster** [comment]
No worries.

Yes, I think this method works. If you wouldn't mind implementing it, that would be great!
Great idea to use the same logic for the connectivity penalties as well.

This will make finding reasonable bpf values so much easier.

**Comment by jeffreyhanson** [comment]
Ok sounds great. I'll work on this after we've merged the CI branch (also, something weird is happening with the CI on Ubuntu dev, so please don't merge it yet) and I've got the benchmark code working.

**Comment by jeffreyhanson** [comment]
> This will make finding reasonable bpf values so much easier.

Yes - I completely agree!

**Comment by ricschuster** [comment]
> Ok sounds great. I'll work on this after we've merged the CI branch (also, something weird is happening with the CI on Ubuntu dev, so please don't merge it yet) and I've got the benchmark code working.

Awesome!

**Comment by jeffreyhanson** [comment]
While I'm at it, I could also implement the Marxan Good Practices trick method (i.e. setting costs to zero, run the optimization, and apply a formula) to find a "balanced" BLM value.

**Comment by ricschuster** [comment]
That would be fun to play with as well.

**Comment by jeffreyhanson** [comment]
So, we would potentially have four new functions then. What should they be called?

```
eval_max_boundary_penalty()
eval_balance_boundary_penalty()
eval_max_connectivity_penalty()
eval_balance_connectivity_penalty()
```

Although, maybe these should have a different prefix because they aren't about evaluating solutions? I.e. all the `eval_` functions have a solution argument (if I remember correctly). So perhaps some prefix to do with calibration? E.g. calib? cal?

```
calib_max_boundary_penalty()
calib_balance_boundary_penalty()
calib_max_connectivity_penalty()
calib_balance_connectivity_penalty()
```

**Comment by ricschuster** [comment]
Oh, I like the `calib` prefix idea. That provides a nice distinction to the `eval` function family, which I think of as functions that work on solved problems.

**Comment by jeffreyhanson** [comment]
Ok great - can you think of something better than `calib`? I feel like it might not be ideal, though `cal` seems a bit vague.

**Comment by ricschuster** [comment]
`calc`?
Its pretty vague too.
`assess`?

**Comment by jeffreyhanson** [comment]
Hmm, yeah, I feel like they don't necceasrily relate to "tweaking input parameters". Whereas, "calibration" sort of does (or at least to me), e.g. like parameter calibration vs parameter calculations or parameter assessment.

**Comment by jeffreyhanson** [comment]
Shall we still with calib then?

**Comment by jeffreyhanson** [comment]
we stick with calib for now then* I mean

**Comment by ricschuster** [comment]
yes, lets stick with `calib`.

**Comment by jeffreyhanson** [comment]
I just realized that we probably need a method that works for all of the different objectives (e.g. max features, min shortfall, etc) and for multiple zones. This makes things a bit trickier. E.g. for max features, does this mean that the maximum BLM value should be based on based on the number of species that have their targets met (instead of costs). E.g.

```
# load package
library(prioritizr)

# load data
data(sim_pu_raster, sim_features)

# create boundary matrix
bm <- boundary_matrix(sim_pu_raster)

# set budget
b <- raster::cellStats(sim_pu_raster, "sum") * 0.2

# create baseline problem
p1 <-
  problem(sim_pu_raster, sim_features) %>%
  add_max_features_objective(budget = b) %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions()

# max BLM value
m1 <- (raster::nlayers(sim_features) / min(bm@x)) + 1e-5
m2 <- (raster::nlayers(sim_features) / sum(bm@x)) + 1e-5
m3 <- ((raster::nlayers(sim_features) * 10) / sum(bm@x)) + 1e-5

# create problem with boundaries
p2 <- p1 %>% add_boundary_penalties(m1, data = bm)
p3 <- p1 %>% add_boundary_penalties(m2, data = bm)
p4 <- p1 %>% add_boundary_penalties(m3, data = bm)

# solve problems
s1 <- solve(p1)
s2 <- solve(p2)
s3 <- solve(p3)
s4 <- solve(p4)

# plot solutions
plot(stack(s1, s2, s3, s4))
```

But we can see here that this under-estimates the maximum reasonable BLM (i.e. s3 has much less clumping than s4)?

**Comment by ricschuster** [comment]
Hmmm, I don't have any good ideas about other objective functions.

Maybe your `add_max_features_objective` example shows that the min_set approach doesn't generalize well?
It is interesting that `s2` doesn't set aside any of the features, because BPF is so high.
`s4` is more costly as `s1`, but feature representation is still good.

```
> eval_cost_summary(p1, s1)
# A tibble: 1 x 2
  summary  cost
  <chr>   <dbl>
1 overall 2010.
> eval_cost_summary(p1, s2)
# A tibble: 1 x 2
  summary  cost
  <chr>   <dbl>
1 overall     0
> eval_cost_summary(p1, s3)
# A tibble: 1 x 2
  summary  cost
  <chr>   <dbl>
1 overall 2149.
> eval_cost_summary(p1, s4)
# A tibble: 1 x 2
  summary  cost
  <chr>   <dbl>
1 overall 2537.
> eval_feature_representation_summary(p1, s1)
# A tibble: 5 x 5
  summary feature total_amount absolute_held relative_held
  <chr>   <chr>          <dbl>         <dbl>         <dbl>
1 overall layer.1         83.3          8.84         0.106
2 overall layer.2         31.2          3.21         0.103
3 overall layer.3         72.0          7.22         0.100
4 overall layer.4         42.7          4.38         0.103
5 overall layer.5         56.7          5.97         0.105
> eval_feature_representation_summary(p1, s2)
# A tibble: 5 x 5
  summary feature total_amount absolute_held relative_held
  <chr>   <chr>          <dbl>         <dbl>         <dbl>
1 overall layer.1         83.3             0             0
2 overall layer.2         31.2             0             0
3 overall layer.3         72.0             0             0
4 overall layer.4         42.7             0             0
5 overall layer.5         56.7             0             0
> eval_feature_representation_summary(p1, s3)
# A tibble: 5 x 5
  summary feature total_amount absolute_held relative_held
  <chr>   <chr>          <dbl>         <dbl>         <dbl>
1 overall layer.1         83.3          9.67         0.116
2 overall layer.2         31.2          3.19         0.102
3 overall layer.3         72.0          7.47         0.104
4 overall layer.4         42.7          4.28         0.100
5 overall layer.5         56.7          6.92         0.122
> eval_feature_representation_summary(p1, s4)
# A tibble: 5 x 5
  summary feature total_amount absolute_held relative_held
  <chr>   <chr>          <dbl>         <dbl>         <dbl>
1 overall layer.1         83.3         11.2          0.134
2 overall layer.2         31.2          3.30         0.106
3 overall layer.3         72.0          8.42         0.117
4 overall layer.4         42.7          5.64         0.132
5 overall layer.5         56.7          8.40         0.148
```

**Comment by jeffreyhanson** [comment]
Yeah, maybe it doesn't generalize well to other objective functions. Perhaps one explanation for this is that: under the min set problem, the planning unit variables directly influence the primary objective function (i.e. total cost of the solution) and the penalty objective function (i.e. total boundary length) which means there is a stronger (direct?) relationship between them. And this, in turn, could mean that a simple formula based on the cost and boundary values has a better chance of approximating the true "maximum reasonable penalty value"? This is just a guess though.

**Comment by ricschuster** [comment]
I think you are right in regards to the stronger relationship between cost and boundary penalty for min_set. 
Do you think this function/formulation would only work for min_set than? Would be neat to have this function, but if its restricted to min_set it might be a bit weird to add it.
What do you think?

**Comment by jeffreyhanson** [comment]
Sorry @ricschuster, it looks like I totally forgot to respond to your question. Yeah, I think we would need to add the functionality so that these new family of functions would generalize to all the objective functions. Since the calibrating trade-offs tutorial provides guidance on quickly finding a maximum reasonable BLM value (which is also generalizble to other objective functions), I think this issue is mostly resolved now? Ideally, it would be nice to have some automatic method, but this is difficult without making a lot of assumptions about what the user would consider reasonable and also adding routines to automatically re-scale data internally.

**Comment by ricschuster** [comment]
No worries and I agree with the calibration tutorial the package provides guidance on finding max reasonable BLM values.
I will close the issue for now.
