### ISSUE TITLE
marxan cloud

### ISSUE THREAD

**Issue by mattwatts** [prioritizr/prioritizr#11]
Any takers?

Sometimes Nectar regions go out without warning, causing outages on our website.

Volunteers needed. The more the merrier. Monitor, restart, troubleshoot Marxan web (completely redevelop in your own image if you like also).

I'm using OpenStack on Nectar Cloud nectar.org.au , so anyone with an AAF credential (any technically literate student/postdoc/prof/etc affiliated with an account from an Australian University or AAF accredited org like CSIRO) can be added to the mix so they can monitor Marxan infrastructure and restart/etc if required. AAF is required so I can add them to the Nectar dashboard as collaborators on Marxan web - unfortunately for now we can't include our overseas colleagues as admins on Marxan cloud.

**Comment by mattwatts** [comment]
I'm sure we can figure out a way to include our overseas colleagues also, but just not in the first instance.

**Comment by ricschuster** [comment]
Would be happy to be part of this, but will need to wait as I'm an 'overseas colleague'.

**Comment by jeffreyhanson** [comment]
@mattwatts That sounds awesome! I'm really busy at the moment so I don't think I'll be able to help too much, but I'd be keen to be kept in the loop as I might be able to help out later.

PS. hope everything's going well :)

**Comment by jeffreyhanson** [comment]
I'll close this now due to lack of activity, but please feel free to reopen if anyone wants to discuss further.
