### ISSUE TITLE
feature_representation() fails error checks if supplied data are data.frames

### ISSUE THREAD

**Issue by Martin-Jung** [prioritizr/prioritizr#110]
No test data, but should be verifiable with the `prioritizr` test data or any other data.

pu_data is a `data.frame` with columns id / cost
feature_data is a `data.frame` with columns species / name / id
rij_data is a `data.frame` with columns pu / species / amount

```
p_objutil <- problem(pu_data, feature_data, rij_data, cost_column = "cost") %>%
  add_max_utility_objective(budget = 8000) %>% 
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0, threads = 7,verbose = TRUE) 
r_objutil <- solve(p_objutil)

# Now if feature_representation is run, the following
feature_representation(p_objutil,r_objutil)

>  Error: number_of_zones(x) not equal to ncol(solution)
```

`number_of_zones(p_objutil)` is **1**
`ncol( r_objutil )` is **3** ( id, cost, solution_1 )

**Comment by jeffreyhanson** [comment]
Hi,

Given `data.frame` planning unit data, the argument to `solution` in the `feature_representation` function should contain columns that contain the status of planning units. For single-zone problems, this means having a single column with the status (e.g. 0/1) of the planning units in the solution. For multi-zone problems, this means having a column for each zone, and each column containing the status of the planning units (e.g. 0/1). 

Could you please try the code below?

```
feature_representation(p_objutil,r_objutil[, "solution_1", drop = FALSE])
```

Cheers,

Jeff

**Comment by Martin-Jung** [comment]
The supplied code works, cheers. 

So running your 'prioritizr-parallel-example.R' example script:
This doesn't work: `feature_representation(p,s)`
This works: `feature_representation(p,s[, "solution_1", drop = FALSE])`

Could this maybe be added to the documentation or maybe a short check is run, whether solutions are dropped?

Cheers for the speedy help :+1:

**Comment by jeffreyhanson** [comment]
Ah - yeah that's a typo, sorry about that. Yeah adding this to the documentation is a great idea!
