### ISSUE TITLE
Check optimization problems for issues before solving them

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#111]
I've added a new `presolve_check` function check conservation problems for potential issues before solving them (see https://prioritizr.net/reference/presolve_check.html). In the documentation for this function, I've also outlined several common problems (e.g. high boundary penalties) and how these can be detected and fixed. @ricschuster and @mstrimas, if you have some spare time, could you please take a look and let me know what you think? Can you can think of any other common issues that users often experience? Also, I've updated the `solve` function to automatically check problems for issues with the new presolve check function (though this can be disabled using `run_checks = FALSE`) and throw an error before trying to solve the problem (though this can be overridden with `force = TRUE`) - what do you think about this?

**Comment by mstrimas** [comment]
This looks great, and I agree it makes sense to call the function automatically (but optionally) when `solve()` is called. I wasn't actually aware that large cost values would cause problems, I assumed if a planning unit had a huge cost it would just never be selected, so that's useful to know. I can't think of any other issues off the top of my head, but I'll post here if anything comes to mind.

There is one small typo:
![typo](https://user-images.githubusercontent.com/7296482/57620189-07cca480-7556-11e9-8f30-94c2237c0f02.png)

**Comment by ricschuster** [comment]
Thanks very much Jeff! This looks great and I agree with Matt re: calling the function automatically (but optionally). 

One common issue that I've seen quite often is the issue of many optimal solutions, when features and cost are relatively uninformative. I haven't really thought about this and how one would test for this, but if you have ideas, it would be great to include a check for this as well.

A simple test would be to test for variance in feature and cost data, but that on its own isn't enough to cause issues I'd argue. What do you think?

**Comment by jeffreyhanson** [comment]
Yeah, I suppose an uninformative problem could be defined as a problem with many optimal solutions relative to its number of planning units? But finding out exactly how many optimal solutions exist for a problem could take a long time for problems with a reasonable number of planning units. Is there some sort some sort of proxy we could use? E.g. the number of feasible solutions relative to the number of planning units?

**Comment by ricschuster** [comment]
The only proxy I could think of was variance in features and cost, but that's probably not good enough. Would number of feasible solutions with less costly in terms of computation time than finding number of optimal solutions? If not, maybe a warning triggered by low variance is a start?

**Comment by jeffreyhanson** [comment]
@ricschuster, sorry - I'm just going over old issues to see what I can close - and I completely forgot to respond to your question. Yeah, we could include a warning if problems have low variance in cost data, but I think that such problems are valid and also fairly common. I worry that throwing a warning is such cases is likely to cause confusion and put people off (e.g. many people cannot tell the difference between a warning and an error in Rstudio), rather than make people think critically about whether equal costs are valid in their planning scenario. What do you think?

**Comment by ricschuster** [comment]
I agree. Maybe this is something we just have to put into the documentation.

One vignette we should probably think about would be a 'good practice' one, where we talk about some of the common issues and what they could mean and also more broadly about input and output data and data 'quality'. What do you think about that?

There are some things that do come up repeatedly, that would be good to put into a vignette. One example is strange looking output patters (prioritzr selecting data row after row) that indicate issues with the input data.

**Comment by jeffreyhanson** [comment]
Yeah, I think a good practices and/or a FAQ vignette is a really good idea.

**Comment by jeffreyhanson** [comment]
Ok I'll close this issue now, since I don't think we have any more ideas for improving the `presolve_check` function, but please feel free to reopen it.
