### ISSUE TITLE
add_contiguity_constraints throws error when 'data' argument is supplied

### ISSUE THREAD

**Issue by rinnan** [prioritizr/prioritizr#116]
Hi Jeff,

I am running into problems when supplying a pre-calculated `connected_matrix` to the `add_contiguity_constraints()` function. The error that gets returned says there is "no applicable method for 'isSymmetric' applied to an object of class 'dsCMatrix'", which is strange, because the Matrix library clearly contains such methods. 

This works:

```{r}
p <- problem(x = ras, features = sp.br) %>%
  add_min_set_objective() %>%
  add_binary_decisions() %>%
  add_absolute_targets(c(2247, 93, 2000)) %>%
  add_contiguity_constraints() %>%
  add_gurobi_solver(gap = 0, time_limit = 180)
```

This does not:

```{r}
cmat <- connected_matrix(ras)

p <- problem(x = ras, features = sp.br) %>%
  add_min_set_objective() %>%
  add_binary_decisions() %>%
  add_absolute_targets(c(2247, 93, 2000)) %>%
  add_contiguity_constraints(data = cmat) %>%
  add_gurobi_solver(gap = 0, time_limit = 180)
```

When I remove `Matrix::isSymmetric(data)` from the `assert_that()` check in the function's methods, everything runs fine.

Thanks!
Scott

**Comment by jeffreyhanson** [comment]
Hi, that's strange. Just to double check, are you using the latest version of prioritizr on CRAN? Also, which version of R are you using?

**Comment by jeffreyhanson** [comment]
Could you please try running the example code below and see if it works?

```
# load package
library(prioritizr)

# load data
data(sim_pu_raster, sim_features)

# make connected matrix
cm <- connected_matrix(sim_pu_raster)

# verify that connected matrix is a dsCMatrix object
assertthat::assert_that(inherits(cm, "dsCMatrix"))

# create minimal problem
p <- problem(sim_pu_raster, sim_features) %>%
      add_min_set_objective() %>%
      add_contiguity_constraints(data = cm) %>%
      add_relative_targets(0.2) %>%
      add_binary_decisions()

# solve problem
s <- solve(p)
```

**Comment by rinnan** [comment]
Thanks for the speedy reply!

I should know better than this. I was not running the most up-to-date version of prioritizr. When I ran your example code I got the same error message as before, but it went away when I updated the package. I am using prioritizr 4.1.1 and R 3.5.0, and everything is peachy now. Sorry for the bother!

**Comment by jeffreyhanson** [comment]
No worries at all - glad you got it working!
