### ISSUE TITLE
add_proportion_decisions overshoots with floating points and fails assertion in feature_representation

### ISSUE THREAD

**Issue by Martin-Jung** [prioritizr/prioritizr#117]
Hi Jeff,

Here is a weird little bug when using `add_proportion_decisions()`.
I have a solution data.frame that fails the error checks at the start of the `feature_representation` script, specifically on that [line](https://github.com/prioritizr/prioritizr/blob/master/R/feature_representation.R#L323). 

Attached my solution data.frame:
[ProportionDecisions.rds.zip](https://github.com/prioritizr/prioritizr/files/3540995/ProportionDecisions.rds.zip)

If you check the respective column you find that this assertion evaluates to FALSE
`max(solution, na.rm = TRUE) <= 1`
While this one here asserts to TRUE
`max(solution, na.rm = TRUE) > 1`

Problem formulation as follows
```
    p_maxfeat <- problem(pu_data, feature_data, rij_data, cost_column = "cost") %>%
      add_min_shortfall_objective(budget = b_cells) %>% 
      add_relative_targets('relative_target') %>%
      add_proportion_decisions() %>% 
      add_gurobi_solver(gap = optimality_gap,time_limit = time_limit,threads = cores,
                        verbose = TRUE) 

```
My full dataset is too large to share, but it seems to me as if sometimes by using the proportion_decision option, the solution "_overshoots_", resulting in values greater than 1 at the floating point?

**Comment by jeffreyhanson** [comment]
Thank you very much for raising this issue. ILP/LP solvers often work with a certain level of precision (e.g. 5 decimal places). When they return solutions, these solutions can have values that only make sense given the solver's level of precision (e.g. Gurobi can return a planning unit status of 0.000001 when planning units should have binary-type decisions). So, prioritizr needs to "clean" these output values so they make sense (numerically) for the user. At the moment, prioritizr manually rounds raw solution values for binary decisions. To fix this, prioritizr will need to manually truncate solution values for proportion decisions. This should be fairly straight forward and I'll try to push a patch to GitHub later tonight. In the mean time though, you can fix this using something like `solution[solution > 1] <- 1` before calculating the representation.

**Comment by jeffreyhanson** [comment]
I've just pushed a patch to GitHub which should prevent output solutions from having values below zero or greater than one.
