### ISSUE TITLE
[Feature request] Updating of locked-in continuous constrains for proportion decisions 

### ISSUE THREAD

**Issue by Martin-Jung** [prioritizr/prioritizr#118]
In a problem formulation I would like to lock-in previous solutions. These previous solutions however are not binary (TRUE/FALSE or 1/0) since I used the `add_proportion_decisions()` function.

According to the [documentation](https://prioritizr.net/reference/add_locked_in_constraints.html) however only boolean values are supported as input ( _The fields (columns) must have logical (i.e. TRUE or FALSE) values indicating if the planning unit is to be locked in the solution._  ).

Would be possible to add an option to lock-in a set proportion of a planning unit? 

```
s <- problem(sim_pu_polygons, sim_features, "cost") %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_proportion_decisions() %>%
  add_locked_in_constraints("locked_in") %>% # This column to contain float values
  add_default_solver(time_limit = 5) %>%
  solve()
```

**Comment by jeffreyhanson** [comment]
Sorry if you've already looked into this, but does the `add_manual_locked_constraints` function provide this functionality (https://prioritizr.net/reference/add_manual_locked_constraints.html)? For example, using the code below we can lock the value of the first planning unit to 0.2.

```
# set seed for reproducibility
set.seed(500)

# load data
data(sim_pu_polygons, sim_features)

# create minimal problem
p <- problem(sim_pu_polygons, sim_features, "cost") %>%
     add_min_set_objective() %>%
     add_relative_targets(0.2) %>%
     add_manual_locked_constraints(data.frame(pu = 1, status = 0.2)) %>%
     add_proportion_decisions()

# solve problem
s <- solve(p)

# print solution value for the first planning unit, should be 0.2
s$solution_1[1]
```

**Comment by Martin-Jung** [comment]
H Jeff, 
Thanks for the quick answer. I was using the `add_locked_in_constraints` function so far and not the `add_manual_locked_constraints` one. My constrain is a column in the data.frame.
The code below throws an unexpected error ?

```
# set seed for reproducibility
set.seed(500)

# load data
data(sim_pu_polygons, sim_features)

sim_pu_polygons$status <- 0
sim_pu_polygons$status[c(4,22,55,78,80,90)] <- 0.57 # Add some randomly locked in 

# create minimal problem
p <- problem(sim_pu_polygons, sim_features, "cost") %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_locked_in_constraints("status") %>% 
  #add_manual_locked_constraints(data.frame(pu = 1, status = 0.2)) %>%
  add_proportion_decisions()

> Error in stop(assertError(attr(res, "msg"))) : bad error message

```

**Comment by jeffreyhanson** [comment]
Yeah, it 's throwing an error because it expects TRUE/FALSE values. The weird error message is occurring because the _assertthat R_ package is having difficult parsing a sensible error message from the data checking code. I'll update this to manually output a sensible error message. Does the manual locked constraints work for you?

**Comment by Martin-Jung** [comment]
Thanks!
It does, however only when a data.frame is supplied directly. 
It does not support a column name, which I find a bit unintuitive compared to the other locked-in constrain functions. So this one also throws a weird error:
`add_manual_locked_constraints("status")`

I will rework my code to do with the `add_manual_locked_constraints` function then.

**Comment by jeffreyhanson** [comment]
Yeah, perhaps this function could use some reworking to make it more consistent. It was originally meant to be an internal function, but I ended up exporting it in case anyone wanted more control over the locked values (which as it turns out wasn't a bad idea, haha).

**Comment by Martin-Jung** [comment]
Hi Jeff,
Opening this one again. The `add_manual_locked_constraints` does work, however I encounter another issue that is different but related (changed title).

My plan is to produce a nested set of hierarchical solutions with varying budgets. This works well for binary decisions since previously locked-in solutions can be "build-upon", e.g. the set of binary pu's selected can only be FALSE/TRUE.
For 'previous' `add_proportion_decisions()` one however locks the proportion of a cell (e.g. 0.2) indefinitely, thus preventing the optimizer to ever increase this estimate. So cells that have 0.2 with a low budget will also remain as 0.2 with a high budget, even though it might be more cost-efficient to increase the proportion protected in those cells. I realize that this can be a desirable setting for a conservation problem, however what I would like to achieve is an equal-or-greater selection.

Hope my issue is understandable? Do you think there is a way to account for this?
Unsure whether this has to be a parameter in the `add_proportion_decisions()` function or the `add_manual_locked_constraints`?
Best would be a parameter that allows the use to decide on whether the optimizer should treat the locked-in proportion as fixed (equal) or as minimum (equal-or-greater)
So effectively allowing to optimizer to constrain either **==** or if the user so desires **=>** (can only be higher than the previously selected set).

**Comment by jeffreyhanson** [comment]
I've added a new function that lets you set lower and upper bounds for planning unit statuses (https://prioritizr.net/reference/add_manual_bounded_constraints.html). If I understand correctly, you should be able to achieve the result you want by setting the lower bounds to the output from the previous solution, and keeping the upper bounds at 1. Could you please give it a go and let me know what you think?

**Comment by Martin-Jung** [comment]
Thanks Jeff, 
Works like a charm :D  
FYI: I did notice however that this issue ( #117 ) still seems to persist in the current github build. I am getting an assert_that fail of lower bounds being higher than upper bounds.
I am using a quick around in my code that fixes this.
`dplyr::mutate(lower = pmin(lower, 1)) # Assert that lower does not overshoot 1`

**Comment by jeffreyhanson** [comment]
Glad to help. Oh - sorry, I thought I fixed it - I'll have another attempt. I assume you're using the Gurobi solver?

**Comment by Martin-Jung** [comment]
Yes, I am.
>  I assume you're using the Gurobi solver?

**Comment by jeffreyhanson** [comment]
Hmm, are you saving the data to disk and then reloading it back into R (which could introduce floating point issues)? Are you able to the share your data and code to help track down the issue?

**Comment by Martin-Jung** [comment]
Data is sadly too way large too share. Sorry about the lack of a reproducible example. Attached is the save of the solution. 
I am using the `fst` package for compression. Could it be that it has issues with compressing floating_points?
[tests_solution.fst.zip](https://github.com/prioritizr/prioritizr/files/3550063/tests_solution.fst.zip)


> Hmm, are you saving the data to disk and then reloading it back into R (which could introduce floating point issues)? Are you able to the share your data and code to help track down the issue?

**Comment by jeffreyhanson** [comment]
Ah - no worries. Thanks for sharing the code. To clarify, are you: (1) generating a solution, (2) saving the solution to disk using `fst` package, (3) reloading the solution, and (4) using the solution to generate another solution? If so, that might be what's causing the problems.

**Comment by Martin-Jung** [comment]
Yes, that is my workflow. Wonder though where the problem in this approach is. I will test if it is an issue with the `fst` package (save as zip compressed table using `saveRDS` instead) or if the solver still returns solutions with values greater than 1.

> Ah - no worries. Thanks for sharing the code. To clarify, are you: (1) generating a solution, (2) saving the solution to disk using `fst` package, (3) reloading the solution, and (4) using the solution to generate another solution? If so, that might be what's causing the problems.

**Comment by jeffreyhanson** [comment]
Ah ok - yeah, if you don't mind testing to see where the problem is that would be brilliant.

**Comment by Martin-Jung** [comment]
I can confirm that the issue is with the solver :-( 
After solving it I still finds values over 1
```
    r_maxfeat <- prioritizr::solve(p_m, force = F,run_checks = FALSE)
    any(r_maxfeat$solution_1>1) # Returns TRUE
```
Solution is the one attached earlier.

**Comment by jeffreyhanson** [comment]
Ok - thank you very much. I'll see what I can do.

**Comment by jeffreyhanson** [comment]
I was able to reproduce this problem using data from the prioritizrdata R package:

```
# load packages
library(prioritizr)
library(prioritizrdata)

# define problem
p <- problem(tas_pu, tas_features, cost = "cost") %>%
     add_min_set_objective() %>%
     add_relative_targets(1) %>%
     add_proportion_decisions() %>%
     add_gurobi_solver(gap = 0, verbose = FALSE)

# solve problem
s <- solve(p)

# run check
assertthat::assert_that(all(s$solution_1 <= 1),  all(s$solution_1 >= 0))
# Error: Elements 39, 41, 55, 88, 104, ... of s$solution_1 <= 1 are not true
```

**Comment by jeffreyhanson** [comment]
I've just pushed a patch which should fix the problem of solutions containing values greater than 1 (due to floating point stuff). If you get a chance, could you please try it out?
