### ISSUE TITLE
Parallel processing replacement_cost

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#119]
I've only tried the awesome new `replacement_cost` function on Windows so far, so might be related to the OS, but would it be possible to multi-thread this, in order to increase speed for this?

I'm currently trying on a problem with 100k pu's and suspect using `replacement_cost` will take a long time.

Thanks.

**Comment by jeffreyhanson** [comment]
Yeah, it can be very slow. Are you doing the 100k pu's with binary decisions? I don't think that will complete in a feasible period of time without 20+ cores. I can have a go at this when I get a spare moment sometime this week  -- probably the weekend  -- but I fear that it won't have much of an impact without a lot of cores.

**Comment by jeffreyhanson** [comment]
I've added a threads argument to the `replacement_cost` function so you can use multiple threads to calculate the replacement costs. Could you please try it out and let me know how it goes?

**Comment by jeffreyhanson** [comment]
Brilliant - thanks! If it's taking too long with binary type decisions, then it might be worth trying to calculate the replacement costs with proportion-type decisions.

**Comment by jeffreyhanson** [comment]
Hmm, that's strange. Those warning messages are normal when running things in parallel (they are annoying though). I'll take another look.

**Comment by jeffreyhanson** [comment]
Sorry about that, I've just pushed a patch which should fix this. Can you please try it again?

**Comment by jeffreyhanson** [comment]
Great - glad to hear its working now.

**Comment by jeffreyhanson** [comment]
Yeah - that's really encouraging! I think the main bottleneck is probably the number of selected planning units in the solution, not just the total size of the problem, what percentage of the planning units are in the solution?

**Comment by jeffreyhanson** [comment]
Ah - neat - that's still pretty good I reckon! Re-solving a 50k planning unit problem 8k times in 30 minutes is pretty decent?
