### ISSUE TITLE
rarity_weighted_richness warning message for Tas data

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#120]
I'm testing the `rarity_weighted_richness` function.  When I setup the Tasmania dataset as below, I get `replacement_cost` to work fine:

```# load packages
library(prioritizrdata)
library(prioritizr)

# load planning unit data
data(tas_pu)

# load conservation feature data
data(tas_features)

spplot(tas_pu, zcol = "cost", names.attr = "Cost",
       main = "Planning unit costs")

# build problem
p1 <- problem(tas_pu, tas_features, cost_column = "cost", run_checks = FALSE) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.3) %>%
  add_locked_in_constraints("locked_in") %>%
  add_binary_decisions() %>%
  add_boundary_penalties(penalty = 0.0005, edge_factor = 1)

# print the problem
s1 <- solve(p1)

spplot(s1, "solution_1", col.regions = c("grey90", "darkgreen"),
       main = "problem solution")

rc <- replacement_cost(p1, s1[,"solution_1"])

rc$rc[rc$rc > 100] <- 1.09


spplot(rc, "rc", main = "Irreplaceability",  at = c(seq(0, 0.9, 0.1), 1.01, 1.1),
       col.regions = c("#440154", "#482878", "#3E4A89", "#31688E", "#26828E",
                       "#1F9E89", "#35B779", "#6DCD59", "#B4DE2C", "#FDE725",
                       "#FF0000"))
```

When I try to use the `rarity_weighted_richness` function such as this:

```
rw <- rarity_weighted_richness(p1, s1[,"solution_1"])
```

I get the following Warning messages:
> 1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf 

Does this have something to do with the way I specify the solution passed to `rarity_weighted_richness`?

**Comment by jeffreyhanson** [comment]
Hmm, that's strange. I'll try and take a look at this tomorrow night and see what I can do.

**Comment by jeffreyhanson** [comment]
Looks like this is due to divide by zero issues resulting in NaNs in the rarity weighted range calcs because one feature has a zero amount in all planning units - I'll try and get a patch out later today.

**Comment by jeffreyhanson** [comment]
I've just pushed a patch which should address this issue, could you please try recalculating the RWR and see if you get sensible values and no warnings?

**Comment by jeffreyhanson** [comment]
Excellent!
