### ISSUE TITLE
no solution found (e.g. due to problem infeasibility or time limits)

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#121]
I am at a bit of a loss with the error I'm getting for an example I put up [here](https://github.com/ricschuster/KBA_CriterionE_Brazil).

The script that will reproduce the error is `test.R`

What I have tried is using the global IUCN range maps for mammals, convert them to rasters and clip them to Brazil to run through `prioritizr`.

```
# cost = land area of brazil
# biod = raster stack of mammal rasters that meet the following criteria:
# 1: !all(is.na(raster_cropped_to_brazil))
# 2: sum(values(raster_cropped_to_brazil)[!is.na(cost)]) > 10 
p1 <- problem(cost, biod) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions()

# solve problem
s1 <- solve(p1)
# Error in .local(a, b, ...) : 
#   no solution found (e.g. due to problem infeasibility or time limits)
```

I thought criteria 1 and 2 would make sure that only rasters that have enough 1's in the study region are considered, but I might be missing something here, as I still get the error message.

@jeffreyhanson, any idea what it could be?

**Comment by jeffreyhanson** [comment]
Great - I'm glad you were able to fix this. Do you think its worth updating prioritizr so that it throws a warning or something in case other people experience this issue?

**Comment by ricschuster** [comment]
Hmmm. Good question. I think a warning would be great, but wander if that check might take too long? Maybe something that can be bypassed with the `run_checks` and `force` flags?
