### ISSUE TITLE
Locking out proportions?

### ISSUE THREAD

**Issue by Martin-Jung** [prioritizr/prioritizr#126]
Hi,

Is there a way to lock out only a certain proportion of a PU when using proportional decisions? The rest of the PU should still be able to be part of a potential solution.

I tried the `locked_out_constrain` function, but it seems to me as if always removes the entire cell from the solutions (e.g. works binary if the value is != FALSE).

```
# load package
library(prioritizr)
set.seed(31337)

# load data
data(sim_pu_raster, sim_features)

# Overwrite locked out values with simulated fractions
sim_locked_out_raster[sample(1:100,30)] <- runif(30)

# create problem
p <- problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_locked_out_constraints(sim_locked_out_raster) %>%
  add_proportion_decisions()

# solve problem
s <- solve(p)
plot(stack(sim_locked_out_raster,s))

```
Or is there a way to do this with the `add_manual_locked_constraints` function as indicated in the help file? [https://prioritizr.net/reference/add_manual_locked_constraints.html](https://prioritizr.net/reference/add_manual_locked_constraints.html).

In my use case I use a data.frame with pu ids and a fraction of the pu that should not be touched (but the rest can be). If there is no easy way, I might have to do some nasty work-arounds by altering / subtracting values from the rij table  :)  

Thanks in advance for any tipps!
M

**Comment by jeffreyhanson** [comment]
Hey,

The locked constraints are used to specify exactly what values the planning units should have in the solution. In your case, it looks like you want to specify a maximim possible value that the planning unit could have (e.eg. 0.4) but not neccesarily force tha solution to have this value? If so, then take a look at the bounded constraints function (https://prioritizr.net/reference/add_manual_bounded_constraints.html).

Cheers, 

Jeff

**Comment by Martin-Jung** [comment]
Fast as always, thanks ;) Will test out and see If I can make that work.
Merry christmas to you
M

**Comment by Martin-Jung** [comment]
Think it works fine by setting an upper limit based on the (cost - constrain) via `add_manual_bounded_constraints`.
Cheers!
