### ISSUE TITLE
Getting the representation targets

### ISSUE THREAD

**Issue by jivelasquezt** [prioritizr/prioritizr#127]
I'm new to prioritizr and I was wondering if there's a simple way to obtain the representation targets that are set after using the function add_loglinear_targets. This is to double check that the function is doing what I'm expecting it to do.

**Comment by ricschuster** [comment]
Hi,

Thanks for getting in touch.

If you want to have a look at the targets you can use something like this:

```
library(prioritizr)

# load data
data(sim_pu_raster, sim_features)

# create problem using loglinear targets
p <- problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_loglinear_targets(10, 0.9, 100, 0.2) %>%
  add_binary_decisions()

#check feature targets
p$feature_targets()
```

If you want to (also) look at feature representation, you can add this:

```
# solve problem
s <- solve(p)

#feature representation
feature_representation(p, s)

```

Is that what you are interested in? If not, could you maybe provide an example of what you would like to get?

**Comment by jivelasquezt** [comment]
That is perfect (and easy), thank you!

**Comment by ricschuster** [comment]
You are welcome.
