### ISSUE TITLE
selection frequency

### ISSUE THREAD

**Issue by IsaakBM** [prioritizr/prioritizr#128]
I'm new to prioritizr and I was wondering if there's a way to obtain a 'selection frequency' (i.e., the number of times each planning unit was selected across multiple solutions) like Marxan. 

Thanks in advance!
IBM

**Comment by jeffreyhanson** [comment]
Yeah, check out the portfolio methods for generating multiple solutions (https://prioritizr.net/reference/portfolios.html). After generating multiple solutions, you can calculate selection frequency values you R code (see https://prioritizr.net/articles/tasmania.html). Also, you might be interested in functions for calculating irreplaceability scores which -- in my opinion -- provide a better understanding of planning unit importance than selection frequency (see https://prioritizr.net/reference/irreplaceability.html). Does that help?

**Comment by IsaakBM** [comment]
Thanks! I'll try those approaches

**Comment by ricschuster** [comment]
Hi Isaak, 

Just to follow up on Jeff's comments, which I completely agree with, we are currently working on comparing Marxan selection frequency and the metrics Jeff mentioned. For the fairly restricted test case of largely focusing on endemic species across 6 regions globally, we found that irreplaceability (specifically replacement cost: https://prioritizr.net/reference/replacement_cost.html) and pool portfolios (https://prioritizr.net/reference/add_pool_portfolio.html) produce very similar results as Marxan selection frequencies. Again, this is for a special case of endemic and largely range restricted species, but it might be useful for you.

**Comment by jeffreyhanson** [comment]
@IsaakBM it looks like we've resolved your questions for now, so I'll close this issue. Please feel free to reopen this issue if you have any more questions about this topic, or create a new issue if there's anything else we can help with.
