### ISSUE TITLE
velox archival

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#130]
I received a heads up from @jeffreyevans that the velox package is going to be archived soon. I was thinking this might be a good excuse/opportunity to update the raster/polygon extraction functionality with something faster? I was thinking of using the extractr R package (https://cran.r-project.org/web/packages/exactextractr/index.html). What do you think @ricschuster and @mstrimas?

**Comment by ricschuster** [comment]
Too bad that velox is going to be archived, I like that package.
I think taking this as an opportunity to switch to extractr is a good idea though.

**Comment by mstrimas** [comment]
I didn't realize velox was going away nor that exactextractr had been created. Making the switch seems like a great plan!

**Comment by jeffreyevans** [comment]
I am eternally grateful to Jeff Hanson for pointing me to `exactextractr` as I was not aware of this package. I am currently migrating functions in a few packages so I do not get caught up in the CRAN archiving, they are being ruthless and archiving strong reverse dependencies at the same time.

If anybody is interested here is a quick benchmark using the velox, exactextractr, terra (alpha replacement for raster) and raster packages. Interesting note is that exactextractr is a bit slower than velox on small problems but twice as fast on larger ones. With the max.dist argument in knn.graph as 1500 (n=136) velox is twice as fast, at 5000 (n=610) they are the same and with no distance constraint (n=930)  exactextractr is twice the speed of velox. Using exactextractr  in a function environment you also avoid the overhead of coercing into a velox object, which for large data adds quite a bit of time and avoid the odd syntax. The new Rcpp implementation in terra is not very impressive speed wise but faster than raster.

p = utils::installed.packages()[,1]
if(!"devtools" %in% p)
  install.packages("devtools")
if(!"terra" %in% p)
  remotes::install_github("rspatial/terra")
library(terra)
if(!"velox" %in% p)
  install.packages("velox")
library(velox)
if(!"GeNetIt" %in% p)
  install.packages("GeNetIt")
library(GeNetIt)
if(!"raster" %in% p)
  install.packages("raster")
library(raster)
if(!"exactextractr" %in% p)
  install.packages("exactextractr")
library(exactextractr)

data(rasters)
data(ralu.site)

r <- stack(rasters)
graph <- knn.graph(ralu.site, row.names = ralu.site$SiteName,
                                   max.dist = 5000)
x <- rgeos::gBuffer(graph, byid = TRUE, id = row.names(graph),
                    width = 1000, quadseg = 100)

#### Extract using velox
system.time( {
  rvx <- velox::velox(r)
  ldf <- rvx$extract(sp = x)
} )

#### Extract using exactextractr
system.time( {
  vx <- as(x, "sf")
  ldf <- exact_extract(r, vx, progress=FALSE)
} )

#### Extract using terra
system.time( {
  rvx <- rast(r)
  vx <- vect(x, type="polygons", atts=x@data)
  ldf <- extract(rvx, vx)
} )

#### Extract using raster (don’t run, too slow)
system.time( {
  ldf <- extract(r, x)
} )

**Comment by jeffreyevans** [comment]
I realized, while I was modifying code, that `exactextractr::exact_extract` does not support any vector geometry other than polygon. I found a workaround for a function that extract lines (graph) and reverted to raster for point extract as it does not seem too painful for simple [X,Y] geometry.

Best,
Jeff

**Comment by jeffreyhanson** [comment]
@ricschuster, @mstrimas - Ok, I'll get started on replacing velox with exactextractr.

@jeffreyevans, no worries - thank you very much for providing those benchmarks! Also thanks for the heads up about the line/point issues with exactextractr! Also, in case you're not aware and this is helpful, you can also eek out extra performance gains by customizing the compiler flags. For example, try adding these lines to your `~/.R/Makevars` file (you might need to create this if it doesn't exist already) and then re-installing the packages:

```
CXX11FLAGS += -O3 -march=native
CPPFLAGS += -O3 -march=native
```

**Comment by jeffreyhanson** [comment]
As discussed, I've replaced `velox` with `exactextract` for raster data extraction. The affected files are:

* `R/fast_extract.R`
* `tests/testthat/test_fast_extract.R`
* `DESCRIPTION`

**Comment by jeffreyhanson** [comment]
@jeffreyevans (and anyone else interested), I noted that `exactextractr` can be slow for `RasterStack` objects with multiple layers. In such cases  (as of version 0.2.0), it's actually faster to use `exactextractr` to extract the the raw data and compute the summary statistics yourself afterwards. I've included a quick benchmark below showing this for the area-weighted sum:

```
# load packages
library(raster)
library(sf)
library(exactextractr)
library(prioritizrdata)
library(testthat)

# load data
data(tas_pu)
data(tas_features)

# prepare data
tas_pu <- sf::st_as_sf(tas_pu)
tas_features <- tas_features[[seq_len(10)]] # 10 layers

# benchmark area weighted sum using exact_extracts functionality
system.time({  
  out1 <- exact_extract(tas_features, tas_pu, fun = "sum", progress = FALSE)
})
out1 <- t(as.matrix(out1))
#  user  system elapsed 
# 27.829   0.002  27.839

# benchmark area weighted sum using manual processing
system.time({  
  out2 <- exact_extract(tas_features, tas_pu, fun = NULL, progress = FALSE)
  out2 <- sapply(out2, function(x) {
    v <- x[, seq_len(ncol(x) - 1), drop = FALSE]
    p <- x[, ncol(x), drop = TRUE]
    colSums(sweep(v, 1, p, "*"))
  })
})
#   user  system elapsed 
#  7.047   0.000   7.047

# compare results
expect_lte(max(abs(out1 - out2)), 1e-6)
```

**Comment by mstrimas** [comment]
@jeffreyhanson a few bugs in `R/fast_extract.R`, should I fix by pushing directly to `v5` branch or just list them here and let you fix them?

Also, you mentioned we should review `tests/testthat/test_fast_extract.R`, but as far as I can tell that file doesn't exist.

**Comment by jeffreyhanson** [comment]
@mstrimas,Yes  - please do push directly into the `v5` branch - thank you so much for catching the bugs.

Yeah, that's a typo, the file doesn't exist. Yes please! If you could add tests for `fast_extract` that would be amazing!

**Comment by mstrimas** [comment]
Fixed that issue, will add tests. Only other problem I find is a weird edge case where `extract()` gives an error with lines when there is no attribute data. For example,

```
library(prioritizr)
library(sf)
data(sim_features)

l <- matrix(c(0.1, 0.1, 0.9, 0.9), byrow = TRUE, nrow = 2) %>% 
  st_linestring() %>% 
  st_sfc() %>% 
  st_as_sf()
fast_extract(sim_features, l)
#> Error in `[.data.frame`(x@data, i, j, ..., drop = FALSE) : 
#>  undefined columns selected 

# but this works
l$.dummy <- 1
fast_extract(sim_features, l)
```

This doesn't happen for polygons or points. Was thinking we could temporarily add a fake column when this edge case arises or a check to ensure there's always at least one attribute. Preferences?

**Comment by mstrimas** [comment]
Actually, seems it's the conversion to `sp` that's causing the issue. Looks like it'll work if you just pass `extract()` the sf objects

```
l <- matrix(c(0.1, 0.1, 0.9, 0.9), byrow = TRUE, nrow = 2) %>% 
  st_linestring() %>% 
  st_sfc() %>% 
  st_as_sf()
# error
raster::extract(sim_features, as_Spatial(l))
# works
raster::extract(sim_features, l)
```

**Comment by jeffreyhanson** [comment]
Thanks for digging into this. What do you think we should do? We could create a specific `fast_extract` method for `SpatialPoints` and `SpatialLines` and pass the data straight to `raster::extract`? Or we could fix the conversion issue by adding a fake column as you found earlier?

**Comment by jeffreyhanson** [comment]
Sorry, I didn't notice the new `sfc` method before making the previous comment. Thank you very much for fixing that. I'll just quickly add in the missing alias to pass CRAN checks.

**Comment by mstrimas** [comment]
Unless you have a reason not to, I'd remove the `as_Spatial()` calls entirely. Looks like `raster:::.sf2sp()` does the conversion for you within `extract()` and it deals with this edge case when there's no attribute data: https://github.com/rspatial/raster/blob/64b107aeb02615d11cfed56882e237fd8d96823a/R/sf.R

Specifically, the two calls to `as_Spatial` here:

```
if (any(point_idx)) {
        out[point_idx, ] <- as.matrix(raster::extract(
          x = x, y = sf::as_Spatial(y[point_idx, ]), fun = fun2, df = TRUE,
          na.rm = FALSE)[, -1, drop = FALSE])
    }
    # process line geometries
    line_idx <- grepl("LINE", geomc, fixed = TRUE)
    if (any(line_idx)) {
        out[line_idx, ] <- as.matrix(raster::extract(
          x = x, y = sf::as_Spatial(y[line_idx, ]), fun = fun2, df = TRUE,
          na.rm = FALSE)[, -1, drop = FALSE])
    }
```

**Comment by jeffreyhanson** [comment]
Ok - yeah that sounds good to me. Could you please remove `as_Spatial`?

**Comment by mstrimas** [comment]
Done my review. Fixed a few bugs and added unit test in `tests/testthat/test_fast_extract.R`. This is a great, versatile function that I see using as a fast drop in replacement for `raster::extract()` in addition to its intended use within `prioritizr`.

Only odd thing I found is some differences when summary stats are computed by `exactextract` vs. manually in memory. Differences are down in the 6th decimal place, but thought I'd mention just in case. The last test in `tests/testthat/test_fast_extract.R` checks this and I've made it pass by rounding to 5 decimal places for now. Here's a reprex:

```
library(prioritizr)
# in memory
in_mem <- fast_extract(sim_features, sim_pu_sf)
# on disk
options(rasterToDisk = TRUE)
on_disk <- fast_extract(sim_features, sim_pu_sf)
options(rasterToDisk = NULL)
testthat::expect_equal(in_mem, on_disk)
```

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much for the bug fixes and writing the extra tests - I really appreciate it! Yeah, I had a quick look at the source for exactextractr and they use `float`'s instead of `double`'s in their C++ calculations (likely to speed up performance), so I think this difference in precision we're seeing in the tests reflects that of the underlying data types.

**Comment by ricschuster** [comment]
@jeffreyhanson can we close this issue and assume the travis issue resolved?

**Comment by jeffreyhanson** [comment]
Yeah I think so, unless you found anything more issues when looking over the code?

**Comment by ricschuster** [comment]
Thanks. Didn't find anything else.

**Comment by vbhav92** [comment]
> Done my review. Fixed a few bugs and added unit test in `tests/testthat/test_fast_extract.R`. This is a great, versatile function that I see using as a fast drop in replacement for `raster::extract()` in addition to its intended use within `prioritizr`.
> 
> Only odd thing I found is some differences when summary stats are computed by `exactextract` vs. manually in memory. Differences are down in the 6th decimal place, but thought I'd mention just in case. The last test in `tests/testthat/test_fast_extract.R` checks this and I've made it pass by rounding to 5 decimal places for now. Here's a reprex:
> 
> ```
> library(prioritizr)
> # in memory
> in_mem <- fast_extract(sim_features, sim_pu_sf)
> # on disk
> options(rasterToDisk = TRUE)
> on_disk <- fast_extract(sim_features, sim_pu_sf)
> options(rasterToDisk = NULL)
> testthat::expect_equal(in_mem, on_disk)
> ```

Hello,
New to the R community and GIS in R. I was running zonal statistics in ArcGIS and decided to switch to R as I'm dealing with a large number of rasters and need to extract summary statistics (zonal stats to grids).

I found the speed of exactextract to be much better than terra and the base extract in R - however I did notice that the values of statistics were different. 

Both terra, the base R extract, and ArcGIS values matched - exactextract gave values in the range (+-10), but the difference was not just in the decimal place as pointed out. I'm not sure why this is occurring, but I had to revert to terra as that shares consensus among the other programs. Any reason why this might be occurring? The exactextractr documentation does not fully explain the pixels (overlapping, edge) being utilised in processing, or if weighted, which might be why this is occurring.

**Comment by jeffreyhanson** [comment]
Hi,

I think the reason for the different results might be because `exactextractr::exact_extract` -- unlike `raster::zonal` -- takes into account the percentage of each raster pixel that each polygon covers when calculating zonal statistics. To my knowledge, the `raster::zonal`  function does not account for this, and only uses raster pixels that have their centroid inside a polygon when calculating zonal statistics. This means that if a polygon partially overlaps with a pixel, but does not include the centroid of the pixel, then `exactextractr::exact_extract` will use the value of the pixel when calculating the zonal statistics -- but the `raster::zonal` function will not (and this could result in very different outputs given the value of the pixel). I don't know how ArcGIS calculates zonal statistics though, sorry. The exactextractr package is maintained on GitHub (https://github.com/isciences/exactextractr), so it might be worth getting in touch with them about this?
