### ISSUE TITLE
New publication using prioritizr

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#131]
Hi Jeff et al,
A new publication just out from me and many excellent colleagues:

Flower J, Ramdeen R, Estep A, et al. Marine spatial planning on the Caribbean island of Montserrat: Lessons for data-limited small islands. Conservation Science and Practice. 2020;e158. https://doi.org/10.1111/csp2.158

We used prioritizr in the marine spatial planning process, and cite the package of course! 

Would be great if it could be added to the prioritizr publication record, thanks.

**Comment by jeffreyhanson** [comment]
Hi,

Awesome work - massive congratulations! Yes, absolutely - I'll add your paper as soon as I can. Thank you for letting us know about it.

**Comment by jflowernet** [comment]
Excellent, many thanks Jeff!

**Comment by jeffreyhanson** [comment]
Ok, I've added this to `v5` branch. 

The specific file is:
* `vignettes/publication_record.Rmd`

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson! 
What do you think about sub-headers for years and alphabetical order by first author last name within year?

**Comment by jeffreyhanson** [comment]
Yeah, that's a brilliant idea - I'll update that now.

**Comment by ricschuster** [comment]
Awesome! Looks great, thanks.
