### ISSUE TITLE
Bug in boundary matrix calculations for MULTIPOLYGON geometries

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#132]
I found a bug in the `boundary_matrix` function that causes it to under-estimates the total length of multipolygon geometries (e.g. a planning unit comprising two separate localities). I've added a patch to the `v5` branch, and fixed the tests for detecting this. 

@ricschuster, could you take a look at these files?
* `R/boundary_matrix.R`
* `src/rcpp_boundary_data.cpp`
* `tests/testthat/test_boundary_matrix.R`

**Comment by ricschuster** [comment]
Just to double check, is is actually `src/rcpp_boundary_data.cpp` that I should be looking at? I can't find `src/rcpp_boundary_matrix.cpp`

**Comment by jeffreyhanson** [comment]
Sorry, yeah that's correct. I'll update the previous comment with the correct file.

**Comment by ricschuster** [comment]
As far as I can tell (granted that my cpp is super rusty) the code in the three files of this issue is sound, so we can close the issue.

**Comment by jeffreyhanson** [comment]
Awesome - thanks @ricschuster!
