### ISSUE TITLE
New solution pool option

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#134]
Gurobi now has a [`PoolGap` parameter](https://www.gurobi.com/documentation/9.0/refman/poolgap.html#parameter:PoolGap) that can be used along with other parameters to generate a solution pool that contains _n_ solutions that are all within a certain level of optimality. I propose that we add this to prioritizr so that someone could generate 1000 solutions that are all within 20% of optimality. I think this is what users want/need to generate more "useful" selection frequencies, since currently our current functionalities  (e.g. 1000 solutions nearest to optimality) tend to give very similar solutions. What do you think @ricschuster, @mstrimas?

**Comment by jeffreyhanson** [comment]
Also, since adding this functionality to the existing `add_pool_portfolio` function means that the single function will have 3 different behaviors. I propose that we create new separate functions for each behavior, and deprecate `add_pool_portfolio`. The new functions could be:

* `add_extra_portfolio(x = problem)`: store extra solutions found while solving the problem (Gurobi: PoolSearchMode = 1).
* `add_top_n_portfolio(x = problem, n = integer)`: find the best _n_ different solutions (Gurobi: PoolSearchMode = 2, PoolSolutions = n, MIPGap = 0).
* `add_gap_n_portfolio(x = problem, n = integer, gap = double)`: find _n_ solutions within an optimality gap (Gurobi: PoolSearchMode = 2, PoolSolutions = n, PoolGap = gap)

Can you think of better names?

**Comment by jeffreyhanson** [comment]
Or what do you think about `add_head_portfolio` or `add_gap_portfolio`?

**Comment by jeffreyhanson** [comment]
@ricschuster and @mstrimas, when reviewing the code for the new portfolio functions, please refer to:

* `R/portfolios.R`
* `R/add_extra_portfolio.R`
* `tests/testthat/test_add_extra_portfolio.R`
* `R/add_top_portfolio.R`
* `tests/testthat/test_add_top_portfolio.R`
* `R/add_gap_portfolio.R`
* `tests/testthat/test_add_gap_portfolio.R`

**Comment by ricschuster** [comment]
The `PoolGap` parameter sounds very useful. Thanks for bringing this up @jeffreyhanson!

 Given that this would result in a total of 5 portfolio functions (these three, plus `add_cuts_portfolio` and `add_shuffle_portfolio`), I wonder if users would get confused by all the choices for portfolio generation?

Could the three functions you mentioned above be combined into one with changing behavior depending on parameter settings or do you think they are conceptually too different?

**Comment by jeffreyhanson** [comment]
Hmm - good question. 

They could all be condensed into a single function, but I'm not sure that it would make things clearer. Since only certain combinations of parameters will yield different results (e.g. changing `PoolSolutions` and `PoolGap` won't do anything if `PoolSearchMethod` is 1), and some combinations of parameters can have undesireable consequences (e.g. you may not get the top _n_ optimal solutions if `MIPGap` >> 0 even when `PoolSearchMethod` is 2), I worry that users may set some parameters to do something but the parameters don't actually give them what they want?

Also, this approach of having separate functions for different purposes seems conceptually similar to having separate functions for the different objectives functions and not condensing them all into a single function (e.g. something like `add_objective_function(type = "min_set")`)?

**Comment by ricschuster** [comment]
Good points. I think `add_objective_function` might be conceptually important to separate into individual functions. 

With the `pool` family I wonder if we could adopt what you sketched with `add_portfolio(type =  "top")`? This way we would signal the users that this is for generating selection frequencies and there are x number of ways to do so. The parameter settings that would be passed on to the solver would be fixed per type though and a user would not have to worry about meaningless combinations of parameters.  What do you think?

Given that Gurobi has the PoolGap parameter, does that mean other solvers wouldn't be able to generate those portfolios?

**Comment by jeffreyhanson** [comment]
Sorry, just so I understand, are you suggesting a `add_pool_portfolio(type = "top")` or a `add_portfolio(type = "top")` function for all types of portfolios (not just the pool-based ones)?

Yeah, this pool stuff is only for Gurobi.

**Comment by ricschuster** [comment]
Good question. Maybe `add_pool_portfolio(type = "top")` for the pool-based ones, because they are conceptually different from `cuts` and `shuffle`? What do you think?

**Comment by jeffreyhanson** [comment]
Also, I think the gap based pool portfolio method is/will probably be the only real "feasible" method for "meaningful" selection frequencies. In my experience, when using the top-based pool portfolio methods for moderate sized planning problems, the user has to generate a huge number of solutions to obtain solutions that aren't just the same thing with only one planning unit different between them.

**Comment by ricschuster** [comment]
Got it. Maybe `add_pool_portfolio(type = "gap")` as the standard and if users really want to they can specify `top` or `extra`?

**Comment by jeffreyhanson** [comment]
Yeah, maybe that could work. I guess I don't like the idea of having unused arguments if we can avoid it. For example, if we have `add_pool_portfolio(type, number_solutions, gap`, then the last two arguments won't have any effect when `type = "extra"`. Also, when `type = top` we would have to explicitly ignore what ever the user specifies to get the desired behaviour.

**Comment by ricschuster** [comment]
Hmm, maybe it would be best to go with your earlier suggestion to deprecate `add_pool_portfolio` and add new functions. The question I have would be: does it make sense to have the `add_extra_portfolio` and `add_top_portfolio` functions or should we just go with `add_gap_portfolio`? Or rephrased, are `add_extra_portfolio` and `add_top_portfolio` useful?

**Comment by jeffreyhanson** [comment]
Hmm - that's an excellent point. We don't want to add/support functionality that's not going to be used.

The extra portfolio doesn't add a lot of computational burden, so if you wanted to generate a portfolio really, really, really, quickly and didn't care how bad the other solutions in the portfolio then this is exactly what you want. This might be useful in applied settings where you want to show the "best" solution to an interested party (e.g. decision maker?), but also try to un-black-box-ify the method by showing some of the "poorer" solutions it found along the way? Perhaps this might have a more educational use?

I think ideally users would use the top portfolio to generate a huge number of solutions in order to calculate the selection frequencies. But the problem is that for moderate and large problems, you need a huge number of solutions for the solutions to be different enough to give meaningful  selection frequencies (e.g. >1M). Therefore, in such cases, the gap portfolio makes sense because you can use it to generate a reasonable number of solutions that are "different enough" to calculate "meaningful" selection frequencies. But the top portfolio is still ideal for small problems, when only 1'000 solutions are needed to get "different enough" solutions for calculating selection frequencies. Does that make sense? Maybe I'm missing something?

**Comment by ricschuster** [comment]
Thanks for writing our your thinking here. Maybe going with the three functions is the most pragmatic thing to do here.

One thing that would be important is that we document this well and also make recommendations on what functions to use. Every time I have talked to people about the portfolio stuff there was the issue of uncertainty of which function to use and I worry that this might confuse people.

Honestly, I do think that the gap function and the Ferrier method/function will be the two things that will be most useful to users as far as selection frequencies and irreplaceability goes.

**Comment by jeffreyhanson** [comment]
Ok - yeah, I completely agree that it will be important to document this properly. Thanks for raising this point. I've written some recommendations in the help files, so please let me know if they aren't clear enough when you review them.

Yeah, I think so too - I think the Ferrier function will probably be the most useful (though it's a bit I don't know how to generalize it to other objectives).

**Comment by ricschuster** [comment]
Thanks Jeff! Will do.

**Comment by ricschuster** [comment]
Almost through with the review of the new pool options, but wanted to check in with you about `add_gap_portfolio`.
I think the description you gave in the help file about the gap parameter is clear, but I do wonder if gap in `solver` and gap in `add_gap_portfolio` might confuse people? What do you think about using a `pool_gap` parameter in the `add_gap_portfolio` function? Not sure that its necessary, just wanted to bring it up.

Other than that, everything looks great. I've only made a couple changes to deprecated.R. Once the above question is resolved, we can finalize the pull request I think, or am I missing anything?

**Comment by jeffreyhanson** [comment]
Brilliant - yeah, I think changing the parameter to `pool_gap` is a great idea. If you could please change the parameter that would be awesome?

**Comment by ricschuster** [comment]
Done. 
Will close the issue now, as I think we've dealt with everything.

**Comment by jeffreyhanson** [comment]
Awesome - thank you @ricschuster!
