### ISSUE TITLE
partial match of 'rij' to 'rij_matrix'

### ISSUE THREAD

**Issue by mstrimas** [prioritizr/prioritizr#136]
There are ~10 cases in the tests where `rij` is being used to refer to a list element called `rij_matrix`. This isn't an error due to R partial matching behavior, but does raise a warning for me since I have `options(warnPartialMatchDollar = TRUE)`, and I think it would be best to fix this just to be safe.

Example: https://github.com/prioritizr/prioritizr/blob/master/tests/testthat/test_add_boundary_penalties.R#L271

@jeffreyhanson I have a commit ready for this, which I could push to the v5 branch if you'd like.

**Comment by jeffreyhanson** [comment]
Yeah, I completely agree - thanks for catching this! Yeah, if you could please push a fix that would be brilliant.
