### ISSUE TITLE
R-devel (upcoming R 4.0.0)

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#137]
As of R version 4.0.0, all data.frames will have `stringsAsFactors = FALSE` by default. This is currently causing our automated checks on Travis to fail with R-devel. I'll  try and push a fix soon.

**Comment by mstrimas** [comment]
I heard that was coming. I'm surprised they did it, but *very* happy about it! Thanks for taking care of this.

**Comment by jeffreyhanson** [comment]
Done - addressed with https://github.com/prioritizr/prioritizr/pull/135
