### ISSUE TITLE
prioritizr::boundary_matrix R session aborted

### ISSUE THREAD

**Issue by IsaakBM** [prioritizr/prioritizr#138]
Hi @jeffreyhanson 

For some reason, I've been having troubles using boundary_matrix function from prioritizr. Every time that I want to use it my R session is aborted. It was working with no problems a few weeks ago but now it does not. This is my session info:

R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] stringr_1.4.0      lwgeom_0.2-1       prioritizr_4.1.5.2 proto_1.0.0        cleangeo_0.2-3    
 [6] maptools_0.9-5     rgeos_0.5-2        future.apply_1.3.0 future_1.14.0      dplyr_0.8.3       
[11] sf_0.9-2           raster_3.0-12      sp_1.4-1          

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       compiler_3.5.0     pillar_1.4.3       class_7.3-15       tools_3.5.0       
 [6] digest_0.6.25      packrat_0.5.0      lifecycle_0.2.0    tibble_3.0.0       lattice_0.20-38   
[11] pkgconfig_2.0.3    rlang_0.4.5        Matrix_1.2-17      DBI_1.1.0          cli_2.0.2         
[16] rstudioapi_0.11    parallel_3.5.0     e1071_1.7-3        vctrs_0.2.4        globals_0.12.4    
[21] classInt_0.4-2     grid_3.5.0         tidyselect_0.2.5   glue_1.4.0         listenv_0.7.0     
[26] R6_2.4.1           fansi_0.4.1        foreign_0.8-71     purrr_0.3.3        magrittr_1.5      
[31] codetools_0.2-16   ellipsis_0.3.0     units_0.6-6        assertthat_0.2.1   KernSmooth_2.23-15
[36] stringi_1.4.6      crayon_1.3.4 

I'm using it for this kind of R object:

class       : SpatialPolygonsDataFrame 
features    : 4649 
extent      : -564771.3, 3371381, 3113886, 4569951  (xmin, xmax, ymin, ymax)
crs         : +proj=aea +lat_1=60 +lat_2=60 +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
variables   : 2
names       :   Id,      Cost 
min values  :    1,         3 
max values  : 4649, 837815374 

Do you have any hint that could help me?

Thanks in advance
Isaac

**Comment by jeffreyhanson** [comment]
Hi,

I'm not sure why that's causing problems. Maybe the shapefile has invalid geometry and needs to be fixed (e.g. using the repair geometry tool in ArcMap, or the `sf::st_make_valid` function in R)? Could you please send me the planning unit shapefile so I can work out what's going wrong? 

Cheers,

Jeff

**Comment by IsaakBM** [comment]
Hi @jeffreyhanson 

I sent you an email with the shapefile. The curious thing is that I replicate the problem on a cluster machine without any problem. My feeling is that is something related to my local machine after an upgrade of the sf package.

Cheers,
IBM

**Comment by jeffreyhanson** [comment]
Thanks - got it! Looking into this now.

**Comment by jeffreyhanson** [comment]
Just to follow up, I tried generating a boundary matrix for your planning unit dataset using stable and unstable versions for GDAL/GEOS/PROJ and I couldn't reproduce the issue. Here's the code I used (comments indicate outputs) - could you please try this on your computer?

```
# load pacakges
library(sf)
# Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(prioritizr)

# load data
d <- read_sf("costlayer2/costlayer2.shp")
d2 <- as_Spatial(d)

# create boundary matrix
bm <- boundary_matrix(d2)

# session information
sessionInfo()
# R version 3.6.3 (2020-02-29)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Ubuntu 18.04.4 LTS
# 
# Matrix products: default
# BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
# LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
# 
# locale:
# [1] C
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] prioritizr_4.1.5 proto_1.0.0      raster_3.0-12    sp_1.4-1        
# [5] sf_0.9-2        
# 
# loaded via a namespace (and not attached):
#  [1] Rcpp_1.0.4.6       magrittr_1.5       units_0.6-6        lattice_0.20-41   
#  [5] rlang_0.4.5        fansi_0.4.1        tools_3.6.3        rgdal_1.5-6       
#  [9] grid_3.6.3         KernSmooth_2.23-16 cli_2.0.2          e1071_1.7-3       
# [13] DBI_1.1.0          ellipsis_0.3.0     class_7.3-16       assertthat_0.2.1  
# [17] tibble_3.0.0       lifecycle_0.2.0    crayon_1.3.4       Matrix_1.2-18     
# [21] vctrs_0.2.4        codetools_0.2-16   glue_1.4.0         pillar_1.4.3      
# [25] compiler_3.6.3     classInt_0.4-3     pkgconfig_2.0.3   
```

**Comment by jeffreyhanson** [comment]
Over email you mentioned that you had PROJ7 installed and were considering downgrading it in case it was causing the issue. If you're still trying to do this then maybe terminal commands like this might work (based on https://flaviocopes.com/homebrew-install-older-version/):

```
R -e "remove.packages(c('sf', 'rgdal', 'raster', 'rgeos'))"
brew unlink gdal
brew unlink geos
brew unlink proj
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/122f2a2a2c44462823360fc5a1becec968b9abf7/Formula/proj.rb
brew install gdal
R -e "install.packages(c('sf', 'rgdal', 'raster', 'rgeos'))"
```

I don't have access to a Mac OSX computer so I can't test this code - so it might need tweaking or may not even work at all.

**Comment by IsaakBM** [comment]
Hi @jeffreyhanson 

The code is working now, but when you set str_tree = TRUE, it crashed. Can you try:

`bm <- boundary_matrix(d2, TRUE)`

Thanks!
IBM

**Comment by jeffreyhanson** [comment]
Ok great! Yeah, setting `str_tree = TRUE` works for me (just tested with Ubuntu, PROJ version 4). Our automated checks for prioritizr stopped working last week for Mac OSX when testing `boundary_matrix` with `str_tree = TRUE` -- maybe also due to PROJ7 issues? -- so I think this helps confirm the behaviour you're seeing (e.g. see test [here](https://github.com/prioritizr/prioritizr/blob/master/tests/testthat/test_boundary_matrix.R#L74-L98)). We don't set `str_tree = TRUE` by default because it uses the `rgeos::gUnarySTRtreeQuery` function which is indicated as experimental in the rgeos documentation (see [here](https://www.rdocumentation.org/packages/rgeos/versions/0.5-2/topics/RGEOS%20Experimental%20Functions)) and I worry that this means that there is some doubt over its correctness. We might be able to replace this function with something from sf -- but I'm not sure?

**Comment by IsaakBM** [comment]
Yep, I think the problem is using `str_tree = TRUE` with PROJ7. Although not really sure how to replace that function using the sf package. Maybe, for now, would be something like stop using `str_tree = TRUE`.

Thanks for your insights and help!

**Comment by jeffreyhanson** [comment]
Ok excellent - yeah, I'm sorry that I don't have a fix for you. Hopefully, the calculations aren't too long with `str_tree = FALSE`?

**Comment by IsaakBM** [comment]
That's OK. The time is not the problem right now so all good!

**Comment by jeffreyhanson** [comment]
@IsaakBM, could you please do me a favor to help implement a partial fix? If so, could you please run this code below on your computer (with PROJ7) and send me the `test.rds` file?

```
# load data
data(tas_pu, package = "prioritizrdata")
x <- tas_pu[c(2, 4), ]
y <- rgeos::gUnarySTRtreeQuery(x)
saveRDS(y, "test.rds")
```

**Comment by IsaakBM** [comment]
Yep, will do. I'll send the output to your email

**Comment by jeffreyhanson** [comment]
Awesome - thanks!

**Comment by jeffreyhanson** [comment]
Hmm, it looks like that's giving the correct result. Could you please send me the output from running `rgeos::gUnarySTRtreeQuery` on your planning unit data?

```
library(prioritizr)
library(sf)
x <- as_Spatial(read_sf("costlayer2.shp"))
y <- rgeos::gUnarySTRtreeQuery(x)
saveRDS(y, "test.rds")
```

**Comment by IsaakBM** [comment]
That code does not work... R session aborted after running `y <- rgeos::gUnarySTRtreeQuery(x)`

**Comment by jeffreyhanson** [comment]
Ah ok - I was thinking it might be some other code in prioritizr that uses the output from `rgeos::gUnarySTRtreeQuery` so we could do something to avoid the crashing, but if the crashing is happening due to this function then I don't think there's anything we can do. I'll a warning to the  `boundary_matrix` function documentation as you suggested earlier.
