### ISSUE TITLE
remove shiny integration functionality

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#141]
A lot of prioritizr's underlying functions have baked in shiny integration. This was originally implemented with the aim to make it easy to build a shiny interface for prioritizr. However, this shiny functionality (1) massively increases the installation footprint of prioritizr (i.e. users must install the shiny, xtable, and rhandsontable packages) and (2) does not actually appear to provide a useful interface for shiny applications (based on discussion with @ricschuster). Once @ricschuster has made more progress with the shiny app for prioritizr, confirming that existing shiny functionality aren't needed, we can go about removing the baked in shiny integration.

I'm making this issue so I don't forget. @ricschuster did I miss anything? Does that sound like a sensible plan?

**Comment by ricschuster** [comment]
Thanks for opening this issue @jeffreyhanson. This sounds like a good plan to me and once I've made some progress on the shiny app for prioritizr, I will post conformation here, so we can start with the removal of the prioritizr shiny integration.

**Comment by jeffreyhanson** [comment]
Ok excellent - thanks!

**Comment by jeffreyhanson** [comment]
@ricschuster, I just wanted to follow up and ask what your thoughts on this are? Do you think the current integration stuff should be removed, or is it still useful to have?

**Comment by ricschuster** [comment]
At the risk of shooting myself in the foot here, I would say we could remove the shiny integration stuff from prioritzr. I might just be well versed enough in shiny to take advantage of the shiny components in prioritzr, but so far I haven't used any of the shiny stuff in prioritizr while creating shiny interfaces using prioritzr.

**Comment by jeffreyhanson** [comment]
Ok sounds good. I'll start removing the shiny integration stuff this afternoon. I think this will help provide a more pleasant experience for first time users so they don't have wait ages for everything to install.

**Comment by ricschuster** [comment]
Awesome!
