### ISSUE TITLE
Error while checking reverse dependencies in parallel

### ISSUE THREAD

**Issue by schloerke** [prioritizr/prioritizr#143]
While checking `shiny`'s reverse dependencies, I consistently run across an error when calling:

```r
# we could also use the parallel processing options available through "plyr"
# to use more computation resources to complete the jobs (note that since
# these jobs are very quick to process this is actually slower).
cl <- parallel::makeCluster(2, "PSOCK")
```

```
Error in serverSocket(port = port) : 
  creation of server socket failed: port 11172 cannot be opened
Calls: <Anonymous> -> makePSOCKcluster -> serverSocket
```

If I run the checks serially, the check works as expected. 

--------------------

Is it possible to add a `if (interactive())` around the example or manually supply a random port number?

Thank you!
\- Barret

**Comment by jeffreyhanson** [comment]
Thanks for reaching out @schloerke. I'm sorry that we've been causing problems for you. Would it be OK if we wrapped this code in a `\donttest{}` tag? I generally use non-interactive sessions for testing the package so wrapping this in an `if (interactive())` condition would make it difficult for me to test this example.

**Comment by schloerke** [comment]
That should work! Thank you! 

Feel free to wait and see what `@HenrikBengtsson` says in https://github.com/fellstat/ipc/issues/21 on how you could approach your solution.  I believe these are similar in nature.

-------------

I am still able to get a green checkmark on revdepcheck, so I am not blocked.  Thank you for the quick response!

**Comment by jeffreyhanson** [comment]
Ok, I'll patch `\donttest{}` into a branch that should be merged within the next week or so. The fix should then appear on CRAN in a couple of weeks.
