### ISSUE TITLE
Full check with R 4.0.0

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#144]
Before we release the new version on CRAN, I think it would be worth running all the tests and checks (including those skipped on CRAN and Travis because they involve solving problems) with the latest version of R and all the latest packages. Although we can't test this with the latest version of Gurobi (to my knowledge), I can try running all the tests with Rsymphony. @ricschuster, I'm hoping we won't have to make any changes - can I let you know when I've finished running these tests?

**Comment by ricschuster** [comment]
Agreed!
Do you think it would be worth contacting Gurobi for the source code to compile the `gurobi` package? There are a number of functions that require Gurobi and it would be good to test them with the latest version of R. What do you think?

**Comment by ricschuster** [comment]
Just submitted a request for R package source code to Gurobi.

Were you also planning on testing on PROJ 7?

**Comment by jeffreyhanson** [comment]
Thanks!

Good question - I'm not sure. The `UBUNTUGIS=unstable` [Travis builds](https://travis-ci.org/github/prioritizr/prioritizr) test for sf/raster/PROJ7 issues, so I don't think we need to run those tests again locally because all the spatial data processing happens outside of the solving functions?

**Comment by ricschuster** [comment]
Sounds good.

**Comment by jeffreyhanson** [comment]
Ok - I just finished the checks - looks like its all good for CRAN. Shall I bump the package version and update the package website so you can send it to CRAN? Was there anything else we needed to do before sending this to CRAN?

**Comment by jeffreyhanson** [comment]
(Sorry, I closed this by accident, so I've reopened it)

**Comment by ricschuster** [comment]
Thanks Jeff! 
I think that's all we wanted to do before submitting to CRAN again.
If you could update the package website, I can send to CRAN after.

**Comment by jeffreyhanson** [comment]
Ok sounds good - I'll let you know when I've done the version bump and remade the docs.

**Comment by jeffreyhanson** [comment]
I've pushed an update-  but I just want to tweak the readme before we release on CRAN, so I'll let you know when it's ready.

**Comment by ricschuster** [comment]
Sounds good.

**Comment by jeffreyhanson** [comment]
Ok - I've just finished updating the readme + site. When you get a chance, could you please check the package with winbuilder  -- just in case we've missed anything -- and assuming that the checks all pass on winbuilder/travis/appveyor submit it to CRAN?

**Comment by jeffreyhanson** [comment]
The automated travis/appveyor checks just passed - so if this passes winbuilder then I think its good to go?

**Comment by ricschuster** [comment]
Thanks Jeff. Submitted to winbuilder and once that passes will submit to CRAN.

**Comment by ricschuster** [comment]
winbuilder passed and just submitted the package to CRAN.

**Comment by jeffreyhanson** [comment]
Awesome - thank you!
