### ISSUE TITLE
New package for ILP optimization ompr

### ISSUE THREAD

**Issue by mstrimas** [prioritizr/prioritizr#15]
Just saw this new R package `ompr`, which offers a nice unified interface to solver MILP problems using various solvers in R. Unfortunately, doesn't have bindings to Gurobi, so probably not useful for us, but maybe something to keep an eye.

https://github.com/dirkschumacher/ompr

**Comment by ricschuster** [comment]
Thanks Matt. Certainly something to keep an eye on.

**Comment by jeffreyhanson** [comment]
Yeah, looks awesome - thanks for the heads up.
