### ISSUE TITLE
Error setting problem with large number of features

### ISSUE THREAD

**Issue by jivelasquezt** [prioritizr/prioritizr#155]
Hi there,

I'm setting up a problem with a large number of features (604). After initializing with a raster and rasterStack I get the following error:

`p1 <- problem(cost, features)`
Error in FUN(X[[i]], ...) : unused argument (.parallel = FALSE)

Running: `p1 <- problem(cost, features[[1:51]])` works fine:

Conservation Problem
  planning units: RasterLayer (129785 units)
  cost:           min: 1, max: 1
  features:       Ryn_nigerX2018.12.28, Pel_occideX2018.01.04, Pel_occideX2018.01.11, ... (24 features)
  objective:      none
  targets:        none
  decisions:      default
  constraints:    <none>
  penalties:      <none>
  portfolio:      default
  solver:         default

But running: `p1 <- problem(cost, features[[1:52]])` returns the same error (and there's nothing wrong with layer 52, as a subset of layers 51 through 75 also works fine).

I appreciate any insights into this issue. I'm running R 3.6.3 as R version 4 does not have the gurobi library.

**Comment by jivelasquezt** [comment]
To follow up, after aggregating the rasters by 3 to make the problem smaller `p1 <- problem(cost, features)` now works. So it seems to be an issue of problem size.

Conservation Problem
  planning units: RasterLayer (14808 units)
  cost:           min: 1, max: 9
  features:       Ryn_nigerX2018.01.04, Ryn_nigerX2018.01.11, Ryn_nigerX2018.01.18, ... (604 features)
  objective:      none
  targets:        none
  decisions:      default
  constraints:    <none>
  penalties:      <none>
  portfolio:      default
  solver:         default

**Comment by jeffreyhanson** [comment]
Hi @jivelasquezt,

Thank you very much for reporting this bug! I think this bug is due to a typo in the code we use for processing large raster datasets (i.e. large number of cells across all layers), which is why you don't see this bug when you aggregate the data (i.e. reducing the number of cells across all layers). I think we've fixed this bug in the developmental version of prioritizr, could you please try installing it and see if it works?  You can install the developmental version with the following R code:

```
if (!require(remotes)) install.packages("remotes")
remotes::install_github("prioritizr/prioritizr")
```

**Comment by jivelasquezt** [comment]
Hi Jeffrey, I've installed the development version and it doesn't return the error, so my issue is solved (I had already installed this version hoping it would solve the issue, but it didn't kicked in until I restarted my r session). Thank you very much for your help.

**Comment by jeffreyhanson** [comment]
Ok excellent! No worries - glad to help.
