### ISSUE TITLE
Article for your repository of articles that use Prioritizr

### ISSUE THREAD

**Issue by boohubris** [prioritizr/prioritizr#158]
Here you go! Thanks for the help along the way Jeff! Working on a follow-up paper that does a ton more sensitivity explorations.
https://doi.org/10.3389/fsufs.2020.00138

Bryant, B.P., Kelsey, T.R., Vogl, A.L., Wolny, S.A., MacEwan, D.J., Selmants, P.C., Biswas, T. and Butterfield, H.S., 2020. Shaping land use change and ecosystem restoration in a water-stressed agricultural landscape to achieve multiple benefits. Frontiers in Sustainable Food Systems, 4, p.138.

**Comment by jeffreyhanson** [comment]
Awesome, no worries! Congratulations - this looks really interesting - I'm looking forward to reading this!

**Comment by jeffreyhanson** [comment]
I've just pushed an update to add the paper to vignette, so I'll close this now.
