### ISSUE TITLE
add_semicontinuous_decisions() + add_gap_portfolio()

### ISSUE THREAD

**Issue by kkemink** [prioritizr/prioritizr#159]
I'm having issues running a conservation prioritization problem that uses both the "add_semicontinuous_decisions" and the "add_gap_portfolio" options. This could very well be a result of just not understanding the program well enough (in which case, sorry - can you please explain?), but I could 'solve' the problem fine when I ran it with one or the other option. Combining them seems to be what causes the issue. In this case the issue is that the program solves the problem as if the "add_gap_portfolio" option was not present. I even tried cranking the upper limit of the semicontinuous decisions to 1 to see if that would help. Happy to send code and data via email - it's unpublished yet though so not sure I can post it up here without contacting all the coauthors...

**Comment by jeffreyhanson** [comment]
Yeah, the gap portfolio options only "work" with binary decisions. If you try adding this portfolio to a problem with semicontinuous decisions then it will basically have no effect. Unfortunately, this is a limitation of the Gurobi software so there's not much we can do to fix this. I'll update the documentation to make this clear - sorry for the confusion. Is there anything else I can help with?

**Comment by kkemink** [comment]
No I think I'm good at the moment - thanks for your reply. That clears it up!

**Comment by jeffreyhanson** [comment]
Ok great - I'll leave this issue open then to remind me to update the docs.
