### ISSUE TITLE
Evaluating solutions

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#161]
I'll have a bit more time to work on prioritizr over the next while, so I was thinking this might be a good time to add some quality of life functions for evaluating solutions. In particular, I think it would be really useful if we added functions for calculating: solution cost and various connectivity metrics (e.g. perimeter / area ratio, total connectivity, largest reserve size, minimum reserve size, median reserve size). What do you think @ricschuster and @mstrimas? Can you think of any others?

Also, I was wondering how we should name these functions? Since prioritizr uses suffixes for different problem components (e.g. objectives, penalties, decisions, constraints), maybe we should use suffixes for these functions too? What would be good suffix for these functions? I imagine they would output a single number (possibly per zone?) per solution. Maybe something like `_metric`? Or `_summary`? Thoughts?

**Comment by jeffreyhanson** [comment]
Regarding connectivity stuff, perhaps this package might be useful: https://cran.r-project.org/web/packages/lconnect/lconnect.pdf

**Comment by ricschuster** [comment]
I like this idea @jeffreyhanson!
The functions you propose all make sense. Can't think of additional ones at the moment.
I have a slight preference for `_summary` over `_metric`, but not a strong one

**Comment by mstrimas** [comment]
Yeah, this sounds like an awesome add! I like the idea of naming consistency, but don't have a preference for `_summary` vs. `_metric`.

**Comment by jeffreyhanson** [comment]
Ok great! Let's go with summary then. To be consistent, should we also rename `feature_representation` to `feature_representation_summary` since this function is also designed to summarize the performance of a solution in some way?

**Comment by jflowernet** [comment]
Just to add my vote, this will be very useful! I just found `feature_representation` which is very handy. I would have a preference for `_summary`, but whatever makes most sense to most people. Thanks!

**Comment by ricschuster** [comment]
`feature_representation_summary` sounds like a good idea for consistency. 
Thanks!

**Comment by jflowernet** [comment]
@jeffreyhanson Another useful summary function (for me at least!) would be % of planning units in the solution. I know a quick bit of raster math can get that, but would be handy to have a ready made function!
Thanks!

**Comment by jeffreyhanson** [comment]
Yeah - that's a great idea - thanks! We could also add a function to report the number of selected planning units too.

**Comment by jeffreyhanson** [comment]
I'll close this now because we've merged this functionality into the master branch.
