### ISSUE TITLE
Replication in prioritizr

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#162]
Hey prioritizr people,
Not specifically an issue, but I wanted to check I wasn't missing anything in the way prioritizr can be used. In short the question is how can you incorporate replication of habitats into a prioritization? e.g. overall target for habitat X is 30% but I want to make sure there are at least two separate contiguous areas where that habitat is represented. Unless I'm mistaken, there isn't a way to include this requirement in prioritzr since it looks at the whole landscape.
One thought would be to divide up the landscape and run the prioritization for each section separately. I'd welcome any thoughts from the wonderful minds behind prioritzr.

**Comment by jeffreyhanson** [comment]
Hey @jflowernet! Yeah, prioritizr doesn't really have the functionality to support this properly. Also, the maths to implement this properly are a bit over my head, so it's not something I can easily add to prioritizr. Here's some ideas:

1. One option could be to use multiple zones (with each zone corresponding to a different contiguous area in the solution) then use (i) boundary penalties clump together adjacent planning units in the same zone and penalize adjacent planning units allocated to different zones, or (ii) contiguity constraints to force all the planning units in the same zone to form a single contiguous reserve. This could take a long time to solve though. 

    See [here](https://github.com/prioritizr/prioritizr/issues/129#issuecomment-582125129) for some code to implement this idea. Note that if you don't care about the size of each reserve, then you would just set the `minimum_reserve_size` variable to 1. The issue with this is that you have to specify exactly how many the reserves should be in the solution, instead of letting this happen as some emergent property based on the number of independent reserves you want per feature.

2. If you have reason to believe that each feature has variation within it (e.g. a species might have intra-spcific variation with different subgroups found in different habitat types), another option could be to subdivide each feature by another layer (e.g. habitat types), set targets for each subdivision, add boundary penalties, and "hope" that the solution represents each feature in multiple reserves.

Does that help? Let me know if anything's not clear?

**Comment by jflowernet** [comment]
Thanks so much for the quick and very helpful reply @jeffreyhanson . If the maths are over your head it must be craaazy difficult!

It's great to have the options laid out, and I was wondering if the zones functionality might be useful for this, so thanks for linking to the example you already put together. We're still in relatively early stages of the planning process but it's good to understand what can and can't be done within prioritizr.

As ever, thanks for both your help with this and for all the work you've done to make prioritizr the very useful package it is. 

I'll drop you a line if I have any further questions down the road, but will close this question for now, thanks!

**Comment by jeffreyhanson** [comment]
No worries - happy to help!
