### ISSUE TITLE
Memory issues caused by assertions in problem()

### ISSUE THREAD

**Issue by mstrimas** [prioritizr/prioritizr#164]
We have a large problem (28,333 features, 1,518,008 PUs) being input using a sparse matrix passed to the `rij_matrix` argument to `problem()`. The sparseMatrix object is ~ 4 GB, yet calling `problem()` eats up > 100 GB of memory leading to a ` vector memory exhausted (limit reached?)`  error. It appears to be coming from one of the assertions ([here](https://github.com/prioritizr/prioritizr/blob/master/R/problem.R#L811)) on the input data:

```
all(vapply(rij_matrix, function(x) sum(is.finite(x)), numeric(1)) > 0)
```

I think this may be forcing the sparseMatrix to be filled in to a full matrix. I believe this will fix the issue, by working only on a vector of non-zero values:

```
all(vapply(rij_matrix, function(x) sum(is.finite(x@x)), numeric(1)) > 0)
```

Will submit a PR for this, but hoping @jeffreyhanson can confirm what I'm doing makes sense since I haven't worked with the package source code in a long time.

**Comment by ricschuster** [comment]
Fixed with #165
