### ISSUE TITLE
Alternative CI?

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#166]
[Travis CI has updated their limits for OSS projects.](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) With their new billing system, we would get 10k free credits per month, which would equate to 1000 minutes of free Linux builds per month. Given that each build of prioritizr takes ~40 minutes and we need to test 5 different configurations (e.g. release, dev, osx, linux). This means we could only do 6 CI runs per month. So, I think we need to look at alternative CI services. Do you have any ideas? Have you tried [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration)?

**Comment by ricschuster** [comment]
That's unfortunate to hear. I haven't heard much about `GitHub Actions` other than it existing.
Not sure about alternatives really, sorry.

**Comment by jeffreyhanson** [comment]
I've updated the [wdpar R package](https://github.com/prioritizr/wdpar) to use GitHub Actions instead of Travis + Appveyor for continuous testing. Here's what the CI interface looks like (https://github.com/prioritizr/wdpar/actions) - what do you think? I've created separate "workflows" for Ubuntu/Windows/Mac to keep track of the different platforms (e.g. in case there's a dependency issue on Mac, it won't cause problems for Ubuntu/Windows platforms). Thoughts? To my knowledge, GitHub Actions does not impose any limits for open source project? Should I update the prioritizr repo to use GitHub Actions like this?

**Comment by ricschuster** [comment]
Great! Looks good to me and according to the documentation public repos don't have any limits put on them. I'm all for moving from Travis to GitHub Actions for prioritizr.
Thanks!

**Comment by jeffreyhanson** [comment]
Ok excellent - I'll get started on switching over to GitHub Actions. I'll also update prioritizrdata for GitHub Actions as well.

**Comment by ricschuster** [comment]
Thanks Jeff!

**Comment by jeffreyhanson** [comment]
I've finished switching over to GitHub Actions, so I've closed this issue.
