### ISSUE TITLE
Tasmania tutorial on CRAN showing gazillion warnings

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#168]
Not really a big issue, but just to let you know the [Tasmania tutorial on CRAN](https://cran.r-project.org/web/packages/prioritizr/vignettes/tasmania.html) is showing about a gazillion warning messages in it:
`Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO"): Discarded datum WGS_1984 in CRS definition,
 but +towgs84= values preserve`

**Comment by jeffreyhanson** [comment]
I've worked out a fix (looks like a bug in sp::spplot) - I'll patch it in the next commit.
