### ISSUE TITLE
New CRAN release?

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#169]
@jeffreyhanson should we prep a CRAN release, given the recent updates to `prioritizr`? Would be nice to get CPLEX, the memory issue fix and the other updates on CRAN.

**Comment by jeffreyhanson** [comment]
Yeah that sounds good. I'll be making more progress on #161 in a bit, so it would be good to have another "minor" release out before we do a potentially version breaking release (e.g. if we decide to rename the feature representation function to be consistent with other evaluation functions).

**Comment by ricschuster** [comment]
Sorry for being so slow. @jeffreyhanson do you want to update the `prioritizr` website and such before I get the package ready for CRAN? I might be able to get everything ready tomorrow or Friday.

**Comment by jeffreyhanson** [comment]
Sorry I completely forgot to reply to you, I'll update the package version and website today and let you know when it's ready for CRAN.

**Comment by ricschuster** [comment]
No worries and thanks very much!

**Comment by jeffreyhanson** [comment]
I updated the version number and added some more records to the pub vignette. Since the CI builds just passed, I think this is now ready for CRAN? Can you think of anything I'm missing?

**Comment by ricschuster** [comment]
Thanks Jeff! I can't think of anything else and will start the submission process now.

**Comment by jeffreyhanson** [comment]
Ok - awesome - thanks!

**Comment by jeffreyhanson** [comment]
Since the new version is on CRAN now, I'll close this issue
