### ISSUE TITLE
Add comparison of solvers to the documentation

### ISSUE THREAD

**Issue by ninsbl** [prioritizr/prioritizr#170]
In a project we are considering to use prioritizR (again). However, after we ran into trouble with the SYMPHONY solver on more complex problems earlier (#53), we are not sure if we can use prioritizR in a way we would need to. Neither do we know if purchasing e.g. a gurobi solver license could make it feasible.

In the documentation you mention the performance differences of the solvers, as does e.g. the technical paper here: https://prod-ng.sandia.gov/techlib-noauth/access-control.cgi/2013/138847.pdf). However, it would be realy nice to have that quantified for the use-case(s) in prioritizR. Cause other users of prioritizR may be faced with similar questions, I think it would be good to have a comparison of available solvers in the documentation. Such a comparison could illustrate what problem sizes are solvable within reasonable processing time on a standardized, decent machine with the different solvers and how the solvers scale (time to complete) by e.g. running a problem with (and without) connectivity constraints and boundary penalties, over a decreasing PU size...

**Comment by jeffreyhanson** [comment]
Yeah, I completely agree that the documentation is pretty vague about this -- sorry about that. [In case you haven't read it, @ricschuster recently led a study which benchmarked prioritisations generated using (i) prioritizr with Gurobi, (ii) prioritizr with Rsymphony, and (iii) Marxan with simulated annealing](https://peerj.com/articles/9258/). Specifically, this study involved generating prioritizations with different methods, settings (e.g. with and without boundary penalties), and different sized datasets (e.g. different numbers of features and planning units; see Table 1 for details). It recorded the run times and also the performance of the prioritizations too (see Figures 1 and 2 in Results section). Does this have the information you're looking for? Or is there an additional information that would be helpful?

Also, we recently added support for IBM CPLEX (another commercial solver) to prioritizr. If you're not able to access Gurobi, maybe you can access this solver? It has a community edition that can solve problems up to a certain size (1k decision variables if I remember correctly; e.g. 1km planning units with  min set objective and no boundary penalties).

**Comment by ninsbl** [comment]
Thanks so much for the info. Yes, that is indeed already very useful information. Nice paper, BTW!
Something like figure S-6 in the docs would be very instructive.
Will inspect CPLEX.

BTW: This is the report where we used prioritizR to assess wolverine management zones in Norway, a highly politcal topic with a high conflict level:
https://brage.nina.no/nina-xmlui/handle/11250/2564869
The report is Norwegian but it has an english summary...

**Comment by jeffreyhanson** [comment]
Ok - awesome! I'll update the package documentation to point readers to the paper for benchmarking info.

Brilliant - that looks really interesting - nice work! Let me know if you end up publishing an English version of it?

**Comment by ricschuster** [comment]
Thanks very much @ninsbl!

@jeffreyhanson, do you think we should write up a page related to the benchmarking in the documentation? We could use the figures from the paper and frame this in a way to fit with the general structure of the documentation. What do you think?

**Comment by jeffreyhanson** [comment]
Yeah, that would be awesome. If you still have the figures handy from the recent benchmarks you ran with CPLEX, we could add those to the vignette?

**Comment by jeffreyhanson** [comment]
Also, what's schedule like at the moment? Do you have time to take point on this?

**Comment by ricschuster** [comment]
Good idea re: CPLEX. 
I don't think I could get to this before the new year. If you want to crack at this before that, I could send you the CPLEX figures.

**Comment by jeffreyhanson** [comment]
Yeah I'm pretty swamped too, so I probably won't be able to write up a new vignette anytime soon. In the meantime, I can definitely add a quick note to the docs about the PeerJ paper though.

**Comment by ricschuster** [comment]
Thanks very much Jeff!
I'm going to open an issue and assign it to me than.

**Comment by jeffreyhanson** [comment]
Awesome - thanks!

**Comment by jeffreyhanson** [comment]
Since I haven't updated the docs to note the PeerJ paper yet, I'll reopen this issue and then close it with the relevant commit.

**Comment by ricschuster** [comment]
Yeah, sorry about that.

**Comment by jeffreyhanson** [comment]
No worries :)

**Comment by ninsbl** [comment]
Cool. Thanks!

**Comment by jeffreyhanson** [comment]
Just following up in case anyone comes across this issue when googling for help, we ended up adding benchmarking the performance of different solvers (see https://prioritizr.net/articles/solver_benchmarks.html)
