### ISSUE TITLE
eval_replacement_importance and SpatialPolygon* bug

### ISSUE THREAD

**Issue by PhDyellow** [prioritizr/prioritizr#176]
I want to use eval_replacement_importance() on a SpatialPolygonsDataFrame, but I am getting an error.

I am using the current master commit, ef165ba, in R 4.0.3.

As a reproducible example, I followed the example from `?prioritizr::solve`, then added a call to `eval_replacement_importance`:
```r
data(sim_pu_raster, sim_pu_polygons, sim_pu_sf, sim_features,
     sim_pu_zones_stack, sim_pu_zones_sf, sim_features_zones)
p2 <- problem(sim_pu_polygons, sim_features, cost_column = "cost") %>%
       add_min_set_objective() %>%
       add_relative_targets(0.1) %>%
       add_binary_decisions() %>%
       add_default_solver(verbose = FALSE)
s2 <- solve(p2)

# calculate importance scores
rc2 <- eval_replacement_importance(p2, s2)
```

It throws this error:
```R
Error: number_of_zones(x) not equal to ncol(solution@data)
```

I can make it work by doing this:

```R
s2x <- s2
s2x@data <- s2@data[, "solution_1", drop = FALSE]

# calculate importance scores
rc2x <- eval_replacement_importance(p2, s2x)
```
but it isn't documented.

This also works, which I figured out by looking at `eval_feature_representation_summary`

```R
rc2 <- eval_replacement_importance(p2, s2[,"solution_1"])
```

**Comment by jeffreyhanson** [comment]
Thank you very much for raising this issue! Yeah, that's correct, all the functions starting with `eval_` need you to select/specify/subset the columns containing the solution values when your planning unit data are in a `Spatial`/`sf`/`data.frame` format. I'll update the documentation to make this clearer.

**Comment by jeffreyhanson** [comment]
@PhDyellow, just to keep you in the loop, I've made a PR to fix this documentation issue. If you want to take a look at it, you can install prioritizr from the `minor-tweaks` branch and see the (1) new Solution format section for the `eval_replacement_importance` function documentation and (2) new example using `sf` data (the syntax would be the same for SpatialPolygonDataFrame planning units). I'll close this issue once we've merged it to the main branch.

**Comment by PhDyellow** [comment]
Thanks @jeffreyhanson, the example code and and help documentation are clear now.

**Comment by jeffreyhanson** [comment]
Ok - excellent! Thanks for taking a look at it.
