### ISSUE TITLE
support the CBC solver

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#178]
The [CBC software is an open source ILP solver by COIN-OR](https://projects.coin-or.org/Cbc) that apparently can perform faster than SYMPHONY [(as of 2012)](https://list.coin-or.org/pipermail/cbc/2012-January/000755.html).  @ricschuster and @mstrimas, have you looked into solving conservation planning problems with this software? There's a developmental version of an R interface on GitHub [(i.e. the rcbc R package)](https://github.com/dirkschumacher/rcbc) that seems to work (on Ubuntu at least). Although it's rcbc is only available on GitHub -- if this solver is much better than SYMPHONY -- it might be worth adding it to prioritizr? What do you think?

**Comment by ricschuster** [comment]
Thanks for looking into this @jeffreyhanson !
I've only looked into CBC a little bit when I first started playing around with COIN-OR. 

Would be great to give this a try. Have you done any testing with the package yet? 
If its faster than SYMPHONY, it would be great to add it to prioritizr.

**Comment by jeffreyhanson** [comment]
Neat! Nah, I haven't really done much testing with the package, I just ran the example in the README and it returned a solution. [It does contain some tests to verify that it correctly solves a simple problem though.](https://github.com/dirkschumacher/rcbc/blob/master/tests/testthat/test-cbc-solver.R) Yeah, even if it has comparable performance to Rsymphony, it might be more useful then Rsymphony because you can specify a relative optimal gap (per the `RATIO` parameter, http://www.decom.ufop.br/haroldo/files/cbcCommandLine.pdf)

**Comment by jeffreyhanson** [comment]
I think SYMPHONY might also support a relative optimality gap too, it's just not available via the Rsymphony (and lpsymphony) packages. It might be worth reaching out to the (their) maintainers at some point to see if we could help add such functionality.

**Comment by ricschuster** [comment]
A relative optimality gap parameter in an open source solver would be really handy.
If you go ahead with CBC solver implementation, please let me know how I can help with testing and such.

Getting in touch with the SYMPHONY maintainers to ask about relative optimality gap sounds like a good idea too.

**Comment by mstrimas** [comment]
I haven't kept up at all with the ILP solver landscape and hadn't heard of CBC before. However, based on what you're saying it would be great to add it! That `RATIO` parameter alone would be super valuable.

**Comment by jeffreyhanson** [comment]
Ok sounds great - thanks @ricschuster and @mstrimas! I'll cc you when I've got a PR ready.

**Comment by tkralphs** [comment]
Just found this PR through @jeffreyhanson's inquiry to me. If you have any questions about Cbc versus SYMPHONY, feel free to ask, I'm actually a maintainer for both.

**Comment by jeffreyhanson** [comment]
Awesome - thank you @tkralphs. Would GitHub be the best place to ask? Or would you prefer me to ask them on a mailing list?

**Comment by tkralphs** [comment]
@jeffreyhanson We're trying to move off of mailing lists and onto Discussions, although there isn't a great place for asking a broad cross-project question like this. For now, I would post on Cbc Discussions for questions pertaining to how Cbc compares to other solvers.

**Comment by jeffreyhanson** [comment]
@tkralphs Ok - will do - thanks!
