### ISSUE TITLE
Increased test coverage on CI

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#181]
It might now be feasible to run a lot more of the unit tests on GitHub Actions, because the CBC solver can solver problems relatively quickly. This would have the benefit of greater cross-platform testing and potentially reduces chances of bugs. I could create a PR that replaces the `skip_on_ci()` skips in the unit tests with `skip_if_not_installed("rcbc")`? This would not affect the unit tests that CRAN runs, since the relevant unit tests would still contain `skip_on_cran()`? @ricschuster, what do you think? The downside is that individual CI runs will likely longer to complete.

**Comment by ricschuster** [comment]
I think this is a great idea and doing this would certainly outweigh the longer CI runs I think.

**Comment by jeffreyhanson** [comment]
Ok, I'll take a look into this and see what I can do.
