### ISSUE TITLE
lpsymphony solver not memory efficient

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#183]
The lpsymphony solver seems to convert the [constraint matrix from a sparse format to a non-sparse format](https://github.com/prioritizr/prioritizr/blob/master/R/add_lpsymphony_solver.R#L102-L111) (for some reason?). This might explain the memory consumption issues @ricschuster is experiencing in https://github.com/prioritizr/benchmark/issues/4. I'll see if if it's possible to use a sparse matrix format instead ([it seems like this is possible with the Rsymphony solver](https://github.com/prioritizr/prioritizr/blob/master/R/add_rsymphony_solver.R#L90-L98)).

**Comment by jeffreyhanson** [comment]
After looking into this further, I'm guessing the unexplained/undocumented reason was that lpsymphony does not support sparse Matrix-class objects (from the Matrix R package). Instead, it only supports sparse matrix-class objects from the slam R package -- so we would need to add slam to the package dependencies to support this functionality.

I personally feel like it's worth adding slam to the package dependencies since (1) this will potentially make lpsymphony runs faster, and (2) users would need to install slam anyway to use Gurobi. So, I'll add slam to the package dependencies and update the lpsymphony solver to use a sparse matrix format. How does that sound @ricschuster?

**Comment by ricschuster** [comment]
Very interesting.

Adding `slam` to the package dependencies sounds like a good idea.

And yes, anyone wanting to use Gurobi needs slam anyways.

**Comment by jeffreyhanson** [comment]
Ok great! I'll try and have a PR ready for you in an hour or two (it takes ~30 minutes to run all the tests on my system, and longer to rebuild all the docs).
