### ISSUE TITLE
Starting solution for Gurobi solver

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#187]
It would be useful to update the solver functions so that users can specify a starting solution. Although Rsymphony, lpsymphony, and rcbc don't currently support this, we could add it to the Gurobi solver (and possible CPLEX)? The trick is that the underlying solver needs to allow us to feed in a partial starting solution (so that users only need to specify planning unit statuses in the solution, and not a value of every single variable in the optimization problem).

This functionality will be exceptionally useful for users conducting a boundary/connectivity parameter calibration analysis (where the solution for given penalty value in the calibration process can be a useful starting solution for the next [higher] value). I've been using a hacky wrapper for this functionality in some of my own work, but it would be good to have this functionality properly in prioritizr.

**Comment by ricschuster** [comment]
Sounds awesome to me!
Too bad that this will not work for the open source solvers, but would really help a lot for calibration it sounds like.
