### ISSUE TITLE
rij_matrix documentation

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#189]
Am I messing things up in my head or should the following part of the `rij_matrix` function documentation actually be reversed?

`Rows correspond to planning units, and columns correspond to features.`

It should really be:
rows = features 
cols = pu's

**Comment by jeffreyhanson** [comment]
Yeah, that's wrong. It should indeed be rows = features, cols = pu's. I'll fix it today.

**Comment by ricschuster** [comment]
Thanks Jeff!
