### ISSUE TITLE
Allow marxan_problem to use the INPUTDIR argument in the Marxan param file

### ISSUE THREAD

**Issue by DanRosauer** [prioritizr/prioritizr#19]
The marxan parameter file - usually input.dat - has an INPUTDIR argument for the input directory, but I understand that marxan_problem() is constrained to using a directory directly below the location of the Marxan input file.

Could INPUTDIR and OUTPUTDIR be allowed to specify any paths?

An advantage of allowing any directory to be specified, is that many problems can then be run from the same input data.  For large projects with many problem variants, this can be a major saving of space and complexity.

**Comment by jeffreyhanson** [comment]
Sorry for the late reply, I've got a small amount of time up my sleeve at the moment so I'm trying to address some prioritizr issues. 

I just want to double check that I understand correctly. Is the issue that it doesn't allow Marxan input.dat files with complete file paths? For example, something like: `C:\Users\jhanson\Downloads`? 

If so, should the file name fields (eg. `SPECNAME` , `PUNAME`) also allow complete paths?

**Comment by jeffreyhanson** [comment]
Also, I don't think prioritizr does anything with `OUTPUTDIR`. Would you like to see `prioritizr` save output files similar to Marxan?

**Comment by jeffreyhanson** [comment]
The following commit will enable absolute file paths in `INPUTDIR`, `SPECNAME`, `PUNAME` and etc. Please re-open this issue if I have misinterpreted the nature of the issue.

**Comment by DanRosauer** [comment]
Hi Jeff

I haven’t checked this behaviour recently, but I think there is a parameter called input, which specifies an input folder path.  Then the other files eg spec.dat would be within that folder.

And my understanding is that it doesn’t read that value, and just looks for a folder called input at the current location.

So both the folder, and the specific paths should be able to specify a full or relative path.  And my apologies if all or some of that already works.

Dan

**Comment by DanRosauer** [comment]
Yes, a great idea.  Makes it one step easier to bring Marxan users in to the prioritizr world.

I have my own code now that does something similar

**Comment by jeffreyhanson** [comment]
Ok, I think I've addressed the issue with the regarding the absolute file paths. Feel free to reopen this issue if it's still not working. I haven't properly tested it on Windows, but it works on Ubuntu.

I'll make another issue with Marxan outputs.
