### ISSUE TITLE
Large problem running out of memory

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#193]
It would be useful to support the `NodeFileStart` parameter in Gurobi so that users can solve large-scale problems on systems with insufficient RAM (and swap space). This suggestion was originally raised by @AlecNelson in https://github.com/prioritizr/prioritizr/issues/192.

**Comment by jeffreyhanson** [comment]
In reply to your post @AlecNelson,

> Not the original commenter, but I have a similar challenge with running a prioritization problem with the Gurobi solver and wanted to ask about the "NodefileStart" parameter as one possible solution:
> 

Yeah - that's a great idea. I'll try and update the version of prioritizr on GitHub with this functionality sometime soon.

> Specifically I am running a problem with 1,130,526 planning units (100m raster cells), solving for min_set_objective at a 0.1 gap and binary_decisions with a range of relative_targets (currently exploring different values of targets). When I add_neighbor_constraints, even low values, the solver will report that it has run out of memory (10001. OUT OF MEMORY.) on a machine with 16GB of RAM and 6 cores. Having just seen your suggestions to the question above, I will certainly try to implement those steps to working out a solution that completes within a reasonable time and fits the conservation problem setting I am working towards.

Yeah, that's a lot of planning units, and the optimization problem becomes even (by a lot) larger when you include additional constraints/penalties for spatial configuration. Since you're not trying to use feature contiguity constraints I don't think all of those suggestions are relevant in your particular case, but reducing the total number of planning units would definitely help (if possible).

> However, I also wanted to ask about the Gurobi parameter that is suggested in their documentation, namely the "NodefileStart" parameter. I can't find much documentation about this parameter, especially in R or prioritzr, but it appears to be one solution to problems that exceed the system memory by writing problems temporarily to the harddrive.
>
> When I scour the prioritzr documentation, I've found the get_solver_parameter and set_solver_parameter options for modifying problem objects, but I can't seem to figure out what the id value would be for "NodefileStart" (running "p1$set_solver_parameter("NodefileStart",0.5)" returns "Error in res(x, ...) : parameter with matching name not found").
> 
> Any assistance you could provide on this particular approach to getting past this problem of running out of memory beyond the helpful suggestions you've mentioned above would be very much appreciated! Thanks!
> 

Thanks, I really appreciate that you tried to get this working before posting here. Unfortunately, the set solver parameter doesn't really work like that, and only let's you change the values of parameters that are currently supported by a given solver (e.g. like `time_limit`). I'll update prioritizr so that you can specify the `NodeFileStart` parameter using `add_gurobi_solver()`.

> My problem setting function:
> 
> p1 <- problem(sav_pu, sav_features) %>%
> add_min_set_objective() %>%
> add_relative_targets(0.1, 0.1, 0.1, 0.6, 0.6, 0.6) %>%
> add_binary_decisions() %>%
> add_boundary_penalties(0.0005, 0.5) %>%
> add_gurobi_solver(gap = 0.1, time_limit = 7200, threads = 2, first_feasible = FALSE)%T>%
> run_calculations()
> 
> p1$set_solver_parameter("NodefileStart",0.5) ##returns "Error in res(x, ...) : parameter with matching name not found"

Thanks for providing this information - that's really helpful! I think I should be able to update prioritizr so you can specify the `NodeFileStart` parameter without too much trouble. Also, just to let you know, the targets should be specified (in your particular case) as a vector (i.e. `add_relative_targets(c(0.1, 0.1, 0.1, 0.6, 0.6, 0.6))` and not a series of separate arguments (i.e. `add_relative_targets(0.1, 0.1, 0.1, 0.6, 0.6, 0.6)`) -- I'm a bit surprised the code you posted didn't throw an error though?

**Comment by jeffreyhanson** [comment]
I've created a PR to address this issue. It needs to be reviewed before it can be merged into the main branch. In the meantime, you can install it with the following code:

```
remotes::install_github("prioritizr/prioritizr@nodestart")
```

**Comment by jeffreyhanson** [comment]
Just to keep you in the loop @AlecNelson, the PR was just merged into the main branch so you can now install it with:

```
remotes::install_github("prioritizr/prioritizr")
```

For example, you could adapt your code to something like the following to avoid the memory issues:

```
p1 <- 
  problem(sav_pu, sav_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1, 0.1, 0.1, 0.6, 0.6, 0.6) %>%
  add_binary_decisions() %>%
  add_boundary_penalties(0.0005, 0.5) %>%
  add_gurobi_solver(gap = 0.1, time_limit = 7200, threads = 2, first_feasible = FALSE, node_file_start = 8)

s1 <- solve(p1)
```

**Comment by AlecNelson** [comment]
Hi @jeffreyhanson , thank you very much for the swift turn-around on implementing this parameter in the package! I have been testing my code with the node_file_start option and have found it remarkably more consistent to complete a run. The problem sets which formerly could not get past the issue of running out of memory are now completing within two hours at a 0.0000% gap, which seems like a great step forward in this analysis. Much appreciated!

**Comment by jeffreyhanson** [comment]
No worries - happy to help! Great to hear that it's all working now! Thanks for getting back to me and confirming that the `node_file_start` parameter works as expected. Please let me know if you run into any further issues or have any further ideas improving prioritizr.
