### ISSUE TITLE
Creating a conservation problem with sf object and data.frames

### ISSUE THREAD

**Issue by jaseeverett** [prioritizr/prioritizr#195]
Firstly, thanks so much @jeffreyhanson (and all contributors) for the wonderful package and documentation. It's an amazing achievement. 

However, I am having trouble using the new `sf` capability when creating the `problem` object. If I interpret the vignette correctly (https://prioritizr.net/reference/problem.html) I should be able to create a problem where `x` is an `sf` object, and `features` and `rij` are data frames.  
From the vignette the 3rd option under features suggests when `x` is an sf-object, I can use data frames for `features`: 
         "x = Spatial-class, or **x = sf::st_sf()**, or x = data.frame, or x = numeric vector, or x = matrix: **y = data.frame object** containing the names of the features.

I have created a small reprex below which uses `sim_pu_sf` from prioritizr datasets and then I create appropriate data frames for `rij` and `features`. However, I get the error: _Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘problem’ for signature ‘"sf", "data.frame"’_

Apologies if I am missing something obvious, but I can't get this to work, and I *think* the vignette suggests I should be able to, although I acknowledge there are no examples of sf + data frames so perhaps its not ....

I have updated all my packages, included prioritizr to the latest GitHub version as per the top of the reprex.

Any help would be appreciated.

```
library(sf)
library(prioritizr)
# packageVersion("sf")
# [1] ‘0.9.8’
# packageVersion("prioritizr")
# [1] ‘7.0.1.2’

data(sim_pu_sf) # load example PUs data from prioritizr
sim_pu_sf$id = 1:90 # assign PU id number. Not sure this is needed but it matches pu in rij (below)

features = data.frame(id = 1:3, name = c("A", "B", "C")) # Create dummy features as a data frame

# Create rij for each feature and then combine.
set.seed(23)
rij_1 <- data.frame(pu = ceiling(runif(50, 0, 89)), species = 1, amount = 100)
rij_2 <- data.frame(pu = ceiling(runif(20, 0, 89)), species = 2, amount = 100)
rij_3 <- data.frame(pu = ceiling(runif(20, 0, 89)), species = 3, amount = 100)
rij <- rbind(rij_1, rij_2, rij_3)
rm(rij_1, rij_2, rij_3)

# Check all classes are correct as per the documentation
class(sim_pu_sf) # should be sf
class(features) # should be data.frame
class(rij) # should be data.frame

p1 <- prioritizr::problem(x = sim_pu_sf, features = features, rij = rij, cost_column = "cost")
# results in 
# >Error in (function (classes, fdef, mtable)  : 
# >unable to find an inherited method for function ‘problem’ for signature ‘"sf", "data.frame"’
```

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for reaching out! I'm sorry, it looks like the `problem()` doesn't support this combination of input arguments -- so the documentation is incorrect. How important is this functionality? Would it be OK to specify the features using a character vector of column names (e.g. similar to `p6` example in https://prioritizr.net/reference/problem.html but with `sf` instead of `Spatial` data)?

**Comment by jaseeverett** [comment]
Thanks @jeffreyhanson. I'm glad I hadn't made a dumb mistake :-)

Somehow I missed the `p6` example and didn't realise it could also be used with `sf`. That is even easier! Having all the data (PUs, cost and features) in a single `sf` object is ideal for me. Thanks so much for the prompt reply. 

I will have a go at modifying the documentation for the incorrect `sf` example if you like?

**Comment by jeffreyhanson** [comment]
No worries - I'm sorry that I made that mistake with the documentation. 

Ok excellent! I'm glad that input format will work well.

Yeah, if you could please submit a PR that removes the incorrect bit of the documentation that would be really helpful? If you open a PR with an edited `R/problem.R` file, I can then update the other files as needed? How does that sound?
