### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#2]
Hi all,

I thought it might be nice to have a logo or picture for the repo organization.

Any thoughts?

**Comment by yeronimo** [comment]
Great idea. I am not good with logos, anyone else?

**Comment by jeffreyhanson** [comment]
I've created a [repo](https://github.com/prioritizr/prioritizr/logo) to store the logo in, so once we've sorted out the logo, we can have it in an easily accessible place.

**Comment by theodorosploumis** [comment]
I could give a hand here. I am not a professional logo designer but I like creating logos for open source projects. Will come back on Monday with some proposals if you like. Thanks!

**Comment by ricschuster** [comment]
@theodorosploumis That would be awesome! Thank you very much.

**Comment by jeffreyhanson** [comment]
yeah that would brilliant @theodorosploumis - thanks!

**Comment by theodorosploumis** [comment]
Here you are. I have studied a bit the repo and what Prioritzr does. 
Some logos are based on letter "P" and the up arrow. Some others are based on letters "Pr" combined. For the moment they are black & white but there could be a color after selection.
Personally I prefer No 7.

![proposal_1-7](https://cloud.githubusercontent.com/assets/1315321/24430595/f77f5238-141f-11e7-854a-87e803827691.png)

**Comment by jeffreyhanson** [comment]
I like the idea of combining the letters P and R. Yeah, I like 3 and 7. 

It's becoming popular for R package logos' to be inside a hexagon (eg. https://www.stickermule.com/user/1070448958/stickers). Would it possible to have the logo inside a hexagon?

Thanks again!

**Comment by ricschuster** [comment]
Thanks very much for these @theodorosploumis. 

My favorite is 3, but I also like 7.

**Comment by theodorosploumis** [comment]
Let me come back with some hexagon frames for 3 and 7.

**Comment by theodorosploumis** [comment]
Something like this maybe.

![proposals_v2](https://cloud.githubusercontent.com/assets/1315321/24462010/96fd133c-14ab-11e7-84f8-d3d458cf9b21.png)

**Comment by ricschuster** [comment]
@theodorosploumis those are all great, thank you very much!

I have a hard time picking a favorite as I B1-4 almost equally. 
Maybe B1 or B3 (I really like the p+r combos).

**Comment by theodorosploumis** [comment]
I think B4 is the most modern, related to R and software oriented. 
I am afraid though that it could be found somewhere else because it's concept is not hard to reproduce. In any case, I did not look to any other logos so let's assume we don't have issues with established logos.

**Comment by theodorosploumis** [comment]
**B3** on the other hand will have no issues and conflicts for sure.

**Comment by jeffreyhanson** [comment]
These looks awesome! I like B1 and B5 the most.

**Comment by ricschuster** [comment]
Lets go with B1 then. The colors are the most neutral I think. I always associate red with aggression.

**Comment by theodorosploumis** [comment]
Here you are! Enjoy your new logo! I have included an SVG also. The logo repo can be deleted now I believe.

[Logo_Prioritizr.zip](https://github.com/prioritizr/prioritizr/files/881825/Logo_Prioritizr.zip)

**Comment by ricschuster** [comment]
Thank you very much @theodorosploumis.

How would you like us to give credit for you for the logo (I'm new to this, so have no idea)?

**Comment by theodorosploumis** [comment]
I also know nothing about credits! But it's OK to not provide any info about the logo and all these. Consider this like any other PR... I will show the logo in my portfolio and that is fine for me!

**Comment by ricschuster** [comment]
Thanks very much again. 
At the very least we can put a link to your website up on the prioritizr website.
