### ISSUE TITLE
Problems with negative values

### ISSUE THREAD

**Issue by emmacj23** [prioritizr/prioritizr#201]
Hi. 

I am having some difficulties with trying to get my features data to pass pre-solve checks. I get the following error.

Warning in verify_that(all(raster::cellStats(raster::stack(as.list(features)),  :
  Elements 2, 3, 4 of raster::cellStats(raster::stack(as.list(features)), "min") >=  are not trueElements 2, 3, 4 of     0 are not true

and then the error
Error in glp_bounds(as.list(bounds), nc) :
  Upper bounds have to be greater than or equal to lower bounds
Timing stopped at: 2 0 2.07

My feature raster stack contains the following:

class      : RasterStack 
dimensions : 323, 521, 168283, 4  (nrow, ncol, ncell, nlayers)
resolution : 2000, 2000  (x, y)
extent     : 134000, 1176000, 12000, 658000  (xmin, xmax, ymin, ymax)
crs        : NA 
names      :        ag,        bg, emissions, inv_opp_cost_raster 
min values :       0.0, -204721.1, -155483.3,           -449398.5 
max values : 804060.06,  52375.66,      0.00,                0.00 

This is my planning unit data:

class      : RasterLayer 
dimensions : 323, 521, 168283  (nrow, ncol, ncell)
resolution : 2000, 2000  (x, y)
extent     : 134000, 1176000, 12000, 658000  (xmin, xmax, ymin, ymax)
crs        : NA 
source     : test_areas_raster4.tif 
names      : test_areas_raster4 
values     : 1, 376.014  (min, max)

Any advice greatly appreciated
Emma

**Comment by jeffreyhanson** [comment]
Thanks for reaching out!

I just wanted to check if negative cost values make sense for your conservation planning scenario before we get prioritizr working with the negative cost values. May I ask what the cost data are (e.g. are they human density values, land values in USD)? One issue with negative cost values is they will offset positive cost values -- meaning that a prioritization might select planning units with negative cost values even if they provide no benefits to biodiversity (e.g. it might select them even if they are not needed to meet representation targets). Although negative cost values can make sense in certain scenarios (e.g. when cost values indicate stakeholder preferences, and negative values indicate planning units that are preffered by stakeholders for conservation actions), these situations aren't very common. If you don't mind, could you please explain why cost values make sense for your conservation planning scenario? I'm sorry - this isn't the question you asked for help with - I'm just worried that if we get the negative cost values working then you might get results that don't make sense.

I'm sorry, I'm not exactly sure what this error means. Could you please post your R script, all the R output, and your session information (i.e. output from `sessionInfo()`)? Also, to get more details on the error, could you please try re-solving the problem with `verbose = TRUE`  when specifying the solver (e.g. using `add_gurobi_solver(verbose = TRUE)`)?

**Comment by emmacj23** [comment]
Hi,
Thanks for getting back to me so quickly. I'm new to optimisation techniques so it's likely I've done something silly in setting this up!

I am trying to identify areas for tree planting which maximise both biodiversity and carbon benefits. I was planning to carry out separate prioritisations, one for the carbon data and another for the biodiversity data, then take the outputs of these to indentify areas which are optimal for both. I can work with the biodiversity data ok, but I am having difficulties with setting up the problem for the carbon data.

-My planning unit raster, is the total area of farmland within in each grid cell which could be planted with trees. I have a target to plant 200000 ha in total.

-I want to maximise the carbon benefits achieved when farmland is reverted to woodland, whilst minimising the opportunity costs to farmers (so using the inverse of the opportunity costs data hence the negative values). 

-My features layer are (ag) predictions of the above ground carbon sequestered if trees were planted on the farmland in that cell. This has been monetised so is a pound value, (bg) predictions of the below ground carbon that would be released from the soil if trees were planted in that cell (also monetised), (emissions) the carbon that would no longer be emitted from farming if trees were planted in that cell (also monetised), (opp) The opportunity cost to the farmer if they gave up farming and planted trees in that cell. As I'm using the maximum utility function, but I want to minimise the opportunity costs, I've used the inverse of the opportunity cost, which is why I have so many negative values.

The error I received that I posted in my original message came about when I tried to set up the problem just for individual feature layers so I could find out which feature layer was preventing the problem from solving. I don't seem to be getting it for the stacked feature layers.

I work for an organisation, not a university so am using an open source solver, lpsymphony. I've used the following script:

library(prioritizr)
library(rgdal)
#if (!requireNamespace("BiocManager", quietly = TRUE))
#install.packages("BiocManager")
#BiocManager::install("lpsymphony")
library(lpsymphony)

> ag<-raster("./ag_carbon_raster.tif")
> bg<-raster("./bg_carbon_raster.tif")
> emissions<-raster("./emissions_raster.tif")
> opp<-raster("./inv_opp_cost_raster.tif")
> carbon_features<-stack(ag,bg,emissions,opp)
> carbon_features
class      : RasterStack 
dimensions : 323, 521, 168283, 4  (nrow, ncol, ncell, nlayers)
resolution : 2000, 2000  (x, y)
extent     : 134000, 1176000, 12000, 658000  (xmin, xmax, ymin, ymax)
crs        : NA 
names      : ag_carbon_raster, bg_carbon_raster,    emissions_raster, inv_opp_cost_raster 
min values :              0.0,        -204721.1,                  0.0,           -449398.5 
max values :        749817.11,         52375.66,             66978.28,                0.00 

> 
> #load planning units
> pu_raster<-raster("./pu_raster.tif")
> pu_raster
class      : RasterLayer 
dimensions : 323, 521, 168283  (nrow, ncol, ncell)
resolution : 2000, 2000  (x, y)
extent     : 134000, 1176000, 12000, 658000  (xmin, xmax, ymin, ymax)
crs        : NA 
source     : pu_raster.tif 
names      : pu_raster 
values     : 0, 376.0142  (min, max)

> p1<- problem(pu_raster, carbon_features) %>%
+     add_max_utility_objective(budget = 200000)%>%
+     add_binary_decisions()%>%
+     add_lpsymphony_solver(verbose=TRUE)
Warning in verify_that(all(raster::cellStats(raster::stack(as.list(features)),  :
  Elements 2, 4 of raster::cellStats(raster::stack(as.list(features)), "min") >=  are not trueElements 2, 4 of     0 are not true
> s1<-solve(p1)
Warning in presolve_check.OptimizationProblem(compile(x)) :
  features with (relatively) very high weights (> 1e+6)
Error in .local(a, b = b, ...) : 
  problem failed presolve checks, for more information see ?presolve_check

> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lpsymphony_1.20.0 prioritizr_7.0.1  proto_1.0.0       sf_0.9-8          raster_3.4-10    
[6] rgdal_1.5-23      sp_1.4-5         

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         magrittr_2.0.1     units_0.7-1        uuid_0.1-4         lattice_0.20-44   
 [6] rlang_0.4.11       fansi_0.5.0        tools_4.1.0        parallel_4.1.0     grid_4.1.0        
[11] utf8_1.2.1         KernSmooth_2.23-20 e1071_1.7-7        DBI_1.1.1          ellipsis_0.3.2    
[16] class_7.3-19       assertthat_0.2.1   tibble_3.1.2       lifecycle_1.0.0    crayon_1.4.1      
[21] Matrix_1.3-3       vctrs_0.3.8        codetools_0.2-18   slam_0.1-48        proxy_0.4-25      
[26] compiler_4.1.0     pillar_1.6.1       classInt_0.4-3     pkgconfig_2.0.3   
>

Thanks for any help

**Comment by jeffreyhanson** [comment]
Thanks so much for providing all this information - that's extremely helpful! 

Here's a couple of comments with regards to your data/analysis:

> I am trying to identify areas for tree planting which maximise both biodiversity and carbon benefits. I was planning to carry out separate prioritisations, one for the carbon data and another for the biodiversity data, then take the outputs of these to indentify areas which are optimal for both. I can work with the biodiversity data ok, but I am having difficulties with setting up the problem for the carbon data.

Yeah that sounds great! To identify optimal locations for tree planting to maximize both biodiversity and carbon benefits, I wonder if you could generate single prioritization instead of combining results of previous prioritizations (e.g. generating a prioritization using a combination of biodiversity and carbon features)? What do you think? This might be helpful because the places needed to maximize both might not neccesarily overlap with the places to maximize biodiversity and carbon individually. E.g. could you have a set of places with high biodiversity value (that are selected in the biodiversity prioritization), a second set of places with high carbon value (that are selected in the carbon priroitization), and a third set of places with medium-high biodiversity and carbon value that could be selected to maximize both biodiverity and carbon (but aren't selected in the biodiversity prioritization or carbon prioritization because they don't have "high" values)? 

> My features layer are (ag) predictions of the above ground carbon sequestered if trees were planted on the farmland in that cell. This has been monetised so is a pound value, (bg) predictions of the below ground carbon that would be released from the soil if trees were planted in that cell (also monetised), (emissions) the carbon that would no longer be emitted from farming if trees were planted in that cell (also monetised), (opp) The opportunity cost to the farmer if they gave up farming and planted trees in that cell. As I'm using the maximum utility function, but I want to minimise the opportunity costs, I've used the inverse of the opportunity cost, which is why I have so many negative values.

Ah ok - so if I understand correctly, the `ag`, `bg` and `emissions` are in exactly the same units, and your goal is to select planning units that maximize the total amount of carbon sequestered (whilst accounting for opportunity cost)? So, you don't care if the solution is able to maximize carbon sequestration based on only one of these variables? E.g. if the optimal solution involved planning trees to maximize carbon sequestration based on above ground (`ag`) alone (i.e. selected planning units had zero `bg` and `emissions` values) then that would be ok?

> My planning unit raster, is the total area of farmland within in each grid cell which could be planted with trees. I have a target to plant 200000 ha in total.

Ah, so the grid cell values in the planning unit raster (i.e. `raster("./pu_raster.tif")`) the area of farmland within the grid cell available for planting trees (in ha units). Is that right?

> ```
> carbon_features<-stack(ag,bg, emissions, opp)
> carbon_features
> class : RasterStack
> dimensions : 323, 521, 168283, 4 (nrow, ncol, ncell, nlayers)
> resolution : 2000, 2000 (x, y)
> extent : 134000, 1176000, 12000, 658000 (xmin, xmax, ymin, ymax)
> crs : NA
> names : ag_carbon_raster, bg_carbon_raster, inv_emissions_raster, inv_opp_cost_raster
> min values : 0.0, -204721.1, 0.0, -449398.5
> max values : 749817.11, 52375.66, 66978.28, 0.00
> ```

I'm sorry if I'm missing something obvious, but if the `bg_carbon_raster` contains values that are in monetary pound values - how can it have negative values (i.e. the smallest value in this dataset is `-204721.1`)?

> ```
> p1<- problem(pu_raster, carbon_features) %>%
> add_max_utility_objective(budget = 200000)%>%
> add_binary_decisions()%>%
> add_lpsymphony_solver(verbose=TRUE)
> ```

The `add_max_utility_objective` function basically involves computing a score for each planning unit (by summing togeather the values of the features inside the planning unit) and aims to maximize the total of these scores. Since all the carbon sequestration features (i.e. `ag`, `bg`, and `emissions`) are in the same units -- then I completely agree that this objective makes sense for your particular conservation planning scenario (assuming that you only care about total carbon sequestration, per my second point). But I wonder if there's a better way to accountfor the opportunity costs here? E.g. consider the following.

```
# let's say we had 1 planning unit with the following feature values
pu1 <- c(ag=5, bg=6, emissins=10, opp_cost = -6 )

# this planning unit would have a total score computed like this inside prioritizr based on max utility obj
sum(pu1)

# but typically, cost-effectiveness is calculatd like this: benefit / cost
# so if we applied this formula, then the total score should be computed like this:
sum(pu1[1:3]) / abs(pu1[4])
```

Does that make sense? If so, then maybe you could do some pre-processing to compute carbon sequestration cost-efficiency scores for the planning units, and use these scores as a feature when generating the prioritization:

```
# import packages
library(prioritizr)
library(rgdal)
library(lpsymphony)

# import data
pu_raster<-raster("./pu_raster.tif")
ag<-raster("./ag_carbon_raster.tif")
bg<-raster("./bg_carbon_raster.tif")
emissions<-raster("./emissions_raster.tif")
opp<-raster("./inv_opp_cost_raster.tif")

# calculate carbon sequestration cost-efficiency score for each planning unit
score <- sum(stack(ag,bg, emissions)) / abs(opp)

# build problem
p1<- 
  problem(pu_raster, score) %>%
  add_max_utility_objective(budget = 200000)%>%
  add_binary_decisions()%>%
  add_lpsymphony_solver(verbose=TRUE)

# generate solution
s1 <- solve(p1)
```

How does that sound? After generating the solution based on the ost-efficiency scores, you could then overlay the solution with the carbon sequestration data to calcualte the total amount of carbon sequestration:

```
cellStats(sum(stack(ag,bg, emissions)) * s1, "sum")
```

**Comment by emmacj23** [comment]
Hi, this is all really helpful advice.

Negative values result from me attempting to value carbon being released from soil through tree planting but you are right, the valuation of this is incorrect. Thanks for noticing this. I think that summing the carbon as you suggest, then applying the valuation would fix this. We just want to maximise the overall carbon sequestered, so a benefit cost ratio would work. I will try this. 

Yes you are correct, the units for the area of farmland in the planning unit raster is ha.

_I wonder if you could generate single prioritization instead of combining results of previous prioritizations (e.g. generating a prioritization using a combination of biodiversity and carbon features)?_

Yes, ideally I would like to undertake one prioritisation for the carbon and biodiversity data but I wasn't sure how to do this as my biodiversity data is the probability of occurrence for species and pollinators but unlike the carbon data is not monetised. Is this where having targets for the biodiversity would come in?

Thanks for the help
Emma

**Comment by jeffreyhanson** [comment]
Excellent - glad it was helpful!

Hmm, yeah, targets could potentially be one way to address this. Just to check, when generating the carbon prioritization and biodiverstity prioritization seperately, would these prioritizations involve different management actions? For example, if we were prioritizing areas for tree planting to enhance carbon sequestration, then we might plant trees that have the greatest sequestration abilities (e.g. Species X). Whereas, if we were prioritizing areas for tree planting to enhance biodiversity, then we might plant a set of native trees (e.g. Species A, B, C, D, and E) instead. Is that relevant here? If so, then maybe the "combined prioritization" could use different management zones to indicate which places should have (1) "carbon sequestran tree species planted", (2) "native trees species planted", and (3) "no trees planted"? For more details on management zones, please see this vignette (https://prioritizr.net/articles/zones.html).

**Comment by jeffreyhanson** [comment]
It's been a while now since there was any activity on this issue, so I'll assume that this issue has been resolved. Please feel free to re-open this issue, or open a new issue, if the issue hasn't been resolved or if you have any follow up questions?
