### ISSUE TITLE
cplexAPI package archival

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#214]
The cplexAPI R package has been archived on CRAN. Since prioritizr uses this package to interface with CPLEX, this will cause issues for users that rely on CPLEX. I'd reached out to the maintainer of the cplexAPI package, and I'll update this issue once I've heard back from them. In the meantime, the archived version of the cplexAPI package can be installed with:

```
if (!require(remotes)) install.packages("remotes")
remotes::install_github("cran/cplexAPI")
```

**Comment by ricschuster** [comment]
Thanks Jeff!

**Comment by jeffreyhanson** [comment]
Just to follow up, I emailed the developers of the cplexAPI R package and they've submitted an updated version to CRAN. So, hopefully it should be on CRAN soon.

**Comment by jeffreyhanson** [comment]
@ricschuster, if I remember correctly you mentioned that you were going to scope out Rcplex as a potential replacement, I just wanted to check if you'd had a chance to test it out?

**Comment by ricschuster** [comment]
I've tried to install Rcplex on a Windows machine, but haven't been successful so far. No issues on Linux, but will need to spend more time getting this to work on Windows.

**Comment by jeffreyhanson** [comment]
So, I think the plan here is to keep on cplexAPI as a Suggests if possible, and have users install from github.com/cran/cplexAPI - assuming that's ok with CRAN. How does that sound?

**Comment by ricschuster** [comment]
Sounds good. Any news from the slack channel in this approach?

**Comment by jeffreyhanson** [comment]
Nah, no one with specific experience to this question has answered (someone chimed in with a guess). I also posted on the publc ROpenSci forums (see https://discuss.ropensci.org/t/optional-suggests-dependency-that-has-been-archived-on-cran/3071), but no one has responded specifcally with a yes/no answer to the specific question. Could you post this question on the R-devel emailing list (https://stat.ethz.ch/mailman/listinfo/r-package-devel)? If so, feel free to use the forum post as a template.

**Comment by ricschuster** [comment]
Still haven't gotten on the R-devel list. What do you think about just going ahead without that?

**Comment by jeffreyhanson** [comment]
Yeah, I feel like the CRAN checks would have raised a NOTE or WARNING specifically about archived packages if that's an issue (but could be wrong). Could you take a look at the cran-commands.md in the PR? I added some text about justifying why cplexAPI is included even though its been archived - can you think of any ways to improve it?

**Comment by jeffreyhanson** [comment]
Also, I'm still waiting to hear back from the Matrix developers about 1.5-0 being the version that will be released on the 8th.
