### ISSUE TITLE
Minimum versions for dependencies

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#217]
I receieved an email that prioritizr was failing to install, and this was likely due to some outdated dependencies. Although prioritizr only specifies minimum versions for a few dependencies where we have noticed obvious breaks with backwards compatibility, I think it would be good to follow best practices by providing minimum versions for all dependencies and update them as needed moving forward. However, I don't know exactly what the "true" minimum version of each dependency is. So, I was thinking of specifying current CRAN and Bioconductor versions as the minimum versions for dependencies that lack minimum version numbers (with exception to R base packages, e.g. utils, methods, etc). Unfortunately, this means that many prioritizr users may need to update dependencies to use the next version of prioritizr. Does anyone have any strong opinions about this? @ricschuster and @mstrimas, what do you think?

**Comment by mstrimas** [comment]
My observation has been that most casual R users rarely if ever update packages unless forced to do so. So, I agree that it may end up being a pain for a bunch of users, but also it does feel like the safest option to ensure we specify versions for all dependencies, and maybe it will encourage users to update their packages as a side benefit. Anyway, this sounds like a good idea to me.

**Comment by ricschuster** [comment]
I agree with Matt. Using current CRAN and Bioconductor versions sounds good to me.

**Comment by jeffreyhanson** [comment]
Awesome - thanks! I'll push an update to the GitHub version today sometime.
