### ISSUE TITLE
rgdal, rgeos, and maptools retirement

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#218]
The rgdal, rgeos, and maptools R packages will be retired on Jan 1st 2024. So, we'll need to make sure that prioritizr fully transitions away from these packages before then.

**Comment by jeffreyhanson** [comment]
Posting this here so future me doesn't forget:

* maptools is included as an optional dependency for testing. This is because prioritizr has a speedy C++ port of `maptools::SpatialPolygonsToPolyset` and the tests are used to verify correctness of the port.
* rgeos is included as an optional dependency to help speed up the `boundary_matrix` functions. Specificaly, it provides an interface to the STR query tree in GEOS. It appears that the geos package also provides such an interface (see https://paleolimbot.github.io/geos/reference/geos_strtree.html), so this could be a good replacement.
* rgdal doesn't appear to be used by the package, so I don't think we need to do anything about it.

**Comment by jeffreyhanson** [comment]
@ricschuster, do you think it's trying to to get these updates into the next version, or waiting till later?

**Comment by ricschuster** [comment]
Good question. I was thinking early 2023 might be a good idea to start early, but I have no idea what's involved.

**Comment by jeffreyhanson** [comment]
Yeah, me too - but it's not looking as difficult as I originally thought. I might have a play with this today and see what I can do?

**Comment by ricschuster** [comment]
That sounds great to me, thanks Jeff.

**Comment by jeffreyhanson** [comment]
This turns out to be much easier than originally anticipated, due to the geos package, I'll try and push some updates to the PR by the end of today.

**Comment by ricschuster** [comment]
That's awesome!
