### ISSUE TITLE
eval_ferrier_importance documentation

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#220]
We currently have the following text in the documentation for `eval_ferrier_importance`:

"Please note that the mathematical formulation for computing these scores needs verification, and so this functionality should be considered experimental at this point in time."

Would it be alright to remove this note now that Brandon has vetted the formulation?

**Comment by jeffreyhanson** [comment]
Yeah that's correct - this text should be removed. I'll fix it this morning.
