### ISSUE TITLE
Problems with calibrating trade-offs and others

### ISSUE THREAD

**Issue by SuJie26** [prioritizr/prioritizr#221]
Hi

I wish you a happy new year! 

I am using a raster layer with a grid size of 30m * 30m as the cost input and a raster stack of seven species with the class of 1-9 to represent the suitability (unsuitable to perfectly suitable) of restoring them to build up the model for optimization planning for restoration. However, I am having some difficulties with the following issues.

Firstly, I followed each step of **calibrating trade-offs** to generate the penalty value using Cohon et al. (1979) method, but it comes to a very large result, like 1080 or so, which generate an irrational result (cannot even finish the estimation in a real model). I am wondering what is the reason behind this kind of "weird" results and how to address this issue. In addition, in the provided case, the boundary length values were manually re-scaled, I am curious if the re-scale will have impacts on the true value of panelty.

Secondly, instead of minimizing cost, I am also interested in maximizing benefit-cost ratio (BCR), which would be subject to different discount rates and timeframes. To achieve that, I have tried using objective with **add_min_set_objective** and negative value of BCR (BCR * -1), but it cannot work. Is there any way that I can achieve the objective?

Lastly, I also have difficulties in understanding the numbers in the results of **Evaluate target coverage**. Please see below results of my model. I assume that the number here is the total sum of class of suitability (total_amount) and chosen ones (absolute_held). I am wondering how can we know that if they chose the grid with high suitability. Also, I may not find the right way to do but how can I set up the overall restoration target of 500 ha with suitability larger than class 7?

feature met   total_amount absolute_target absolute_held absolute_shortfall relative_target relative_held
  <chr>   <lgl>        <dbl>           <dbl>         <dbl>              <dbl>           <dbl>         <dbl>
1 ac      TRUE        761502          26653.         28503                  0           0.035        0.0374
2 ai      TRUE        790778          27677.         29109                  0           0.035        0.0368
3 am      TRUE       1133678          39679.         39679                  0           0.035        0.0350
4 bg      TRUE       1085321          37986.         39542                  0           0.035        0.0364
5 ko      TRUE        985633          34497.         36494                  0           0.035        0.0370
6 rs      TRUE       1087365          38058.         38394                  0           0.035        0.0353
7 sa      TRUE       1066619          37332.         38050                  0           0.035        0.0357

It would be much appreciated for any suggestions.
Many thanks in advance.
Su

Below is the information of my input layers and the code for generating the problem.
> print(cost)
class      : RasterLayer 
dimensions : 1605, 2676, 4294980  (nrow, ncol, ncell)
resolution : 30, 30  (x, y)
extent     : 20581185, 20661465, 2685620, 2733770  (xmin, xmax, ymin, ymax)
crs        : +proj=tmerc +lat_0=0 +lon_0=117 +k=1 +x_0=20500000 +y_0=0 +datum=WGS84 +units=m +no_defs 
source     : cost_8%_20yr_new.tif 
names      : cost_8._20yr_new 
values     : 48.73102, 1395.984  (min, max)

> print(suitability)
class      : RasterStack 
dimensions : 1605, 2676, 4294980, 7  (nrow, ncol, ncell, nlayers)
resolution : 30, 30  (x, y)
extent     : 20581185, 20661465, 2685620, 2733770  (xmin, xmax, ymin, ymax)
crs        : +proj=tmerc +lat_0=0 +lon_0=117 +k=1 +x_0=20500000 +y_0=0 +datum=WGS84 +units=m +no_defs 
names      : ac, ai, am, bg, ko, rs, sa 
min values :  2,  2,  4,  3,  3,  4,  3 
max values :  8,  8,  9,  9,  9,  9,  9

> print(bcr)
class      : RasterLayer 
dimensions : 1605, 2676, 4294980  (nrow, ncol, ncell)
resolution : 30, 30  (x, y)
extent     : 20581185, 20661465, 2685620, 2733770  (xmin, xmax, ymin, ymax)
crs        : +proj=tmerc +lat_0=0 +lon_0=117 +k=1 +x_0=20500000 +y_0=0 +datum=WGS84 +units=m +no_defs 
source     : BCR_diversity_8%_20_neg.tif 
names      : BCR_diversity_8._20_neg

p1 <- problem(cost, suitability) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.035) %>%   
  add_boundary_penalties(penalty = 1) %>%. ## Here I am trying to identify the best value of penalty value.
  add_binary_decisions()%>%
  add_linear_penalties(-1,conn)%>%
  add_gurobi_solver()

**Comment by jeffreyhanson** [comment]
Hi,

Happy New Years! Thanks for reaching out. I'm currently on holiday with limited internet connectivity till the 24th Jan. @ricschuster, do you have any ideas? If not, I can follow up when I get back to work.

**Comment by jeffreyhanson** [comment]
Briefly, I would guess that it is the negative values that are causing problems for your first 2 points. If you use a negative cost value for a planning unit, then it will almost always get selected (e.g. unless you use locked out constraints, or other constraints). This is because the objective of the min set is to minimize the sum of cost values, and selecting lots of planning units with negative cost values is a good way to do this. So, i suggest rescaling costs so they are all > 0. 

That's correct. The values in those columns for the target shortfalls correspond to sums. It sounds like you want to calculate means, quantiles, or other instead? You can do this by multiplying the solution data with the feature data and then calculating a statistic. For example, with raster data:

```
cellStats(s1 * suitability, "mean")
```

To set a restoration target, I suggest using (1) a budget limited objective function (such as `add_min_shortfall_objective`, for total area must be <= 500 ha), or (2) adding constraints to a problem with the min set objective (I.e. `add_linear_constraints`, for total area must be >= 500 ha).

**Comment by SuJie26** [comment]
Hi 

Thank you very much for answering.

For my first question, I used the cost raster layer with values all larger than zero, ranging from 48.73 to 1395.98. And the problem is the weird large results of penalty value from Cohen's method. Can you help me to explain why and how I can do to prevent this issue? 

For the second point,  thank you for your explanation, that helps. Maybe to achieve maximize the Benefit-cost ratio, I need to firstly negative them and then rescale them so that the values >0 when I apply the min set objectives. Is it your suggestions?

For the third question, thank you for your explanations and suggestions. It is clear to me how to set up the constraints on area now. Thanks! However, I am still confused that from the result of _Evaluate target coverage_, how can we know that if they chose the planning unit with the suitability of restoring certain species larger than  7 (suitability > 7 means it is suitable for restoration). Or is it possible in some ways that I can set up this constraint? say in the solution, I would like the suitability class of at least two species can reach to 7?

Thanks a lot in advance.
I hope you have a nice holiday.

**Comment by ricschuster** [comment]
Hi,

If you are comfortable sharing your data and code, I'd be happy to have a look into your first question.

For your third question, you could setup a constraint or a penalty for that, but I wonder if you would really want to enforce this type of constraint? What you could do is convert your suitability layers to binary layers (0 = values smaller 7 and 1 = values of 7 and higher) and then sum across layers. You can convert that new layer to a binary layer again (0 = values smaller 2 and 2 = values of 2 or higher). You could use this layer for `add_linear_constrains` and exclude all cells with values of 0 from your solution.
This is a pretty extreme approach that would exclude a lot of cells, but one of the ways you could achieve what you describe.

Does that help?

**Comment by SuJie26** [comment]
Hi  @ricschuster,

Thank you very much for your reply.

Yes, I upload my code and data on the Google Drive. https://drive.google.com/file/d/1MrcFvE_yY4LcadWG-AoXH9TTVG193ofC/view?usp=sharing 
Thank you in advance, please feel free to check them.

For the suitability layers, thanks again for your suggestions. I incorporated your suggestion of binary layers into my model. 

Thanks in advance.

**Comment by SuJie26** [comment]
Hi @ricschuster 

Thank you very much for your reply.

Sure, I upload my data and codes in the following google drive https://drive.google.com/file/d/1fWga2vaNAJZ6PjWSq3iLvRV-WjMkAB15/view?usp=sharing
Please feel free to check them and thanks a lot in advance.

For the third question, I incorporated your suggestion of changing the suitability layers to binary layers. Thank you for your suggestions.

Thanks again in advance.

**Comment by SuJie26** [comment]
Hi

Thank you very much for your suggestions.

For the first issue, I think I have figured it out and now it goes well. 
For the third question, thank you very much for your suggestions. I incorporated in my models and it helps.

Again, many thanks for your excellent work of developing this package and your kindly support!
I wish all the best to you in 2022!

**Comment by ricschuster** [comment]
That's great to hear @SuJie26 and we are always happy to help.
Just let us know if you have any further questions.

**Comment by SuJie26** [comment]
Thank you.

Actually I have another question. Do we have constraints that allow me to specify the number of species in each planning unit, say for every planning unit, the number of suitable species should be > 2?

Many thanks in advance.

**Comment by ricschuster** [comment]
If this is a hard constraint, you could create a species richness layer and filter out all pu's that have a value of 2 or smaller. I personally would try to avoid this way of specifying the problem if possible, but it is an option.

**Comment by SuJie26** [comment]
Thank you for your suggestions. I will think about it.

**Comment by jeffreyhanson** [comment]
Thanks @ricschuster! Just in case this helps, another option could be to (1) create a species richness layer, (2) use it to create a binary layer indicating which planning units have < 2 species, and (3) use the binary layer to lock out planning units (via `add_locked_out_constraints()`).

That said, depending on study system and the conservation goals driving the prioritization, I wouldn't say it's unreasonable to have a solution that contains some planning units that only contain a single feature (e.g. a single species of the N species considered in the prioritization process). For example, if you're using a bunch of species to serve as surrogates for broader patterns of biodiversity (e.g. maybe you have 100 bird species, and 4 of these bird species are grassland species that you're using to account for grassland biodiversity), it might be reasonable to protect some planning units that only contain a single feature to help ensure coverage of other species not considered in the prioritization (e.g. maybe 1 of the 4 species is a high-alpine grassland specialist, and if you add such constraints maybe the prioritization will only represent marginal areas with high alpine grassland habitat).

**Comment by jeffreyhanson** [comment]
@SuJie26, did you have any further questions? If not, could you please close this issue?

**Comment by SuJie26** [comment]
Thank you @jeffreyhanson ! That is very helpful. Yes, I totally agree that in the case of conservation, single species should be considered. However, my research focus on forest restoration, identifying priority areas that are suitable for planting multiple species could promote the potential of mixed-species restoration and further to host biodiversity. 

Thank you both for your kindly helps. I will close this issue.
