### ISSUE TITLE
Changing targets/parameters after problem construction

### ISSUE THREAD

**Issue by rschueller** [prioritizr/prioritizr#227]
Hello! It is totally possible I am either a) deeply misunderstanding how the problem objects work or b) missing something obvious in the documentation but is there a way to change a parameter of a conservation problem after it has already been constructed (i.e. change the target type or values after already having piped the target into the problem)? The obvious answer here would have been to just make the feature/cost problem and add all of the parameters later but I did not do that and I'm looking for a way around re-running the whole thing (my deadlines weigh heavy). Alternatively, is there a way to extract the rij from a problem and use that to initialize a new problem to save some time? 

Thanks in advance, it has been very fun to tinker around and look at results already!

**Comment by jeffreyhanson** [comment]
Hi,

Yeah, in earlier versions of the prioritizr package we had envsioned ways to update the parameters/settings for problems after defining a problem. However, this ended up being too complex and added a lot of uneeded complexity to the code - so there isn't really an easy way to do this in the current version of the package. 

Yeah, you can extract the rij matrix from a problem using using `p1$data$rij[[1]]` (assuming you have 1 zone and the problem object is called `p1`). For example, here's some code to build a problem using the built-in dataset and extract the rij matrix:

```
# load packages
library(prioritizr)

# set seed for reproducibility
set.seed(500)

# load data
data(sim_pu_sf, sim_features) 

# load data
data(sim_pu_raster, sim_features)

# create problem using polygon (sf) planning unit data
p1 <- problem(sim_pu_sf, sim_features, "cost") %>%
      add_min_set_objective() %>%
      add_relative_targets(0.2) %>%
      add_binary_decisions() %>%
      add_default_solver(verbose = FALSE)

# print problem
print(p1)

# extract rij matrix
rij_mat <- p1$data$rij_matrix[[1]]

# preview matrix
head(m)
```

To use this matrix to create a new problem, I would suggest using the data.frame input format for creating a new `problem`. For example, see:

```
# extract cost
costs <- sim_pu_polygons$cost

# create a data.frame describing the features
features <- data.frame(id = seq_len(nlayers(sim_features)),
                       name = names(sim_features))

# create problem
p2 <- problem(costs, features, rij_matrix = rij_mat) %>%
      add_min_set_objective() %>%
      add_relative_targets(0.2) %>%
      add_binary_decisions() %>%
      add_default_solver(verbose = FALSE)

# print problem
print(p2)
```

Does that help? Please let me know if anything I've written isn't clear, or if you have any follow up questions?

**Comment by rschueller** [comment]
Yes, that helps tremendously. I assumed the matrix was in there somewhere, just wasn't quite sure how to get at it. Thank you so much!
