### ISSUE TITLE
Multiple planning units with seperate constraints

### ISSUE THREAD

**Issue by hjftan** [prioritizr/prioritizr#231]
Hi,

I want to minimize the cost of some planning units data whilst maximizing the values of some feature data. However, I have some other data which I also want to maximize.

I can do this using either the add_linear_penalties() or add_linear_constraints(), however, i think these constraints can only be applied across the entire solution.

I would like to allow the prioritization to select multiple planning units (i.e. the opposite of add_contiguity_constraints), and I would like to apply a single constraint to any proposed planning units independently, not across the entire solution.

This would be useful in a case where a conservation planning area is based upon model based simulations, however, we wish to ensure that a certain proportion of 'real data' is included in each planning unit.

Im sorry if this is already a feature. Many thanks for developing prioritzr.

H

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for reaching out! If I understand correctly, you want to ensure that the solution selects only planning units that contain particular values (i.e. planning units have at least a certain proportion of "real data"). Is that correct? If so, I would suggest creating a binary raster/column/object (depending on your planning unit data) that contains 0s and 1s indicating if each planning unit should _not_ be available for selection by the solution. For example, if you had a raster layer indicating the percentage of real data in each planning unit, you could apply a threshold of 70% to create a binary layer (e.g. using something like `binary_data <- round(percentage_data < 70))`. Next, you could use this binary layer with the locked out constraints to ensure that the solution will not select planning units with a percentage of real data below this thresholds (e.g. 70%).

Does that make sense? Let me know if you have any follow up questions? Sorry in advance if I take a while to respond, I'm really swamped at the moment.

**Comment by hjftan** [comment]
Hi,

Thanks for the help. No problems about any delay (also very busy at the moment).

For my purposes I don't think the locked in/out method would work because I want the constraint/threshold to be applied to a raster wide value not a by-cell value, if that makes sense? i.e. its fine if many cells are selected which have a low % value of real data, so long as the sum of all selected planning units corresponds to a threshold which I can define.

However, I have been able to get close to what I want by including the "real data" raster as an additional feature to prioritize. 

Many thanks,

H
