### ISSUE TITLE
Using prioritizr for 3D marine planification

### ISSUE THREAD

**Issue by lmathon** [prioritizr/prioritizr#236]
Hi,

I would like to use prioritizr to find the best plaling solution both spatially and vertically (along depth), but I am not sure how to do it and if it is even possible.

I have several features (fish abundances, biomass, richness..) across a large spatial extent (something like 80,000 cells) and 3 depth layers.

Is there a way to build a problem with planning units as a data.frame (maybe with a unique id for each cell and all depth) and the features as a data.frame also, with unique feature id, and their values for each pu in the rij ?

Would prioritizr  know which pu shares boundaries with other pu ? And will it be able to solve the problem by taking into acount the 3 depth layers ?
Maybe there is a better way to build my problem ?

Thanks for your help,

Laetitia

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for reaching out! 

Yeah, I haven't tried doing any 3D planning with prioritizr, but it should be possible using the data.frame input format. The main trick will be creating the boundary data. Although you can use the `boundary_matrix()` function to create the 2D version of the boundary data, you'll also need to make sure that the boundary data accounts for the (i) spatial vertical relationships among planning units, and (ii) adding in extra boundary lengths for the top edge of planning units on the shawllowest depth and the floor of the planning units on deepest depth.

I had a go at trying to code up an example of how this could be done for the simulated datasets in prioritzr. I've copied it in below - could you please take a look and let me know what you think? Please note that I didn't have a lot of time to focus on this - meaning there's a high chance that it contains errors/budgets/mistakes - so please step through it and double check that I haven't made any mistakes or invalid assumptions :)

```
# load packages
library(prioritizr)
library(raster)
library(plyr)
library(dplyr)

# load data
data(sim_pu_sf)
data(sim_features_zones)

# here sim_pu_sf is our planning unit in 2d format
print(sim_pu_sf)

# create a list with the feature data at different depths
# here, we will just use the built-in data for teaching purposes
sim_features_depths <- as.list(sim_features_zones)
names(sim_features_depths) <-
  paste0("depth_", seq_along(sim_features_depths))
print(sim_features_depths)

# create a tibble with the planning unit data
pu_data <- tibble(
  ## id column with unique ids for each 3D planning unit
  id = seq_len(nrow(sim_pu_sf) * length(sim_features_depths)),
  ## id column indicating which the 2d identifier for the planning unit
  id_2d = rep(seq_len(nrow(sim_pu_sf)), length(sim_features_depths)),
  ## depth column indicating which depth the 3d planning unit is at
  id_depth = rep(names(sim_features_depths), each = nrow(sim_pu_sf)),
  ## randomly simulate cost data
  cost = runif(length(id))
)

# print table
print(pu_data)

# extract information on the amount of each feature within each planning unit
## here we assume sim_features_depths is a list of raster stack objects
## e.g., sim_features_depths[[1]][[1]] has data for 1st feature in 1st depth
## e.g., sim_features_depths[[2]][[1]] has data for 1st feature in 2nd depth
## e.g., sim_features_depths[[1]][[2]] has data for 2nd feature in 1st depth
## e.g., sim_features_depths[[2]][[2]] has data for 2nd feature in 2nd depth
rij_data <- lapply(seq_along(sim_features_depths), function(i) {
  ## overlay the 2d planning units with the feature data at i'th depth
  rij_matrix(sim_pu_sf, sim_features_depths[[i]])
}) %>% do.call(what = cbind)

# now let's create a table with the feature data
feat_data <- tibble(
  id = seq_len(nlayers(sim_features_depths[[1]])),
  name = names(sim_features_depths[[1]])
)

# now let's create the boundary matrix
## initialize matrix for 2d data
b_matrix_2d <- boundary_matrix(sim_pu_sf)
b_data_2d <- as(b_matrix_2d, "dgTMatrix")
b_data_2d <- tibble(
  id1 = b_data_2d@i + 1,
  id2 = b_data_2d@j + 1,
  boundary = b_data_2d@x
)
### compute edge length
edge_length <- raster::modal(b_data_2d$boundary)

## create matrix for 3d planning unit data
### initialize with horizontal connections between 3d planning units
### that are located at the same depths
bound_data <-
  pu_data %>%
  plyr::ddply("id_depth", function(x) {
    id1_data <- left_join(b_data_2d, x, by = c("id1" = "id_2d"))
    id2_data <- left_join(b_data_2d, x, by = c("id2" = "id_2d"))
    tibble(
      id1 = id1_data$id,
      id2 = id2_data$id,
      boundary = id1_data$boundary
    )
  }) %>%
  dplyr::select(-id_depth) %>%
  as_tibble()
### now we add in the vertical connections between 3d planning units
### that are located at different depths (same water column)
bound_data <- bind_rows(
  bound_data,
  plyr::ddply(pu_data, "id_2d", function(x) {
    tibble(
      id1 = x$id[-nrow(x)],
      id2 = dplyr::lead(x$id)[-nrow(x)],
      boundary = edge_length
    )
  }) %>%
  dplyr::select(-id_2d) %>%
  as_tibble()
)
### add in vertical lengths for planning units on top and bottom depth
### note these connections are id1 == id2, they are adding the boundary
### lengths for the roof and floor of the planning units
bound_data <- bind_rows(
  bound_data,
  pu_data %>%
  dplyr::filter(
    id_depth %in% c(
      dplyr::first(names(sim_features_depths)),
      dplyr::last(names(sim_features_depths))
    )
  ) %>%
  dplyr::transmute(
    id1 = id,
    id2 = id,
    boundary = edge_length
  )
)
### aggregate data so we don't have any duplicate rows with exactly
### the same id1 and id2 values
bound_data <-
  bound_data %>%
  group_by(id1, id2) %>%
  summarize(boundary = sum(boundary)) %>%
  ungroup()

# now let's create the problem
p <-
  problem(pu_data$cost, features = feat_data, rij_matrix = rij_data) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions()
print(p)

# generate a solution
s <- solve(p)

# prepare data for plotting
## add solution to planning unit data
pu_data$solution_1 <- c(s)

## lets create a list (one element per depth) with a copy of the solution
## values that correspond to the planning units at each depth
sol_data <-
  lapply(seq_along(sim_features_depths), function(i) {
    x <- sim_pu_sf
    x$id_2d <- seq_len(nrow(x))
    x$id_depth <- names(sim_features_depths)[[i]]
    x <- left_join(
      x,
      pu_data %>% dplyr::select(id_2d, id_depth, solution_1),
      by = c("id_2d", "id_depth")
    )
    x$solution_1
  }) %>%
  setNames(paste0("solution_1_", names(sim_features_depths)))

## let's now create a version of the 2d planning unit data and insert
## a column for each depth, indicating (using 0s and 1s) if the
## planning unit was prioritized at a specific depth
sol_2d_data <-
  sim_pu_sf %>%
  bind_cols(do.call(tibble, sol_data))

# now let's visualize the solution
plot(
  sol_2d_data[, paste0("solution_1_", names(sim_features_depths))]
)
```

**Comment by lmathon** [comment]
Wow that seems like a wonderful solution to my problem !!
The code works just fine on your data, I will try it on mine and see how it goes.

Thank you very much for taking the time to help me with this!

**Comment by lmathon** [comment]
Ok so, I encountered several issues.


When I try to initialize the boundary matrix with `b_matrix_2d <- boundary_matrix(pu_sf)`  I get this error :
`Error in boundary_matrix.sf(pu_sf) : 
  data represented by points have no boundaries - see ?constraints alternative constraints`

which I understand, because the geometry in my pu_sf object are points, but I don't know how to create a geometry column like the one in your example (and I am not sure to understand what the values stand for).

The second issue is when I try solving the problem, I get the error :

`Warning in presolve_check.OptimizationProblem(compile(x)) :
  planning units with very high (> 1e+6) or very low (< 1e-6) non-zero cost values note this may be a false positive
Error in .local(a, b = b, ...) : 
  problem failed presolve checks, for more information see ?presolve_check`

This is strange because the costs in my pu_data object are either 1 or NA. I set 1 to all the planning units I want to consider (no differences between them) and I set NA to all the planning units that I don't want to consider (for example where the seafloor is  less than 400m deep, there is no planning units to consider in depth 3, so NA). 
Is this correct ? I also tried by using the locked_out constraint but it did not work either. 



Here is the features_depth object :

`$depth_1
class      : RasterBrick 
dimensions : 824, 1454, 1198096, 30  (nrow, ncol, ncell, nlayers)
resolution : 0.0096, 0.0096  (x, y)
extent     : 158.0928, 172.0512, -25.728, -17.8176  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : memory
names      : Aphareusrutilans, Carcharhinusalbimarginatus, Pristipomoidesflavipinnis, Pristipomoidesfilamentosus, Seriolarivoliana, ... 
min values :     0.0001565220,               0.0032815862,              0.0004847605,               0.0004948988,     0.0000010000,         0.0007875107, ... 
max values :        0.9168629,                  0.9732093,                 0.8763724,                  0.8917390,        0.9506976,            0.7330459,         0.8111991, ... 


$depth_2
class      : RasterBrick 
dimensions : 824, 1454, 1198096, 30  (nrow, ncol, ncell, nlayers)
resolution : 0.0096, 0.0096  (x, y)
extent     : 158.0928, 172.0512, -25.728, -17.8176  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : memory
names      : Aphareusrutilans, Carcharhinusalbimarginatus, Pristipomoidesflavipinnis, Pristipomoidesfilamentosus, Seriolarivoliana, ... 
min values :     1.000000e-06,               7.620336e-04,              2.090033e-03,               5.006251e-04,     1.000000e-06,         1.000000e-06, ... 
max values :        0.9785836,                  0.9479759,                 0.9279555,                  0.9870675,        0.9974087,            0.8812798,         0.8062266, ... 


$depth_3
class      : RasterBrick 
dimensions : 824, 1454, 1198096, 30  (nrow, ncol, ncell, nlayers)
resolution : 0.0096, 0.0096  (x, y)
extent     : 158.0928, 172.0512, -25.728, -17.8176  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : memory
names      : Aphareusrutilans, Carcharhinusalbimarginatus, Pristipomoidesflavipinnis, Pristipomoidesfilamentosus, Seriolarivoliana, ... 
min values :     1.000000e-06,               3.901406e-05,              1.878786e-03,               1.000000e-06,     1.000000e-06,         1.000000e-06, ... 
max values :        0.9689347,                  0.9132056,                 0.9302559,                  0.8906146,        0.8306546,            0.8630611,         0.9039919, ... 
`

and here are the first lines of my pu_data object :

`id id_2d id_depth cost
1     1  depth_1    1
2     2  depth_1    1
3     3  depth_1    1
4     4  depth_1    1
5     5  depth_1    1
6     6  depth_1    1`

**Comment by jeffreyhanson** [comment]
Yeah, that's exactly right, the error you're seeing with `b_matrix_2d <- boundary_matrix(pu_sf)` is because your planning unit data are represented as points. The example dataset (`sim_pu_sf`) has planning unit data represented as polygons (i.e. a spatial grid over the study area). Although it's possible to generate prioritizatins using point-based planning units, this isn't very common - so I just want to check what would make the most sense for your study? E.g., planning units are often represented using spatial grids (e.g. using polygon-type spatial data or raster-type spatial data) so that each planning unit represents an area (e.g.  100 m x 100 m grid cell, 1 x 1 km grid cell, 5 x 5 km grid cell) that is availale for protected area establishment. If you want to generate a spatial grid for your planning units, one approach would be to use `sf:::st_make_grid()`, or you could use the raster data for your features to create a spatial grid (e.g., using something like this):

```
pu_raster <-  features_depth[[1]][[1]]                   # extract data
pu_raster[raster::Which(!is.na(pu_raster))] <- 1  # set cost values as 1
```

Also, I noticed that the feature data are in the WGS1984 (aka EPSG:4326) coordinate system. I would strongly recommend reprojecting the data to an equal-area coordinate system, or a projected coordinate system (e.g. based on a particular UTM zone). This is because, under the WGS1974 coordinate system, a spatial grid of 0.0096 x 0.0096 decimal degrees and located at the equator will actually be a larger than a spatial grid of  0.0096 x 0.0096 decimal degrees located nearer to the poles. In other words, even the each grid cell in the raster bricks are the same size according to WGS1984 resolution, they will not actually be the same size in reality.

What do you think? I'm hoping that updating the planning unit data might also resolve those optimization warnings - but let me know if they persist after updating the planning unit data.

**Comment by lmathon** [comment]
Hi, thanks for your help. 
The firsts steps of the bound_data building are working now with the pu_sf with polygon geometry, however, the last bit :

```
bound_data <-
  bound_data %>%
  group_by(id1, id2) %>%
  summarize(boundary = sum(boundary)) %>%
  ungroup()
```
returns only a single value, and I can't understand why. Up to that last part everything works well.

Also I don't see where the bound_data object is included in the problem ?

And I still get the Error message when running `solve(p)` :

```
Warning in presolve_check.OptimizationProblem(compile(x)) :
  planning units with very high (> 1e+6) or very low (< 1e-6) non-zero cost values note this may be a false positive
Error in .local(a, b = b, ...) : 
  problem failed presolve checks, for more information see ?presolve_check
```


I also had a question about the rij_data. Since all my planning units don't have features values for all depth layers, there are NAs in the rasterStack in the features_depths object. Is it taken into account when the rij_data object is built ?

**Comment by jeffreyhanson** [comment]
> The firsts steps of the bound_data building are working now with the pu_sf with polygon geometry, however, the last bit :

Hmm, that's strange, what does `bound_data` look like before you do this step?

```
bound_data <-
  bound_data %>%
  group_by(id1, id2) %>%
  summarize(boundary = sum(boundary)) %>%
  ungroup()
```

It might be worth updating the version of dplyr installed on your computer. Maybe there's an old version installed causing problems?

> Also I don't see where the bound_data object is included in the problem ?

Ah, that's a mistake, the code should use `add_boundary_penalties()` to specify boundary penalties using the `bound_data`.

`And I still get the Error message when running solve(p) :`

Hmm, that's strange too. What does `range(pu_data$cost)` output? Also, I'm assuming you're using the most recent version of prioritizr and the min set formulation. Is that correct? Would you mind posting your problem formulation here?

> I also had a question about the rij_data. Since all my planning units don't have features values for all depth layers, there are NAs in the rasterStack in the features_depths object. Is it taken into account when the rij_data object is built ?

The NA values should be treated as zeros when constructing the rij_matrix. If you want to be 100% confident though, you could manually replace the NAs with zeros in the depth data layers.

**Comment by lmathon** [comment]
Hi,

So, updating dplyr did the trick for the bound_data object.

For the rij_matrix, it's ok as well, I get 0 where there are NAs in my depth layers.

I still get this error message, wit an additional one about penalty boundary length :

```
Warning in presolve_check.OptimizationProblem(compile(x)) :
  planning units with very high (> 1e+6) or very low (< 1e-6) non-zero cost values note this may be a false positive
Warning in presolve_check.OptimizationProblem(compile(x)) :
  penalty multiplied boundary lengths are very high
Error in .local(a, b = b, ...) : 
  problem failed presolve checks, for more information see ?presolve_check
```

The costs in my pu_data object are either 1 or NA (1 if there are corresponding features for this cell and depth, and NA if there aren't). Should I replace the NA by 0 ? or remove these planning units ?

This is what my bound_data object looks like :

```
> summary(bound_data)
      id1              id2            boundary       
 Min.   :     1   Min.   :     1   Min.   :0.009600  
 1st Qu.: 54340   1st Qu.: 65608   1st Qu.:0.009600  
 Median :113241   Median :129623   Median :0.009600  
 Mean   :116304   Mean   :126680   Mean   :0.009847  
 3rd Qu.:177575   3rd Qu.:188683   3rd Qu.:0.009600  
 Max.   :242787   Max.   :242787   Max.   :0.048000
```

**Comment by jeffreyhanson** [comment]
Hi,

>So, updating dplyr did the trick for the bound_data object.

Awesome! 

> For the rij_matrix, it's ok as well, I get 0 where there are NAs in my depth layers.

Ok - good to hear.

> I still get this error message, with an additional one about penalty boundary length :

Hmm, that's odd. Could you please try updating prioritizr to the latest version (e.g. on CRAN), and could you please post the `summary(pu_data)`? This error really shouldn't be happening with only 1s and NA values. If you still see this after updating prioritizr, could you please send me the pu data, feature data, and boundary data over emal so I can work out what's happening ?

> This is what my bound_data object looks like :

Looks good! The boundary values seem a bit small though. What units are they in? E.g., after calculating the boundary data in meters, did you do some scaling?

> My problem is like that 

Yeah that looks correct.

**Comment by lmathon** [comment]
I think I already had the latest version, but I updated it anyway, but still get the same message.

Here is the summary of pu_data :

```
> summary(pu_data)
       id             id_2d         id_depth              cost      
 Min.   :     1   Min.   :    1   Length:242787      Min.   :1      
 1st Qu.: 60698   1st Qu.:20233   Class :character   1st Qu.:1      
 Median :121394   Median :40465   Mode  :character   Median :1      
 Mean   :121394   Mean   :40465                      Mean   :1      
 3rd Qu.:182091   3rd Qu.:60697                      3rd Qu.:1      
 Max.   :242787   Max.   :80929                      Max.   :1      
                                                     NA's   :40158 
```
Should the id and id_2d be character instead of numeric, maybe ?


The boundary length are in decimal degrees, the same as the resolution of my raster. So each 2D planning units is 0.0096*0.0096°, so roughly 1*1km. Should I convert the boundary length from degrees to km or meters ?

I send you my data by email, thank you very much for your help !

**Comment by lmathon** [comment]
Hi,

Were you, by any chance, able to identify the source of the problem with my data ?

Thank you !

**Comment by jeffreyhanson** [comment]
Hi,

I'm sorry, I'm swamped at the moment. I got a paper back from review and need to turn that around ASAP (it's due back in 3 weeks) and I also need to prepare for a talk comming up next week. I'll try and get to this on Thursday or Friday next week.

Regarding your previous message, I would strongly suggest using a projected coordinate system (e.g. UTM zone). E.g., you could reproject the feature data to a projected coordinate system, and then re-create the planning unit data based on the feature data layers and setting costs to 1.

**Comment by jeffreyhanson** [comment]
Also, this paper (https://www.nature.com/articles/s41558-022-01323-7) came out a few days ago on doing 3D planning in marine systems, maybe the supporting information might have some R code that be could adapted?

**Comment by ricschuster** [comment]
I just came across this paper "Towards climate-smart, three-dimensional protected areas for biodiversity conservation in the high seas" (https://www.nature.com/articles/s41558-022-01323-7) and thought I'd share this here as it could be relevant to you @lmathon

**Comment by jeffreyhanson** [comment]
@lmathon, sorry it's taken me so long to get to this!

It turns there's a bug in the `problem()` function that specifically occurs when  a problem is constructed using arguments to (i) `x` that are `numeric` or `matrix` format, (ii) `x` that contain missing (`NA`) values, and (iii) `rij_matrix` that are in `dgCMatrix` format. This bug only occurred when all three of these specific conditions were met. When it occurred, the bug caused planning units with `NA` cost values to receive very high cost values (e.g. 1e+300). This bug meant that when attempting to solve the problem, the presolve checks (per `presolve_check()`) would throw an error complaining about very high cost values.

I'll push an update to the Github repository in a bit that fixes this issue. So, you can address this issue by (1) updating your version of prioritizr to the GitHub version (see README for installation instructions), or (2) converting the feature data from `dgCMatrix` format to `matrix` format (using `as.matrix(rij_data)`). Although the second option is a bit easier, you might find that this could increase memory consumption.

In this case this helps, here's some R code to build and solve the problem using the `matrix` format with the CRAN version of prioritizr. Although I use `penalty = 1`, you might need to change this to something much smaller (e.g. `penalty = 1e-4`) since your boundary data (per `boundary` column) are now in meters (and not degrees).

```
# Load packages
library(prioritizr)
library(raster)
library(tidyverse)

# Import data
load("feat_data.rdata")
load("pu_data.rdata")
load("rij_data.rdata")
load("bound_data.rdata")

# convert to matrix format
rij_mdata <- as.matrix(rij_data)

# build problem
p <-
  problem(pu_data$cost, features = feat_data, rij_matrix = rij_mdata) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_boundary_penalties(penalty = 0.1, data = bound_data) %>%
  add_binary_decisions()

# solve problem
s <- solve(p)
```

**Comment by jeffreyhanson** [comment]
Also, to answer your question about the warning message concerning `penalty multiplied boundary lengths are very high`, this is saying that the argument to `penalty` in `add_boundary_penalties()` is really high relative to (1) the cost values and (2) the boundary length values (i.e. values in boundary column of boundary data). So, I would suggesting a smaller penalty values (e.g. 1e-3, 1e-5, 1e-6) because given the relative scaling of these different values, the current penalty value is likely to produce a solution with one giant reserve. For more info on choosing a good boundary penalty value, I suggest reading the calibrating trade-offs tutorial (see https://prioritizr.net/articles/calibrating_trade-offs_tutorial.html).

Does that help? Let me know if you have any further questions?

**Comment by lmathon** [comment]
Hi Jeffrey !

Thank you very much for your help, everything is working perfectly fine now !
I am currently trying several penalty values and later will use the topsis score to choose the best solution.

I'll let you know if I have other questions later, and I will for sure acknowledge your precious help in my manuscript !

Thank you again !

Cheers

**Comment by jeffreyhanson** [comment]
No worries - great to hear everything's working now! Sorry again for my delay in responding to your questions. Sounds good! Since we've got the code working now and you don't have any more questions at the moment, I'll close this issue now. Please feel free to re-open it, or open a new issue, if you run into any more issues or have any further questions.
