### ISSUE TITLE
Cost re-scaling

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#242]
Hi Jeff and all,

Sorry, yet another question, quite possibly a stupid one. 

Context: cost data is fisheries data, so represents opportunity cost, or potential lost revenue 

Question: Why does re-scaling cost values radically alter the solutions and also associated costs when boundary penalties are included?

The reprex below illustrates my question using the Salt Spring Island data and comparing a solution with and without the cost data re-scaled on a 0.01 to 100 scale (bearing in mind your comment that this is a suitable scale in #215 ). I have included a baseline solution just using the unaltered salt springs data and a 30% target (baseline) and a solution with the cost values rescaled (rescaled), and both those options with the same boundary penalty added (bp = 0.001). The baseline and rescaled are similar, though not the same, but the baseline with bp and rescaled with bp are pretty different: the rescaled with bp is way more clumped. I presume this is something to do with their being a smaller range of cost values, perhaps related to the fact that the cost values are very long tailed (see `quantile()` results), and the rescaling makes some of those lower values practically indistinguishable to the algorithm?

Another noticeable difference between the baseline and rescaled solutions is the costs: rescaled solutions are considerably more costly. Again, don't quite understand why.

Any thoughts would be very welcome, thank you!

``` r
library(prioritizr)
#> Loading required package: raster
#> Loading required package: sp
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1; sf_use_s2() is TRUE
#> Loading required package: proto
library(prioritizrdata)

data(salt_pu)
data(salt_features)

set.seed(500)

#generic function for rescaling a raster between new_min and new_max
func_rescale <- function(x, new_min, new_max){
  rescaled_value <- ((x - cellStats(x, min, na.rm=TRUE)) * (new_max - new_min) / (cellStats(x, max, na.rm=TRUE) - cellStats(x, min, na.rm=TRUE))) + new_min
}

#baseline problem with 30% targets 
p <- problem(salt_pu, salt_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.30) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0.1, verbose = TRUE)

sp <- solve(p)
#> Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
#> Thread count: 6 physical cores, 12 logical processors, using up to 1 threads
#> Optimize a model with 5 rows, 19794 columns and 98970 nonzeros
#> Model fingerprint: 0xf32c2568
#> Variable types: 0 continuous, 19794 integer (19794 binary)
#> Coefficient statistics:
#>   Matrix range     [1e-01, 9e-01]
#>   Objective range  [3e-02, 1e+04]
#>   Bounds range     [1e+00, 1e+00]
#>   RHS range        [2e+03, 5e+03]
#> Found heuristic solution: objective 11915.032165
#> Presolve removed 0 rows and 331 columns
#> Presolve time: 0.10s
#> Presolved: 5 rows, 19463 columns, 97315 nonzeros
#> Variable types: 0 continuous, 19463 integer (19132 binary)
#> Found heuristic solution: objective 10574.626915
#> Root relaxation presolved: 5 rows, 19463 columns, 97315 nonzeros
#> 
#> 
#> Root relaxation: objective 1.163432e+03, 3 iterations, 0.02 seconds (0.04 work units)
#> 
#>     Nodes    |    Current Node    |     Objective Bounds      |     Work
#>  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
#> 
#>      0     0 1163.43166    0    1 10574.6269 1163.43166  89.0%     -    0s
#> H    0     0                    1169.3115250 1163.43166  0.50%     -    0s
#> 
#> Explored 1 nodes (3 simplex iterations) in 0.30 seconds (0.37 work units)
#> Thread count was 1 (of 12 available processors)
#> 
#> Solution count 3: 1169.31 10574.6 11915 
#> 
#> Optimal solution found (tolerance 1.00e-01)
#> Best objective 1.169311525006e+03, best bound 1.163431660760e+03, gap 0.5028%

#####################################################
#second problem, same as above but boundary penalties added
p2 <- problem(salt_pu, salt_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.30) %>%
  add_binary_decisions() %>%
  add_boundary_penalties(0.001) %>% 
  add_gurobi_solver(gap = 0.1, verbose = TRUE)

sp2 <- solve(p2)
#> Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
#> Thread count: 6 physical cores, 12 logical processors, using up to 1 threads
#> Optimize a model with 77397 rows, 58490 columns and 253754 nonzeros
#> Model fingerprint: 0x1706a6ba
#> Variable types: 0 continuous, 58490 integer (58490 binary)
#> Coefficient statistics:
#>   Matrix range     [1e-01, 1e+00]
#>   Objective range  [2e-01, 1e+04]
#>   Bounds range     [1e+00, 1e+00]
#>   RHS range        [2e+03, 5e+03]
#> Found heuristic solution: objective 308878.32481
#> Found heuristic solution: objective 11952.232165
#> Presolve removed 56 rows and 28 columns
#> Presolve time: 0.47s
#> Presolved: 77341 rows, 58462 columns, 253642 nonzeros
#> Variable types: 0 continuous, 58462 integer (58462 binary)
#> Found heuristic solution: objective 7881.0017952
#> Root relaxation presolved: 77341 rows, 58462 columns, 253642 nonzeros
#> 
#> 
#> Root relaxation: objective 1.315906e+03, 6635 iterations, 1.08 seconds (2.17 work units)
#> 
#>     Nodes    |    Current Node    |     Objective Bounds      |     Work
#>  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
#> 
#>      0     0 1315.90613    0  192 7881.00180 1315.90613  83.3%     -    1s
#> H    0     0                    1321.8753950 1315.90613  0.45%     -    1s
#> 
#> Explored 1 nodes (6635 simplex iterations) in 2.00 seconds (3.13 work units)
#> Thread count was 1 (of 12 available processors)
#> 
#> Solution count 4: 1321.88 7881 11952.2 308878 
#> 
#> Optimal solution found (tolerance 1.00e-01)
#> Best objective 1.321875395005e+03, best bound 1.315906134962e+03, gap 0.4516%
##############################################################
#third problem, same as baseline problem but cost rescaled

#rescale cost layer between 0.01 and 100, setting min above zero to avoid feature over-representation
salt_pu_rescaled <- salt_pu %>% func_rescale(new_min = 0.01, new_max = 100)

p3 <- problem(salt_pu_rescaled, salt_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.30) %>%
  add_binary_decisions() %>%
  #add_boundary_penalties(0.001) %>% 
  add_gurobi_solver(gap = 0.1, verbose = TRUE)

sp3 <- solve(p3)
#> Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
#> Thread count: 6 physical cores, 12 logical processors, using up to 1 threads
#> Optimize a model with 5 rows, 19794 columns and 98970 nonzeros
#> Model fingerprint: 0xafc2b59e
#> Variable types: 0 continuous, 19794 integer (19794 binary)
#> Coefficient statistics:
#>   Matrix range     [1e-01, 9e-01]
#>   Objective range  [1e-02, 1e+02]
#>   Bounds range     [1e+00, 1e+00]
#>   RHS range        [2e+03, 5e+03]
#> Found heuristic solution: objective 181.1352865
#> Presolve removed 0 rows and 413 columns
#> Presolve time: 0.11s
#> Presolved: 5 rows, 19381 columns, 96905 nonzeros
#> Variable types: 0 continuous, 19381 integer (18968 binary)
#> Found heuristic solution: objective 164.2080326
#> Root relaxation presolved: 5 rows, 19381 columns, 96905 nonzeros
#> 
#> 
#> Root relaxation: objective 7.244150e+01, 13 iterations, 0.03 seconds (0.05 work units)
#> 
#>     Nodes    |    Current Node    |     Objective Bounds      |     Work
#>  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
#> 
#>      0     0   72.44150    0    2  164.20803   72.44150  55.9%     -    0s
#> H    0     0                      72.6973120   72.44150  0.35%     -    0s
#> 
#> Explored 1 nodes (13 simplex iterations) in 0.29 seconds (0.37 work units)
#> Thread count was 1 (of 12 available processors)
#> 
#> Solution count 3: 72.6973 164.208 181.135 
#> 
#> Optimal solution found (tolerance 1.00e-01)
#> Best objective 7.269731204374e+01, best bound 7.244150339288e+01, gap 0.3519%

##############################################################
#fourth problem, same as third problem but with boundary penalty added as in second problem

p4 <- problem(salt_pu_rescaled, salt_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.30) %>%
  add_binary_decisions() %>%
  add_boundary_penalties(0.001) %>% 
  add_gurobi_solver(gap = 0.1, verbose = TRUE)

sp4 <- solve(p4)
#> Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (linux64)
#> Thread count: 6 physical cores, 12 logical processors, using up to 1 threads
#> Optimize a model with 77397 rows, 58490 columns and 253754 nonzeros
#> Model fingerprint: 0x4bd3e9de
#> Variable types: 0 continuous, 58490 integer (58490 binary)
#> Coefficient statistics:
#>   Matrix range     [1e-01, 1e+00]
#>   Objective range  [2e-01, 1e+02]
#>   Bounds range     [1e+00, 1e+00]
#>   RHS range        [2e+03, 5e+03]
#> Found heuristic solution: objective 3369.2639119
#> Found heuristic solution: objective 218.3352865
#> Presolve time: 0.40s
#> Presolved: 77397 rows, 58490 columns, 253754 nonzeros
#> Variable types: 0 continuous, 58490 integer (58490 binary)
#> Found heuristic solution: objective 217.8919877
#> Root relaxation presolved: 77397 rows, 58490 columns, 253754 nonzeros
#> 
#> 
#> Root simplex log...
#> 
#> Iteration    Objective       Primal Inf.    Dual Inf.      Time
#>    21311    1.1757706e+02   1.457713e+03   0.000000e+00      5s
#>    27874    1.2404391e+02   0.000000e+00   0.000000e+00      8s
#>    27874    1.2404391e+02   0.000000e+00   0.000000e+00      8s
#> 
#> Root relaxation: objective 1.240439e+02, 27874 iterations, 7.93 seconds (20.04 work units)
#> 
#>     Nodes    |    Current Node    |     Objective Bounds      |     Work
#>  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
#> 
#>      0     0  124.04391    0  919  217.89199  124.04391  43.1%     -    8s
#> H    0     0                     125.5430567  124.04391  1.19%     -    8s
#> 
#> Explored 1 nodes (27874 simplex iterations) in 8.61 seconds (20.63 work units)
#> Thread count was 1 (of 12 available processors)
#> 
#> Solution count 4: 125.543 217.892 218.335 3369.26 
#> 
#> Optimal solution found (tolerance 1.00e-01)
#> Best objective 1.255430567294e+02, best bound 1.240439061888e+02, gap 1.1941%

################################################

#plot costs on quantile scale
par(mfrow =c(1,2))
brks <- c(0, as.numeric(quantile(salt_pu)))
plot(salt_pu, breaks = brks, lab.breaks = brks, col = hcl.colors(n = length(brks)-1, palette = "viridis"), main = c("Baseline scenario cost"))

brks <- c(0,as.numeric(quantile(salt_pu_rescaled)))
plot(salt_pu_rescaled, breaks = brks, lab.breaks = brks, col = hcl.colors(n = length(brks)-1, palette = "viridis"), main = c("Rescaled cost (0.01 - 100)"))
```

![](https://i.imgur.com/dyjhXRd.png)

``` r
#show quantiles for each cost layer
quantile(salt_pu) 
#>           0%          25%          50%          75%         100% 
#> 2.552000e-02 2.777725e-01 1.285700e+00 3.480427e+00 1.000000e+04

quantile(salt_pu_rescaled)
#>           0%          25%          50%          75%         100% 
#>   0.01000000   0.01252228   0.02260057   0.04454571 100.00000000

#plot all solutions
plot(stack(sp, sp2, sp3, sp4), main = c("Baseline scenario", "Baseline scenario with bp", "Rescaled cost (0.01 - 100)", "Rescaled cost with bp"))
```

![](https://i.imgur.com/0zvuwPD.png)

``` r
#number of planning units in solution as % of total
eval_n_summary(p, sp)$cost/number_of_planning_units(p)
#> [1] 0.3247449
eval_n_summary(p2, sp2)$cost/number_of_planning_units(p2)
#> [1] 0.3273719
eval_n_summary(p3, sp4)$cost/number_of_planning_units(p3)
#> [1] 0.318935
eval_n_summary(p4, sp4)$cost/number_of_planning_units(p4)
#> [1] 0.318935

#costs of solutions as percent of total
100*eval_cost_summary(p, sp)$cost/ cellStats(salt_pu, sum, na.rm=TRUE)
#> [1] 0.3786426
100*eval_cost_summary(p2, sp2)$cost/ cellStats(salt_pu, sum, na.rm=TRUE)
#> [1] 0.3864349
100*eval_cost_summary(p3, sp3)$cost/ cellStats(salt_pu_rescaled, sum, na.rm=TRUE)
#> [1] 2.215871
100*eval_cost_summary(p4, sp4)$cost/ cellStats(salt_pu_rescaled, sum, na.rm=TRUE)
#> [1] 2.77354
```

<sup>Created on 2022-05-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for providing all these details - that really helped a lot!

Yeah, under the min set objective, re-scaling the cost values does indeed alter the influence that boundary penalties have on the overall solution. This is because penalties work by blending the equations for the primary objective (e.g. minimize total cost) and the penalty (e.g. minimize total exposed boundary length) togeather into a single equation. As such, when we use the min set objective with boundary penalties, optimization problem is minimizing `total_cost + (penalty_value * total_exposed_boundary_length)`. This means that the optimizer can find better solutions with a smaller total cost or a smaller total exposed boundary length. If the planning unit cost values are generally much higher than the boundary length values, then better solutions will involve focussing on minimizing total cost (unless we set a relatively high `penalty_value` to counteract this). Whereas, if the planning unit cost values are generally much lower than the boundary length values, then the better solutions will involve focussing on minimizing the total exposed boundary length (unless we set a relatively low `penalty_value` to counteract this). 

Here's one way to think about linearly re-scaling the values. If we re-scale the costs to be between a smaller range of values (e.g. if they were orignally between 1 -- 1e8 and we re-scale to 1 -- 100), this is like setting a higher penalty value. If we re-scale the boundary lengths to be between a smaller range of values (e.g. if they were orignally between 1 -- 1e8 and we re-scale to 1 -- 100), this is like setting a lower penalty value. Indeed, in the [calibrating trade-offs tutorial](https://prioritizr.net/articles/calibrating_trade-offs_tutorial.html) I suggest re-scaling the boundary penalties, because it means we don't have to explore some really low penalty values (e.g. 1e-6, or 1e-8) in order to get useful solutions.

How does that sound? Let me know if anything I've written isn't clear?

**Comment by jflowernet** [comment]
@jeffreyhanson As ever many thanks for this - all very clear and helpful! I just read through the tutorial you linked and this is also very helpful and explains why my boundary penalty values have had to be so low.

I was just exploring the impact of different cost range scaling while keeping the boundary penalty constant, which shows visually what you describe - decreasing the range of cost values is equivalent to a higher penalty and therefore greater prioritized area clumping. I'm including the reprex here for my future self and anyone else who might find it useful.

So, when comparing solutions from prioritization runs using different cost inputs (e.g. fishing catch of trawling and long-lining vessels), it is essential to rescale to the same range if I want to compare like-for-like solutions that include a boundary penalty (right?). But I just wanted to check if there was any potential issue with re-scaling and comparing the data this way? I presume not, since high cost values will still be relatively high cost values regardless, but was wondering if there is an issue if the cost value maximums are a factor of say 1000 or more different?

``` r
library(prioritizr)
#> Loading required package: raster
#> Loading required package: sp
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1; sf_use_s2() is TRUE
#> Loading required package: proto
library(prioritizrdata)

data(salt_pu)
data(salt_features)

set.seed(500)

#generic function for rescaling a raster between new_min and new_max
func_rescale <- function(x, new_min, new_max){
  rescaled_value <- ((x - cellStats(x, min, na.rm=TRUE)) * (new_max - new_min) / (cellStats(x, max, na.rm=TRUE) - cellStats(x, min, na.rm=TRUE))) + new_min
}


#setup cost stack with scaled options
costs <- stack(salt_pu)
costs <- salt_pu %>% 
  func_rescale(new_min = 0.01, new_max = 1000) %>% 
  addLayer(costs, .)

costs <- salt_pu %>% 
  func_rescale(new_min = 0.01, new_max = 100) %>% 
  addLayer(costs, .)

costs <- salt_pu %>% 
  func_rescale(new_min = 0.01, new_max = 10) %>% 
  addLayer(costs, .)

solutions <- stack()
problems <- list()

for (i in 1:nlayers(costs)) {
  p <- problem(costs[[i]], salt_features) %>%
    add_min_set_objective() %>%
    add_relative_targets(0.30) %>%
    add_binary_decisions() %>%
    add_boundary_penalties(0.001) %>% 
    add_gurobi_solver(gap = 0.1, verbose = FALSE)
  
  problems[[i]] <- p
  
  solutions <- addLayer(solutions, solve(p))
}

################################################


#plot all solutions
plot(solutions, main = c("Baseline scenario", "Rescaled cost (0.01 - 1000)", "Rescaled cost (0.01 - 100)", "Rescaled cost (0.01 - 10)"))
```

![](https://i.imgur.com/6Hs43BU.png)

``` r
#number of planning units in solution as % of total
for (i in 1:nlayers(costs)) {
  print(eval_n_summary(problems[[i]], solutions[[i]])$cost/number_of_planning_units(problems[[i]]))
}
#> [1] 0.3273719
#> [1] 0.3285339
#> [1] 0.318935
#> [1] 0.3133273

#costs of solutions as percent of total
for (i in 1:nlayers(costs)) {
  print(100*eval_cost_summary(problems[[i]], solutions[[i]])$cost/ cellStats(costs[[i]], sum, na.rm=TRUE))
}
#> [1] 0.3864349
#> [1] 0.6143793
#> [1] 2.77354
#> [1] 13.17578
```

<sup>Created on 2022-05-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jeffreyhanson** [comment]
Hmm, I think there might be some issues with simlpy linearly re-scaling the cost values to make comparisons among prioritizations based on different datasets. For example, consider two cost datasets: both have a minimum and maximum value of 1 and 100 (respectively), but one has a mean value of 30 and one has a mean value of 99. In this situation, we might expect a priroitization generated using the first dataset to focus more on minimizing spatial clustering than a prioritization generated using the second dataset (assuming the same penalty value). So, I don't think this approach would result in "like-for-like" comparisons. Does that make sense? 

To make "like-for-like" compairons of prioritizations based on different cost datasets, I would suggest something like this. Here we (1) use a min set objective to ensure that all targets will be met, (2) use boundary penalties, (3) use zero costs so that the blended objective function focusses purely on total exposed boundary length, and (4) use a linear constraint to impose a maximum total cost (scaled as a percentage of the total). E.g., something like this could be done to generate a prioritization with a 25% budget. Note that if the budget is too low, then you'll get errors about infeasbility.

```
# generate a prioritization using 1st cost layer
p1 <-  problem(costs[[1]] * 0, salt_features) %>%
    add_min_set_objective() %>%
    add_relative_targets(0.30) %>%
    add_linear_constraints(
      x = costs[[1]], threshold = cellStats(costs[[1]], "sum") * 0.25, sense = "<=") %>%
    add_binary_decisions() %>%
    add_boundary_penalties(0.001) %>% 
    add_gurobi_solver(gap = 0.1, verbose = FALSE)

# generate a prioritization using 2nd cost layer
p2 <-  problem(costs[[2]] * 0, salt_features) %>%
    add_min_set_objective() %>%
    add_relative_targets(0.30) %>%
    add_linear_constraints(
      x = costs[[2]], threshold = cellStats(costs[[2]], "sum") * 0.25, sense = "<=") %>%
    add_binary_decisions() %>%
    add_boundary_penalties(0.001) %>% 
    add_gurobi_solver(gap = 0.1, verbose = FALSE)
```

**Comment by jflowernet** [comment]
Ahh, yes, I understand what you are saying about the distribution of cost values and resulting effect on spatial clustering. 

Your approach for a "like-for-like" comparison sounds good. I'll try it out with our real world data!

We are also trying using the linear constraints as an option for essentially combining multiple costs into one problem - setting one cost dataset as the cost and others as linear constraints with max budgets. Still testing, but seems promising, though there is a trade-off of setting the budgets high enough that the problem is feasible while still keeping the principle cost low. If you have any thoughts on this, do let me know.

I'll leave the issue open for a day, then close if I haven't heard anything, but thank you very much for all the answers and suggestions!

**Comment by jeffreyhanson** [comment]
Awesome - yeah that all sounds great! Yeah, that's exactly how I would recommend accounting for multiple cost datasets (i.e., multiple budgets with a linear constraints).

**Comment by jflowernet** [comment]
Thanks so much Jeff. Really appreciate your quick responses as we have a lot of prioritization work going on at the moment. Our in country partners really like seeing the prioritization outputs and seeing where they come from, so thanks for all your hard work and continuing upgrades to prioritizr!

**Comment by jeffreyhanson** [comment]
No worries - happy to help!
