### ISSUE TITLE
Linear constraints and manual targets with target sense equivalence

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#243]
Hi Jeff or any of the prioritizr crew, 

Sorry, yet another question, but hopefully a quick one. This is coming via my colleague @echelleburns who I'm working with:

Is using `add_manual_targets` using the target sense the same as `add_linear_constraints` with the same sense?

Example: Is 
`add_manual_targets(feature = "feature_column_name", type = "absolute", sense = "<=", target = 1000)` 
identical to 
`add_linear_constraints(threshold = 1000, sense = "<=", data = "feature_column_name")`?

**Comment by jflowernet** [comment]
Very clear, many thanks Jeff!

I feel like it might be useful to have some of these Q & As compiled somewhere for prioritizr users. I don't want to promise anything, but I could try and put an Rmarkdown together at some point. Just a thought!

**Comment by jeffreyhanson** [comment]
No worries! 

Yeah that's a great idea! Yeah, no worries if you don't have time, but an FAQ document would be brilliant. We could include it as a vignette.
