### ISSUE TITLE
CBC solver error: cannot allocate vector of size 64.9 Gb

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#249]
Hi Jeff and all,

I'm trying out the FOSS solvers, CBC and rsymphony, with the hope of using them for a Shiny app.

Using the `add_cbc_solver(gap = 0.5, threads = parallel::detectCores()-1)` throws an error: `Error: cannot allocate vector of size 64.9 Gb`. The error only occurs if I add a boundary penalty (no matter how small); without a boundary the problem is solved in less than a second.

For comparison Gurobi solves the problem in 13s and using rsymphony ~ 6mins (with boundary penalty, few seconds without)

Details of the problem:
52, 525 planning units
2, 8999 'features' (in dataframe) - 21 actual features, the rest being constraints to ensure whole patches (seamounts) are selected using the code you provided in #226 
Boundary matrix - created using an `sf` object with all the planning units (i.e., both seamount and grid-cell based planning units): `boundary_matrix(pu_sf, str_tree = TRUE)` as you suggested [here](https://github.com/prioritizr/prioritizr/issues/238#issuecomment-1100757055)

It seems like CBC is trying to do something incredibly memory intensive to try and solve the problem??

 Apologies for the lack of a reprex - but I suspect this is related to the complexity of the problem which won't be easy to re-create.

Thanks as ever!

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for reaching out! It looks like this issue might be related to this bug (https://github.com/dirkschumacher/rcbc/issues/63). I'll create a PR to see address it, and see if that fixes it. Once I've done that, I'll post instructions for installing a branch with the fix.

**Comment by jeffreyhanson** [comment]
@jflowernet, I've submitted the PR to the rcbc package which should fix this issue (see https://github.com/dirkschumacher/rcbc/pull/64). To install the fix on your computer, please use the code:

```
remotes::install_github("jeffreyhanson/rcbc@fix63")
```

**Comment by jflowernet** [comment]
Amazing, thanks @jeffreyhanson, that has solved the error!

Just wanted to note that I get a 'problem' in the output that I don't remember being there before (see first lines of CBC solver output below) though it might have been, but the solver runs fine and produces an output analogous to the Gurobi one, so doesn't seem to be an issue:

`Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Mar 24 2020 

command line - problem -log 1 -verbose 1 -presolve on -ratio 0.1 -sec 2147483647 -threads 11 -timeMode elapsed -solve -quit (default strategy 1)
verbose was changed from 0 to 1
ratioGap was changed from 0 to 0.1
seconds was changed from 1e+100 to 2.14748e+09
threads was changed from 0 to 11
Option for timeMode changed from cpu to elapsed
Continuous objective value is 419.965 - 0.22 seconds
Cgl0003I 0 fixed, 1 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions`

**Comment by jeffreyhanson** [comment]
Awesome! Interesting, I don't remember seeing `-problem` as a command line option and I can't find it in the documentation. I guess if it works and produces reasonable output that would suggest everything's working?

**Comment by jflowernet** [comment]
Yeah, I agree - everything seems to be working! 

Thanks for your help Jeff. I'll close this now

**Comment by jeffreyhanson** [comment]
No worries! Also, if your interested in a shiny app for prioritizr stuff, I'd recommend checking out this project (https://github.com/NCC-CNC/wheretowork).
