### ISSUE TITLE
solution output

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#25]
A small addition to solution outputs that would be great to have in addition to (usually) the solution raster, would be parameters that are returned by the solvers, such as runtime, status (i.e. did the solver reach an optimal solution) and cost. At least for me that's very useful information to have.

**Comment by jeffreyhanson** [comment]
Yeah, I agree it's important but I'm not sure how to include it in returned objects. I suppose one approach would be to add this information to the object's attributes? One can add a variety of info to objects this way. 

For example:

```
# create vector
x <- 1:5
# add attribute
attr(x, "note") <- "information"
# print object
print(x)
# access data in attribute
attr(x, "note")
```

**Comment by ricschuster** [comment]
Attributes is certainly one way. Would a named list work too? 
Maybe as a standard the first item being the solution raster and the rest with structured order. If the solution raster is NA (cases where no spatial data was supplied) list[[2]] could be the output df? Not sure if that makes sense, I'm just not a big fan of attributes.

**Comment by jeffreyhanson** [comment]
Yeah, I'm not a big fan of attributes in general either. I really like that prioritizr outputs the `Spatial`/`Raster`/`data.frame` objects as solutions, and the outputs can be immediately used for subsequent analysis. Is there any way we could implement this without resorting to attributes?

**Comment by ricschuster** [comment]
Not sure. Maybe attributes do make the most sense in this case. Maybe use attributes for now and if we come across a better solution we can adjust?

**Comment by jeffreyhanson** [comment]
Ok sounds like a plan.
