### ISSUE TITLE
add new solver to support HiGHS software

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#250]
HiGHS is a FOSS optimization software that can solve MILPs (see https://highs.dev/). I just noticed that a highs R package was recently published on CRAN (https://cran.r-project.org/package=highs). It would be great to add a new solver function to support this software, and possibly re-run the benchmarks vignette to see how it compares.

**Comment by jeffreyhanson** [comment]
@ricschuster, given that package probably needs to be submitted to CRAN in the next couple of days, I think it's probably worth delaying this feature till later?

**Comment by ricschuster** [comment]
Agreed.

**Comment by jeffreyhanson** [comment]
Ok great - I'm itching to see how it compares with Gurobi.

**Comment by ricschuster** [comment]
Me too. Would be pretty cool if it came close in performance.

**Comment by jeffreyhanson** [comment]
Yeah, it's 8x slower than Gurobi according to the Mittelmann benchmarks (http://plato.asu.edu/ftp/milp.html). However, these benchmarks include a heap of different optimization problems of varying size and complexity - so HiGHS could potentially have really good performance for the typical SCP problems (e.g., min set, min shortfall, boundary penalties)

**Comment by ricschuster** [comment]
That would be really neat. What's your sense of how much effort it would be to add that solver? Running the benchmarks with HiGHS included would be great at one point regardless of when we might include the solver in prioritizr.

**Comment by jeffreyhanson** [comment]
It shouldn't be too tricky. The API looks very similar to that for other solvers. I would guess about half a days work to add the solver, and then maybe an hour or two to update the benchmark code.

**Comment by ricschuster** [comment]
Awesome!

**Comment by jeffreyhanson** [comment]
I couldn't resist - I've managed to get a highs solver working locally. However, the package doesn't let you specify an optimality gap (although HIGHS does support this, the R package won't let you set it) and it forces you to always use the maximum number of threads on the system (which makes benchmarking a bit annoying). I'll send an email to the maintainer and see if it's possible to address these issues.

**Comment by ricschuster** [comment]
Nice!
Unfortunate about the gap and threads. Would be good if the maintainer could address these issues.

**Comment by jeffreyhanson** [comment]
I heard back from the maintainer and they've already updated the package to address these issues. Although the source code is available on GitLab (https://gitlab.com/roigrp/solver/highs), it seems that installing this package from GitLab is not easy (because you must have a GitLab account and SSH key setup to install the package via the remotes R package - which is because the repo uses Git submodules so simply installing via HTTPS does not work...). I've attached a built version of the updated highs package to this post (kindly provided by the highs maintainer, ([click for download link: highs_0.1-3.tar.gz](https://github.com/prioritizr/prioritizr/files/9528565/highs_0.1-3.tar.gz)), and created a prioritizr branch (`highs-solver`) which can use this package to create prioritizations using HiGHS.

**Comment by ricschuster** [comment]
This is awesome!
Will you test this out via the benchmark vignette?

**Comment by ricschuster** [comment]
Just saw the PR for this :)

**Comment by jflowernet** [comment]
Super interested to see if HiGHS performs better than CBC and rsymphony! This could be very useful for public code release and maybe Shiny apps. 

I was testing a prioritization I'm doing which includes the prioritizing whole patches code you kindly wrote @jeffreyhanson and Gurobi solves almost instantly, but CBC takes ~40s - not a big deal for me, but if it was to be used in a Shiny app, it's not ideal.

Thanks for always striving to make prioritizr better!

**Comment by ricschuster** [comment]
Thanks Jason!

We are currently running the benchmarking analysis (https://github.com/prioritizr/benchmark) to then update the benchmark vignette (https://prioritizr.net/articles/solver_benchmarks.html). I hope we have some updates by early next week. Fingers crossed for HiGHS.

**Comment by jeffreyhanson** [comment]
Thanks @jflowernet! Yeah, I feel like one of the remaining big limitations of prioritizr is that it still requires commerical solvers for large-scale problems - fingers crossed HiGHS can overcome this. 

Interesting! Yeah, we've encountered similar issues with developing the Where to Work tool. Although FOSS solvers are great for developing shiny apps, the wait times don't always conform to user expectations. Depending on the overall goal of the tool (e.g., if responsiveness is more important than optimality), one strategy to help reduce wait times is to relax the optimality gap or impose a time limit. Another strategy is to precompute all possible solutions to a range of different targets and weights, and then simply show a pre-calculated solution when the user wants to "generate" a prioritization.

**Comment by jflowernet** [comment]
Thanks for the tips Jeff! If we do develop a Shiny app it will be with Ant, Jase and Daniel at UQ who have experience, so we should be able to get around the slowness, or make sure users expectations are not for instant results. 
Fingers crossed for HiGHS!
