### ISSUE TITLE
CRS error

### ISSUE THREAD

**Issue by MillerJeju** [prioritizr/prioritizr#259]
Hi, I believe my problem is quite simple. I really want to advance my research using Prioritizr.
In my code, jeju_cost file is a cost-related shp file, and con is the Maxent result value. It's a CRS error problem, but when I look at it, there seems to be no problem, but an error occurred. I tried several ways to solve the error, but I couldn't. Please help me.

`p10_c <- problem(jeju_cost, features = con,
                 cost_column = "cost") %>%
  add_min_set_objective() %>%
  add_relative_targets(0.10) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0)`
Error in (function (cond)  : 
  Error evaluating argument 'x' when selecting method for function 'add_relative_targets': sf::st_crs(x@proj4string) not equal to sf::st_crs(features[[1]]@crs)

`jeju_cost@proj4string`
Coordinate Reference System:
Deprecated Proj.4 representation:
 +proj=tmerc +lat_0=38 +lon_0=127 +k=1 +x_0=200000 +y_0=600000 +ellps=GRS80 +units=m +no_defs 
WKT2 2019 representation:
PROJCRS["ITRF_2000_Transverse_Mercator",
    BASEGEOGCRS["ITRF2000",
        DATUM["International Terrestrial Reference Frame 2000",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6656]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",38,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",127,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",200000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",600000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]] 

`con@crs`
Coordinate Reference System:
Deprecated Proj.4 representation:
 +proj=tmerc +lat_0=38 +lon_0=127 +k=1 +x_0=200000 +y_0=600000 +ellps=GRS80 +units=m +no_defs 
WKT2 2019 representation:
PROJCRS["ITRF_2000_Transverse_Mercator",
    BASEGEOGCRS["ITRF2000",
        DATUM["unnamed",
            ELLIPSOID["GRS 1980",6378137,298.257222101004,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",8997]],
    CONVERSION["Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",38,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",127,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",200000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",600000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]

**Comment by jeffreyhanson** [comment]
Hi @MillerJeju,

Thanks for reaching out! It seems like the planning unit and feature data have slightly different coordinate reference system parameters (see below for image of the text difference). Although the parameters effectively mean the same thing and both correspond to EPSG:9001 (AFAIK), these minor differences are causing prioritizr to think that your planning unit and feature data are in different coordinate reference systems (and it requires both datsets to have the same coordinate reference system). Does that make sense? This might happen if you prepared the datasets using different software (e.g. planning unit data in ArcGIS and feature data in R).

Could you please try the following code to (1) manually overwrite the coordinate systems to ensure that they are identical (**note that we would normally reproject the data when data are in different coordinate reference systems, but here we are confident they are already in the same projection**) and (2) build the problem formulation?

```
# overwrite coordinate systems
jeju_cost@proj4string <- con@crs

# build problem formulation
p10_c <- 
  problem(jeju_cost, features = con, cost_column = "cost") %>% 
  add_min_set_objective() %>% 
  add_relative_targets(0.10) %>% 
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0)
```

--------------

Here's a comparison of the coodinate reference systems:

![image](https://user-images.githubusercontent.com/3610005/200413107-dd6675f1-ebce-4dc9-9ff0-d582907141cf.png)

**Comment by MillerJeju** [comment]
I did it the way you said and it works good!!! Thank you very much. It will be valuable information for my research.

**Comment by jeffreyhanson** [comment]
Awesome! No worries. It sounds like we've resolved this issue, so I'll close it. Please feel free to open a new issue or re-open this one if you encounter any further problems or have any questions.
