### ISSUE TITLE
planning unit importance [feature proposal]

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#26]
It seems like a lot of people like some measure of importance for each planning unit in a solution (eg. selection frequency from Marxan, or ranking from Zonation). So I wonder if we should try adding some functionality to calculate "planning unit priority" or "planning unit importance" given a solution? I remember there was some talk of this on the Marxan emailing list a while ago. 

Do people think this would be useful? What algorithms/metrics should be used? Ideally the algorithm/metric would be problem invariant, so it would be useful no matter what constraints/objectives/decisions were used.

**Comment by jflowernet** [comment]
As someone who has used prioritizr as an off-the-shelf tool for marine spatial planning, I think this sounds like a good idea. I ran scenarios with different protection targets (20, 30 and 40%), which kind-of gets at the same problem (if I understand correctly), so I could see which areas/units are picked-up and dropped. But it would certainly be good to have some relative importance rank when presenting to stakeholders.

Apologies, I'm not familiar enough with the mechanics to suggest algorithms/ metrics, but thanks for working on this!

**Comment by jeffreyhanson** [comment]
Awesome - thanks sharing your experiences @jflowernet! I find it really useful to have a user's perspective on potential features.

Here's some ideas for calculating this metric that are problem invariant from what I can tell.

1. We could try implementing the irreplaceability method outlined in [Ferrier _et al._ 2000](http://www.sciencedirect.com/science/article/pii/S0006320799001494).

2. I wonder if we could just take a problem and a solution, and for each selected planning unit, lock the planning unit out, solve the problem again, calculate the cost of the solution with the planning unit locked out minus the cost of the original solution, and use this value to denote irreplaceability for that planning unit. Planning units with are more irreplacable will result in costlier solutions when they are locked out, and thus be associated with higher scores.  This has the advantage of being in the same units as the cost layer so hopefully is easier to understand.

Thoughts?

**Comment by jflowernet** [comment]
No worries, and thanks for making prioritizr so user friendly!

I like option 2, though it sounds like it might be computationally intensive for big problems. I had a read of Ferrier et al. but their method is definitely less intuitive and harder to grasp from the user-end (at least IMHO).

**Comment by jeffreyhanson** [comment]
I just stumbled across this paper which also proposes "replacement cost" as a measure of importance /irreplacibility:

http://www.sciencedirect.com/science/article/pii/S0006320706001820

**Comment by ninsbl** [comment]
Isn't the selection frequency type of importance definition (almost) covered by the portfolio option already? Would be straightforward also for the user to compute esp. if R code is given in the examples in the manual /website...

**Comment by ricschuster** [comment]
Yes, but if we want to create a more sophisticated irreplacibility metric, we would have to go further than the portfolio option. On the other hand, the portfolio option might be all most users would need really. 

What do you think @jeffreyhanson?

**Comment by jeffreyhanson** [comment]
I've been thinking about this for a while and I think that terms like planning unit "importance" or "ireplaceability" or "priority" can mean a broad range of different things to different people, and can be more or less useful depending on the conservation scenario at hand. I'm sorry if this reply is a bit long, I just feel that this is a complicated topic and I don't know of any simple answers.

I suppose, in an ideal world, we would have access to biodiversity (e.g. species' habitat maps), cost data (e.g. acquisition cost, management action costs) that is at high spatial and temporal resolution. That way, we could use dynamic formulations of the reserve selection problem which explicitly plan for protected area acquisitions across space and time (e.g. [1](https://www.sciencedirect.com/science/article/pii/S0006320706000541), [2](http://www.sciencedirect.com/science/article/pii/S0928765503000733))  to make very precise and (hopefully) effective schemes. But, to my knowledge, such data are not available for a large number of species, and so, rather than planning for acquisitions over time and space, many conservation planners must develop a plan for a set of protected areas using data for only one point in time and then somehow establish an order of priority among these areas---something which is inherently a temporal process and, perhaps, can only be reliably achieved using temporal data sets which arguably do not exist.

I, though perhaps others may not, think that when dynamic reserve selection problems cannot be used (e.g. due to resource limitations), the process of deciding on an "agreeable" solution is separate from the "order of priority" that parts of the solution should be implemented. For real-world planning scenarios, I feel compelled to add that I hope relevant stakeholders would be involved in both of these stages and would encourage some back-and-forth between the two stages. So, I like the idea of the replacement cost metric outlined in [Cabeza & Moilanan 2006](http://www.sciencedirect.com/science/article/pii/S0006320706001820) because it (1) separates the "finding a good solution stage" for the "order of priority stage" and (2) it can accommodate complex constraints in a reserve selection formulations (e.g. in reserve selection problems that have constraints which require all planning units to be connected, `add_connected_constraints`, this metric can highlight planning units which are important for connectivity reasons).  However, I don't think this metric is _perfect_ because it still does not utilize any temporally varying data which, in my opinion, is by definition needed to establish an order of priority. Perhaps the replacement cost data could be calculated using future estimates of the costs needed to convert the planning units to suitable habitat? I don't know.

I think "selection frequency" is an attractive measure of importance because it is fairly easy to calculate, and it would seem logical that planning units that are contained in multiple near-optimal solutions are more important for achieving the conservation objectives (e.g. secure habitat for species X, Y, and Z). But selection frequency is probably a poor measure of "priority" or "irreplaceability" because it does not actually include any information about how likely planning units are to be made unsuitable for their intended purpose (e.g. habitat degradation rates). For example, one might observe in some conservation planning scenarios that the planning units with the highest selection frequencies should be the lowest "priority" because they are located in areas that are far from human influence. This is aside from the fact that "selection frequency" is often used to identify a "solution", whereby _N_ solutions are generated that meet the conservation objectives, selection frequencies are calculated, all the original solutions are discarded, and a new solution is generated that contains _X_ % of the planning units with the highest selection frequencies. This process which ignores the principle of complementarity, and (likely) returns solutions that are much less effective than any of the solutions in the original set of _N_ solutions. So, I think selection frequency can, in some specific cases, be useful but I also see it being misused.

Overall, I think selection frequency is useful because a lot of people know about it and understand it. But, in many cases selection frequency may not be particularly useful for establishing an effective "order of priority" so it would be useful to provide additional methods. What do everyone else think?

**Comment by ricschuster** [comment]
I didn't realize that its been three weeks since your post. Thanks very much for this Jeff, very interesting read.

I think providing a selection frequency metric can be useful in some cases and people do know the metric from Marxan. 

As for additional methods and metrics, I agree that it would be useful to provide them I'm just not sure what would be useful given the snap shot data people usually have. For irreplecability, I do like the locking out and re-running idea, but that would be really costly in terms of computational resources. I wonder if locking out fixed proportion of random sites from the solution would help improve this approach at all? The Cabeza & Moilanan 2006 approach sounds similar in some ways. Maybe its worth looking into that further and see if we can come up with a way to include it into this package?
