### ISSUE TITLE
CRAN check NOTE, update to C++17

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#263]
The package apparantly fails to compile with C++17, and so the package needs to be updated to address this issue before resubmission. CRAN checks now specify the NOTE:

```
checking C++ specification ... NOTE
  Specified C++11: please update to current default of C++17
```

My understanding is that we don't need to address this ASAP, because CRAN won't archive a package for checks producing NOTEs. We just need to make sure this is addressed before next submission. I'll work on addressing this as a part of the terra overhaul updates. How does that sound @ricschuster?

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson, that sounds good to me!

**Comment by ricschuster** [comment]
Very interesting. Thanks very much for looking into this Jeff!
