### ISSUE TITLE
Output resulting in bands

### ISSUE THREAD

**Issue by KCarrollEcology** [prioritizr/prioritizr#268]
I am having an issue with my output (I included a figure below to show what the issue is). I am not receiving any error messages and using the same code for all planning problems. However, when  I run planning problems for one set of metrics, it gives the US "pants," and I can't determine why this is only happening for those two variables (see Figures d and e). Any advice, help, or insights would be much appreciated! 

![Figure5_test](https://user-images.githubusercontent.com/39779120/221887087-e32af273-7e51-4095-9a50-cdcea81f264c.jpg)

**Comment by jeffreyhanson** [comment]
Hi @KCarrollEcology,

Yeah, the solutions do look a bit strange. This behavior generally occrurs when you have a small number binary features (e.g. species presence/absence) that each cover most of the study area, and all planning units have equal cost values. Does that describe your data for scenarios (e) and (f)? Briefly, it might suggest that there might not be enough data (e.g. features, cost data) to identify meaningful priority areas at the scale of the planning untis (e.g., this is sort of like having low degrees of freedom for a statistical analysis). For ideas on fixing this, could you please take a look at this issue on the same topic (https://github.com/prioritizr/prioritizr/issues/205)? Would any of those suggestions work?

**Comment by KCarrollEcology** [comment]
@jeffreyhanson Thank you very much for your response. I am using an equal cost (1) layer, and the feature layer is a single continuous variable from 0 to 1. However, the variable is skewed towards 1, and this might indicate the issue. After reviewing topic 205 and your response, I will try adding more features and see if that remedies the issue!

**Comment by jeffreyhanson** [comment]
No worries! Ah ok, yeah, I think that might be the issue. I'm guessing that the prioritization is probably just selecting pixels with the highest values needed to meet the target (assuming min set objective). Please let me know if you get stuck trying to fix this, and I can try suggesting some other ideas.

**Comment by jeffreyhanson** [comment]
@KCarrollEcology, I just wanted to follow up and ask if you were abel to resolve the issue, or if there was anything else I could do to help? If it's been resolved, shall we close the issue?

**Comment by KCarrollEcology** [comment]
Jeff,
Thank you for checking back! Everything has been resolved.
Best,
K
