### ISSUE TITLE
Get Solution cost/quality/objective value

### ISSUE THREAD

**Issue by Carina-Firkowski** [prioritizr/prioritizr#272]
Hi there,
Is it possible to access the `Solution cost` value (_i.e._, -88.9248820663) from the code below?
```
> scenarioSolution <- solve(scenarioProblem)
Starting Preprocessing...
Preprocessing finished...
 	 with no modifications...
Solving...
****************************************************
* Optimal Solution Found                           *
****************************************************
Solution Found: Node 0, Level 0
Solution Cost: -88.9248820663
```
Alternatively, is there a single measure of solution quality or of the objective value of a solution?
Thanks!

**Comment by jeffreyhanson** [comment]
Hi @Carina-Firkowski,

Yeah, this can be done using:

```
attr(s42scenarioSolution "objective")
```

For more info, see https://prioritizr.net/articles/package_overview.html#solve-the-problem

How does that sound?

**Comment by Carina-Firkowski** [comment]
That's great, thanks @jeffreyhanson!

**Comment by jeffreyhanson** [comment]
No worries! Did you have any further questions? If not, I'll the issue?

**Comment by Carina-Firkowski** [comment]
No, that was all. Thanks!
