### ISSUE TITLE
Remaining tasks for version 8

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#273]
I'm creating this issue to keep track of the remaining tasks I need to do before we release version 8 of prioritizr. Here's what I have so far (below). @ricschuster and @edwardsmarc, please let me know if I've missed anything?

* [x] update `assertions.misc`: In the file assertions_misc.R this line of code: "instructions in {.vignette prioritizr::gurobi_installation_guide}." should be "instructions in {.vignette \"gurobi_installation_guide\"}."
* []x update README so that it works. To do this, I will update prioritizrdata so that it uses the version of the dataset in the prioritizr paper, and update the formulation to match that of the prioritizr paper.
* [x] update `print()` and `summary()` functions so that the solver and portfolio informaiton is shown in a new "`optimization` section (instead of `formulation`).
* [x] fix boundary issues for `tas_pu` data in prioritizrdata so that it doesn't result in warnings when using `eval_boundary_summary()`.
* [x] update `add_manual_targets` documentation to mention list format for `zone` column.
* [x] check sf line example in `adjacency_matrix()`.
* [x] add explanation for start solution to documentation for `add_gurobi_solver()` and `add_cbc_solver()`.
* [x] update multiple zone example for `rij_matrix()`.

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson! Those cover the things I know about and nothing else comes to mind.

**Comment by edwardsmarc** [comment]
This looks good to me @jeffreyhanson
