### ISSUE TITLE
add_min_occ_constraints [feature proposal]

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#28]
I propose adding a `add_min_occ_constraints` function that would allow users to add minimum occurrence constraints, similar to Marxan, such that each feature must be represented in _n_ number of selected planning units.

The function could look something like this:

```
#' Add minimum occurrence constraints
#'
#' This function adds constraints to ensure that features occur in at least a pre-specified
#' number of planning units.
#'
#' @param x \code{\link{ConservationProblem}} object.
#'
#' @param n \code{numeric} minimum number of planning units that each feature needs to be 
#'      represented in. The argument to \code{n} can be single number to represent each feature in
#'      \code{n} in planning units, and a \code{numeric} vector can be used to ensure that
#'      each feature occurs in a minimum number of planning units.
#'
#' @details This constraint is only useful when the feature data are continuous (e.g. amounts or 
#'      proportions) and has no effect if the feature data are binary (i.e. zero or one).
#'
#' @return \code{\link{ConservationProblem}} with the constraint added to it.
#'
#' @seealso \code{\link{constraints}}.
#'
#' @export
add_min_occ_constraints <- function(x, n) {
   # insert magic here
}
```

What do people think? I think Marxan has this functionality. Would it be useful in prioritizr?

**Comment by ricschuster** [comment]
I like `min_occ` a lot, but I'm not sure if we mean the same thing here (see below). I have previously done this before running Marxan (or prioritizr), but it would be neat to have this in prioritizr.

I am a bit confused by the description though. Do you mean probability of occurrence (e.g. SDM output) would need to be > n for a planning unit to be considered? It doesn't look like it from the beginning of the documentation, but that's how I think about `min_occ`. Maybe you are thinking of something different than me here?

**Comment by jeffreyhanson** [comment]
Hmm, I think I didn't explain the idea well. 

I meant adding in constraints so that each feature must appear in _n_ different planning units in the solution. For instance, 10 % target representation targets for a feature might yield a solution which only represents it in 2 planning units. These constraints could be used to specify that the feature must appear in at least 5 planning units as a sort of bet hedging strategy. This set of constraints would aim to mimic the `targetocc` field in the _spec.dat_  Marxan input file [see section 3.3 in the manual](http://marxan.net/downloads/documents/marxan_manual_1_8_2.pdf). 

I like the idea of removing planning units with low probabilities of occurrence, but should this be step in the model building process or a pre-processing step conducted by the user?

**Comment by ricschuster** [comment]
Thanks for clarifying. I suspected we were talking about two different things. I haven't used what you describe before, but as its part of Marxan, including it in prioritzr would probably be a good thing.

re: low probability of occurrence removal. I think it would be good (and easy enough to implement) to include that in the problem building process. For one of the ILP Shiny apps I put together, I included an exclusion slider (constant for all features) that allowed users to easily explored the results of using different cut-offs. I just went ahead and set all feature values that were below the threshold.

**Comment by jeffreyhanson** [comment]
Ok, yeah, it would be fairly straightforward to implement this.

re: low prob removal: Yeah, that's a really good point. If it was implemented as a constraint then users would be ale to play around with it in the package's shiny app. Although, I worry that users might confuse "habitat suitability" (aka Maxent outputs) with "probability of occurrence" and so they might use this functionality to set the same threshold for different species. Since habitat suitability is only monotonically related to probability of occurrence, this could mean that they would be setting a very low probability threshold for some species. What do you think?

**Comment by ricschuster** [comment]
re: low prob removal. Good point. Its unfortunate that Maxent users have introduced that confusion. One, not ideal, way to deal with this would be to use a different term for this. One option could be to allow users to specify a % (of max) value, this way features that have low prop of occurrence in general get taken into account in a comparable way to ubiquitous features/species.

**Comment by jeffreyhanson** [comment]
I think a function like this would have to involve setting a threshold (or making assumptions about a threshold) and I think there are many cases where it would make sense to set different thresholds for different features/layers. I suggest we leave it up to the user to apply such thresholds themselves, so that way they know exactly what data/values prioritizr is using for the features?

**Comment by ricschuster** [comment]
Sounds good to me.
