### ISSUE TITLE
Solving using cbc

### ISSUE THREAD

**Issue by tinbuenafe** [prioritizr/prioritizr#283]
Hi @jeffreyhanson. I'm trying to solve a prioritization problem using `rcbc` (version 0.1.0.9001) and the dev version of prioritizr (version 8.0.2.2), but I'm having an error:

`Error: 'solve' is not an exported object from 'namespace:prioritizr'`

I have yet to try it with a different solver, but I was wondering if you have any way to solve this. Thanks.

**Comment by tinbuenafe** [comment]
Update: I've tried it with `gurobi` 10.0-1 and it still returns the same error.

**Comment by tinbuenafe** [comment]
I've used it with an archived version of prioritizr (version 7.2.2) and it worked fine with `rcbc` and `gurobi`.

My macOS is Ventura 13.3.1 with the Apple M2 Chip.

**Comment by jeffreyhanson** [comment]
Hi, thanks for reporting this! Is your code using `prioritizr::solve()`? If so, could you please try using `solve()` instead?

**Comment by tinbuenafe** [comment]
Yes, `solve()` works fine with the most recent version of prioritizr. But since I'm using it in a Shiny App, it would be best if I called the function with the package. For now, I'm using the older version of prioritizr to run the app.

**Comment by tinbuenafe** [comment]
I think so. Otherwise, if it uses `base::solve()` then it might best if we just rewrite all `prioritizr::solve()` to `base::solve()`?

**Comment by tinbuenafe** [comment]
Thanks Jeff!
