### ISSUE TITLE
Assertion on 'log_to_console' failed: Must be of type 'logical', not 'integer'.

### ISSUE THREAD

**Issue by ZMgogo** [prioritizr/prioritizr#289]
I'm running the tutorial code on my win11 computer, but always encounter the following Error.
**Assertion on 'log_to_console' failed: Must be of type 'logical', not 'integer'**.

![564299a0af140cc79a640855b97ce19](https://github.com/prioritizr/prioritizr/assets/28757336/84777b37-6407-4543-94b0-40b5fabecf01)

I have tried the following R versions, and there are all have problems. 
R-4.3.1, R-4.2.2, R-4.1.3

Sincerely hope someone can give some advice！

**Comment by jeffreyhanson** [comment]
Hi @ZMgogo,

Thanks for reaching out. I think this might be a duplicte of #285, could you please take a look at the potential solutions I mentioned there and see if any work for you?

**Comment by ZMgogo** [comment]
I used the old version of highs package. Thanks a lot for your reply. Great package, Cheers!

**Comment by jeffreyhanson** [comment]
Ok great - glad to hear its working now! Please let us know if you run into any more issues.
