### ISSUE TITLE
rij_matrix can return empty matrix when memory = TRUE 

### ISSUE THREAD

**Issue by edwardsmarc** [prioritizr/prioritizr#290]
If `memory = TRUE`, `rij_matrix` calculates the number of layers to process at once as `n_layers` using the following:

```
      n_layers <-
        ((40 * length(idx)) + (rep(1, terra::nlyr(y)) * length(idx) * 8))
      n_layers <- max(which(cumsum(n_layers) < (terra::free_RAM() * 0.45)))
      layer_ind <- parallel::splitIndices(
        terra::nlyr(y), ceiling(terra::nlyr(y) / n_layers)
      )
```

The line `n_layers <- max(which(cumsum(n_layers) < (terra::free_RAM() * 0.45)))` can return `-Inf` if all the values evaluated by `which()` are `FALSE` (i.e. if the RAM estimated for the first layer is greater than `free_RAM()`. This causes `layer_ind` to be an empty `list` so no rij values get added to the initialized empty matrix.

A proposed fix would be to fall back to an `n_layer` of `1` by using:
```
n_layers <- max(c(1,which(cumsum(n_layers) < (terra::free_RAM() * 0.45))))
```

**Comment by edwardsmarc** [comment]
@jeffreyhanson let me know if you want a PR for this proposed fix.

**Comment by jeffreyhanson** [comment]
Thank you very much for @edwardsmarc! Yeah, that makes perfect sense! I'm working on a PR to fix a couple of other issues, so I'll bundle this fix in with it as well.
