### ISSUE TITLE
Overly zealous assert causes spurious failure on problem(), breaking valid prioritizr 7.1.1  scripts

### ISSUE THREAD

**Issue by cboettig** [prioritizr/prioritizr#295]
Thanks for the awesome package and impressive engineering work here, it's much appreciated!

I noticed an inconsistency in the assertions that has inadvertently introduced a breaking change.  Note:

https://github.com/prioritizr/prioritizr/blob/ac1d7296adb17f7ef9c013d7a388f209768929af/R/problem.R#L863-L864

indicates that `features$name` can be either a character or a factor, but goes on to assert `is.vector()`  inside the `no_duplicates()` call: 

https://github.com/prioritizr/prioritizr/blob/ac1d7296adb17f7ef9c013d7a388f209768929af/R/assertions_vector.R#L87-L88

 This assertion to `is.vector()` will fail on the factor case, which (unlike character) is not a vector (it has attributes -- labels).  Either `no_duplicates()` needs to relax it's assertion about `is.vector()` or perhaps factors need to be coerced to characters?  The current implementation will break valid prioritizr code from 7.1.1 version due to this spurious assertion that factor-type name columns ought to pass `is.vector()`.  

I think a simple solution at least in the meantime is to merely drop line 88 in the no_duplicates or replace with a test that does not fail on factors.

**Comment by jeffreyhanson** [comment]
Hi @cboettig,

Thanks so much for reporting this and tracking down the cause!

I'll try and push a fix to GitHub later today. I'll let you know once that's done.

**Comment by jeffreyhanson** [comment]
I've just merged the fix into the main branch, so hopefully that should fix it. Please let me know if it's still persisting though, or if you run into any other issues?
