### ISSUE TITLE
high boundary penalties, but solution has weird hole

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#297]
I've found an issue with the recommended/documented procedures for rescaling boundary length data to avoid numerical issues during optimization. I would also like to thank @jflowernet and Joan Giménez Verdugo for bug reports that helped enormously with uncovering this issue.

Briefly, when creating a conservation planning problem with boundary penalties, we often need to rescale the boundary length data to avoid numerical issues. This is because the boundary length data often contain very high numbers (e.g., a planning unit might have a perimeter of 1,000,000 meters) and such large numbers can degrade solver performance (e.g., substantially increase run time). To avoid this, we had previously recommended that the best way to rescale the data was using the `scales::rescale()` function to linear rescale the non-zero values in boundary data (e.g., to between 0.01 and 100).  However, with recent changes to the boundary matrix data format in versions 8+ of prioritizr, this rescaling method produces unexpected behavior.

Here I'll provide a short reprex to illustrate the unexpected behavior. 

```
# load packages
library(prioritizr) # version 8.0.2
library(prioritizrdata)
library(sf)
library(terra)

# import data
salt_pu <- get_salt_pu()
salt_features <- get_salt_features()

# aggregate data to coarser resolution
salt_pu <- aggregate(salt_pu, fact = 3)
salt_features <- aggregate(salt_features, fact = 3)

# prepare boundary data using old method
salt_bm <- boundary_matrix(salt_pu)
salt_bm@x <- scales::rescale(salt_bm@x, to = c(0.01, 100))

# create problem formulation
## note that we use a high penalty value so we should get a high degree of spatial clustering
p <-
  problem(salt_pu, salt_features) %>%
  add_min_set_objective() %>%
  add_boundary_penalties(penalty = 100, data = salt_bm) %>%
  add_relative_targets(0.17) %>%
  add_binary_decisions() %>%
  add_gurobi_solver()

# generate solution
s <- solve(p)

# plot solution
plot(s)
```

![bad-sol](https://github.com/prioritizr/prioritizr/assets/3610005/90f1234c-cc83-40cd-8973-48305c950381)

We can see that the prioritization contains a few reserves (sets of clusetered selected planning units) and has a really big reserve in the bottom of the study area. Although we set a very high `penalty` factor -- which should result in high spatial clustering -- the bottom reserve has a hole in it (i.e., one of the planning units in the interior of the reserve wasn't selected). This is unexpected, because we would intuitively expect the optimization algorithm to "fill" in this hole to further reduce the total amount of exposed boundary length (i.e., the measure being penalized by the penalties).

The reason we are getting this weird behavior is due to the rescaling method (i.e., where we use `scales::rescale`). Specifically, this rescaling method introduces inconsistencies into the boundary data (e.g., the total perimeter of a planning unit might not  necessarily equal the sum of the edge lengths) that can, subsequently, cause issues/errors during optimization when calculating the total exposed boundary length of a given solution. To address this, we should use a different rescaling method.  Here's the current method I've come up with. It simply involves rescaling the boundary data by dividing it by a constant to ensure that the maximum value in the matrix is equal to certain value (e.g, 100 in the code below).

```
# prepare boundary data using new method
salt_bm <- boundary_matrix(salt_pu)
salt_bm@x <- salt_bm@x / (max(salt_bm@x) / 100)

# create problem formulation
## note that we use a high penalty value so we should get a high degree of spatial clustering
p <-
  problem(salt_pu, salt_features) %>%
  add_min_set_objective() %>%
  add_boundary_penalties(penalty = 100, data = salt_bm) %>%
  add_relative_targets(0.17) %>%
  add_binary_decisions() %>%
  add_gurobi_solver()

# generate solution
s <- solve(p)

# plot solution
plot(s)
```

![good-sol](https://github.com/prioritizr/prioritizr/assets/3610005/b978557f-1a89-4456-b841-d0405a2c6f03)

We can see that, when using this new method, the solution no longer has the hole in it. As such, I recommend using this new method to rescale the boundary data. Although you might notice that the optimization process now takes a lot longer, this can be mitigated by using a lower penalty value (e.g., `penalty = 1`) which will still produce a similar solution. In the above examples, I kept `penalty = 100` for both runs so that we can directly compare prioritizations generated  using different rescaling approaches and with everything else kept the same.

To help make the new method more accessible, I plan on creating a new `rescale_matrix()` function that can be used to linearly rescale the values in a matrix based on this new method. I also plan on updating the package documentation to use this new method/function so that users will encouraged to use this. Since this issue might impact a number of people, I will also put a short explanation of this issue in the NEWS file too.

@ricschuster, how does that sound to you? Can you think of any other package updates we should do to address this?

**Comment by ricschuster** [comment]
Thanks very much for investigating this and putting together this Issue @jeffreyhanson!

I think the approach you propose is great and I can't think any other updates we should do to address this.
