### ISSUE TITLE
Add linear constraints for multiple zones

### ISSUE THREAD

**Issue by Tegan151** [prioritizr/prioritizr#302]
Dear Jeff, 

I am currently running a prioritzR problem to zone 129 features into 5 zones of different uses. I would like to add linear constraints to the problem that forces the solution to retain a different percentage of each feature in each zone. Similar to the following code for a non-zone problem from your examples and retains at least 8% of each feature in the solution:

p2 <- p0
for (i in seq_len(terra::nlyr(sim_features))) {
  p2 <-
    p2 %>%
    add_linear_constraints(
      threshold = feat_abund[i] * 0.08,
      sense = ">=",
      data = sim_features[[i]]
    )
}

For example:
Here are my proportional targets for each zone for each feature:

![target](https://github.com/prioritizr/prioritizr/assets/8364648/5c9c061f-fb81-4f5a-92cb-5e878646044b)

I would now like to add a constraint that keeps at least 10% of the target I set in the table within the solution.
I created a table that multiples the 'abundance' of each feature (calculated using feat_abund <- feature_abundances(p0)$absolute_abundance) by the zone target I set and by 10% to get a threshold value to code into the add_linear_constraint function.

However, I am unsure of how to code these threshold values into the add_linear_constraints function? The add_linear_constraints function does not allow more than one value to be set as a threshold. 

I apologise if the format of my question is not correct, this is my first time posting on GitHub. And I thank you and your team for all the great documentation you prepared for your R package!

Warm Regards,
Tegan
tegan.carpenterkling@gmail.com

**Comment by jeffreyhanson** [comment]
Hi @Tegan151,

Thanks for reaching out! If I understand the question correctly, you're asking how to specify targets for each feature within each zone using the `add_linear_constraints()` function? 

Here's a short example using the min shortfall objective. I'm assuming that you're using a budget limited objective function, because this wouldn't really have any effect for the min set formulation (unless the secondary set of target, below `min_targets`, are greater than the targets set using `add_relative_targets()`/`add_manual_targets()`/add_absolute_targets()`). What do you think? Does this help? Let me know if I've misunderstood the question, if you have any follow up questions, or if the example below doesn't really work for your problem?

```
# load packages
library(prioritizr)
library(terra)
library(tibble)
library(tidyr)
library(dplyr)

# import data for 3 zone problem
sim_zones_pu_raster <- get_sim_zones_pu_raster()
sim_zones_features <- get_sim_zones_features()

# create matrix with ideal targets for each species in each zone,
# these specify the amount that we would ideally want
n_values <- 
  number_of_zones(sim_zones_features) * 
  number_of_features(sim_zones_features)
ideal_targets <- matrix(
  runif(n_values, 0.5, 0.7), 
  ncol = number_of_zones(sim_zones_features), 
  nrow = number_of_features(sim_zones_features)
)
colnames(ideal_targets) <- zone_names(sim_zones_features)
rownames(ideal_targets) <- feature_names(sim_zones_features)

# create matrix with minimum targets for each species in each zone,
# these ensure that each species has at least some minimum amount
# within each zone 
# (note this would have no effect in a min set problem)
min_targets <- matrix(
  runif(n_values, 0.1, 0.2), 
  ncol = number_of_zones(sim_zones_features), 
  nrow = number_of_features(sim_zones_features)
)
colnames(min_targets) <- zone_names(sim_zones_features)
rownames(min_targets) <- feature_names(sim_zones_features)

# calculate budget for prioritization
## here the budget will be 50% of the total planning unit costs for each zone
budget <- global(sim_zones_pu_raster, "sum", na.rm = TRUE)[[1]] * 0.5

# create problem formulation
## initialize problem formulation
p <-
  problem(sim_zones_pu_raster, sim_zones_features) %>%
  add_min_shortfall_objective(budget) %>%
  add_relative_targets(ideal_targets) %>%
  add_binary_decisions()

## add in min targets
### calculate feature abundances for each zone
feature_abd <- feature_abundances(p)

### add in min targets
for (z in zone_names(sim_zones_features)) {
  for (f in feature_names(sim_zones_features)) {
    #### initialization
    z_idx <- which(zone_names(sim_zones_features) == z)
    f_idx <- which(feature_names(sim_zones_features) == f)
    #### extract min target for feature f in zone z
    curr_min_target <- min_targets[f, z]
    #### extract abundance for feature f in zone z
    idx <- which(feature_abd$zone == z & feature_abd$feature == f)
    curr_abd <- feature_abd$absolute_abundance[[idx]]
    #### prepare raster data
    curr_data <- lapply(
      seq_len(number_of_zones(sim_zones_features)),
      function(i) {
        #### if i'th zone is the same as z, 
        #### then return the layer with the feature datra
        if (i == z_idx) return(sim_zones_features[[i]][[f_idx]])
        #### otherwise, return an empty raster so that only
        #### the z'th zone can help meet the targets
        sim_zones_features[[i]][[f_idx]] * 0 # return 
      }
    )
    #### add threshold
    p <- 
      p %>%
      add_linear_constraints(
        data = rast(curr_data),
        sense = ">=",
        threshold = curr_abd * curr_min_target
      )
  }
}

# print problem
print(p)

# solve problem
s <- solve(p)

# calculate feature representation
fr <- eval_feature_representation_summary(p, s)

# check that feature representation exceeds the min targets
## convert min targets to data.frame form
min_targets_df <-
  min_targets %>%
  as.data.frame() %>%
  mutate(feature = rownames(min_targets)) %>%
  gather(zone, min_target, -feature) %>%
  arrange(zone, feature)

## add in the targets to the feature representation table
fr <-
  fr %>%
  left_join(min_targets_df, by = c("summary" = "zone", "feature" = "feature"))

## check that all min targets met
print(all(fr$relative_held >= fr$min_target, na.rm = TRUE))
 ```

**Comment by Tegan151** [comment]
Thank you so much, Jeff! Both for your answer and how quickly you responded to me. 

This is exactly what I want to do. 

Warmest,
Tegan

**Comment by jeffreyhanson** [comment]
No worries! Happy to help. If you don't have any follow up questions on this topic, shall we close this issue?
