### ISSUE TITLE
ℹ In argument to `x`. Caused by `problems(pu, features = multi_layer)`

### ISSUE THREAD

**Issue by wk-ai** [prioritizr/prioritizr#311]
inpath<-'E:/literature/pu/'
> multi_layer<-rast(paste0(inpath,'feature_com.tif'))
> print(multi_layer)
class       : SpatRaster 
dimensions  : 4044, 4845, 11  (nrow, ncol, nlyr)
resolution  : 1000, 1000  (x, y)
extent      : -2637867, 2207133, 1877283, 5921283  (xmin, xmax, ymin, ymax)
coord. ref. : Krasovsky_1940_Albers 
source      : feature_com.tif 
names       : featu~com_1, featu~com_2, featu~com_3, featu~com_4, featu~com_5, featu~com_6, ... 
min values  :        0.00,       0.000,        0.00,           0,           0,           0, ... 
max values  :    11203.96,    4001.413,    21927.06,      298776,      896328,      149388, ... 
> pu <- glue("interact.tif") %>% 
+   path("test", .) %>% 
+   rast()
> ######################################
> p0 <- problems(pu, features = multi_layer)%>%
+   add_min_set_objective()%>%
+   add_binary_decisions()%>%
+   add_gurobi_solver(verbose = FALSE)
Error in `add_min_set_objective()`:
ℹ In argument to `x`.
Caused by `problems(pu, features = multi_layer)`:
! unused argument(features = multi_layer)
Run `rlang::last_trace()` to see where the error occurred.
> plot(pu)
> print(pu)
class       : SpatRaster 
dimensions  : 4044, 4845, 1  (nrow, ncol, nlyr)
resolution  : 1000, 1000  (x, y)
extent      : -2637867, 2207133, 1877283, 5921283  (xmin, xmax, ymin, ymax)
coord. ref. : Krasovsky_1940_Albers 
source      : interact.tif 
name        : interact 
min value   :        1 
max value   :        1 

I really do not konw how to solve the problem, help!!

**Comment by jeffreyhanson** [comment]
Hi @wk-ai,

It looks like there might be a typo. It seems you have `problems` instead of `problem`. Also, the min set objective requires targets - so you'll need to add some targets (e.g., using `add_relative_targets()`, though there's also other options). Could you please try this and see it works?

```
p0 <- 
  problems(pu, features = multi_layer)%>%
  add_min_set_objective()%>%
  add_relative_targets(0.2) %>%
  add_binary_decisions()%>%
  add_gurobi_solver(verbose = FALSE)
```

**Comment by wk-ai** [comment]
> Hi @wk-ai,
> 
> It looks like there might be a typo. It seems you have `problems` instead of `problem`. Also, the min set objective requires targets - so you'll need to add some targets (e.g., using `add_relative_targets()`, though there's also other options). Could you please try this and see it works?
> 
> ```
> p0 <- 
>   problems(pu, features = multi_layer)%>%
>   add_min_set_objective()%>%
>   add_relative_targets(0.2) %>%
>   add_binary_decisions()%>%
>   add_gurobi_solver(verbose = FALSE)
> ```

Thanks for your reply! But I really do not know how to solve the problems, maybe the PU file need to  be further corrected.

**Comment by jeffreyhanson** [comment]
Sorry, there was a typo in my repsonse! 

The code block should be:

```
p0 <- 
  problem(pu, features = multi_layer)%>%
  add_min_set_objective()%>%
  add_relative_targets(0.2) %>%
  add_binary_decisions()%>%
  add_gurobi_solver(verbose = FALSE)
```

After creating a problem, you can solve it using the `solve()` function. E.g., like this:

```
s0 <- solve(p0)
```

Also, just in case you're not aware, this tutorial might be helpful: https://prioritizr.net/articles/prioritizr.html.

Let me know if you have any further questions?

**Comment by wk-ai** [comment]
> Sorry, there was a typo in my repsonse!
> 
> The code block should be:
> 
> ```
> p0 <- 
>   problem(pu, features = multi_layer)%>%
>   add_min_set_objective()%>%
>   add_relative_targets(0.2) %>%
>   add_binary_decisions()%>%
>   add_gurobi_solver(verbose = FALSE)
> ```
> 
> After creating a problem, you can solve it using the `solve()` function. E.g., like this:
> 
> ```
> s0 <- solve(p0)
> ```
> 
> Also, just in case you're not aware, this tutorial might be helpful: https://prioritizr.net/articles/prioritizr.html.
> 
> Let me know if you have any further questions?

My God!!!!! Thank you!!

**Comment by jeffreyhanson** [comment]
Sorry, I forgot to reply. No worries - glad to help! Did you have any other questions? If not, shall we close this issue?

**Comment by wk-ai** [comment]
Opps!! Sorry, I don't check the mail in time. I don't have any other questions at the moment.



At 2024-02-09 04:34:20, "Jeff Hanson" ***@***.***> wrote:

Sorry, I forgot to reply. No worries - glad to help! Did you have any other questions? If not, shall we close this issue?

**Comment by jeffreyhanson** [comment]
No worries! Thanks for letting me know.
