### ISSUE TITLE
Ph.D.

### ISSUE THREAD

**Issue by monodendri** [prioritizr/prioritizr#314]
Ph.D. Clinical Psychologist, Adjunct Lecturer

**Comment by jeffreyhanson** [comment]
Hi @monodendri, 

I think there might have been a problem with posting your issue/bug report/query? All I can see is your email signature (I think?). Could you please try posting it again?

**Comment by jeffreyhanson** [comment]
I'll close this issue due to lack of activity, but please feel free to re-open this issue or open a new issue if you have any questions.
