### ISSUE TITLE
Cost in problems with zones

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#317]
Hi Jeff,
I've just started playing around with zones, so apologies if this is a very basic question. In the case where you have different cost data used for each zone, how does prioritizr go about minimizing cost within each zone vs. the total cost across all zones? 

I realised that when I had very unequal cost data, e.g. sum of the cost data used for zone 1 is much greater than the sum for zone 2, I was ending up with a much greater total planning area and cost in the solution for zone 2. I presume this is a consequence of the algorithm trying to minimize total cost across all zones, and since costs are much higher in zone 1, it minimizes cost in that zone preferentially?

Many thanks in advance!

**Comment by jeffreyhanson** [comment]
Hi,

Yeah, with the min set objective, prioritizr minimizes the overall costs across all zones. This means all the costs are assumed to be in the same units or comparable (i.e., one cost unit for one zone is equivalent to one cost unit in another zone).  So if you have one zone that generally has much lower costs than another zone, then -- all else being equal -- we might expect more planning units to be allocated to the cheaper zone. That said, there are ways to ensure that you get adequate coverage for different zones---even when different zones have very different cost ranges. For example, you can use zone-specific targets to ensure that certain zones meet target adequately represent certain features. You can also use linear constraints to limit the total area associated with a zone (see #307). Also, if using budget-limited objecitves, you can set zone-specific budgets to ensure the total cost associated with a given zone does not exceed a particular budget. Does that help?

**Comment by jflowernet** [comment]
Excellent, thanks that answers my question! And yep, I think I will be experimenting with some zone specific targets and linear constraints to get the best outcomes.
Thanks again!
