### ISSUE TITLE
Return the optimality gap of a solution

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#323]
I can't remember if we already discussed this, so apologies if we did and the answer was 'it's not possible'!

I often solve multiple problems in a loop, saving each solution. When I use the `time_limit` parameter in `add_gurobi_solver()` the solution might not solve to the optimality gap specified it it runs out of time before reaching that gap. The optimality gap outputs to the console, but I wonder if it's possible to return the value as well, to avoid having to go through long console outputs to find optimality gaps for all solutions? It seems like it is possible to return a value from Gurobi using [MIPGap](https://www.gurobi.com/documentation/current/refman/mipgap.html), though I don't know if there exists something equivalent for other solvers. I guess the bigger problem is, what do you return the gap to since the output from `solve()` is just the solution as e.g. a raster or sf object. One option would be to return a list with the solution as the first element and the gap as second, but this makes for a messier returned object.

Just a thought, and totally understand that this might not be practical.

**Comment by jeffreyhanson** [comment]
Hi,

Yeah, you're right, prioritizr doesn't currently report this information and it looks like it might possible for Gurobi at least (using the mipgap attribute). I'll take a look and see what I can do.

**Comment by jeffreyhanson** [comment]
Also, in terms of storing this information, prioritizr uses attributes to append additional information to the output of `solve()` (e.g., objective value, solver status, run time). E.g., see the first example in the `solve()` docs (https://prioritizr.net/reference/solve.html#ref-examples). So it would be pretty straightforward (in theory) to use this same mechanism to ouput the optimality gap for a solution.

**Comment by jflowernet** [comment]
Ah yes, I'd forgotten the attributes that are added. 
Thanks for considering this!

**Comment by jeffreyhanson** [comment]
Just to follow up, I've merged a PR to the main branch that adds this functionality. After generating a solution (e.g., called `s`), you can use `attr(s, "gap")` to extract the gap value. Note that if gap informmation is not available (e.g., due to run time limits, or because the solver doesn't support this functionality, currently only Gurobi and HiGHS solvers support this) than this will return a missing value.

**Comment by jflowernet** [comment]
Thanks very much for this Jeff! I just gave it a try and works perfectly.

**Comment by jeffreyhanson** [comment]
Awesome - thanks for trying it out!
