### ISSUE TITLE
Infeasible model - seemingly from negative feature values

### ISSUE THREAD

**Issue by hannahmp** [prioritizr/prioritizr#334]
Hello! 

First of all, thank you for this package and the detailed documentation! 

I have encountered an issue where my problem does not solve if the feature data includes negative values. Below, I explain the aim and setup of my problem, describe the issue, and outline the steps I have taken so far to identify the problem.

**Problem and data description**

The goal is to prioritise habitats for restoration in Europe, aiming to increase the local viability or probability of survival for terrestrial mammals with range maps that overlap the continent.

 I used the Jung et al. (2020) maps of IUCN level 1 habitat classifications (level 2 for artificial categories), and Jung’s potential habitat map to create two maps: one of  current habitats and another (hypothetical) map where artificial habitats are ‘restored’ to their potential habitat type. Using species habitat and elevation preferences (from the IUCN), I clipped the species’ range maps  to create area of habitat (AOH) maps for both current and restored scenarios. The difference between these maps provides the potential habitat gain per species in each planning unit if restoration were to occur. 

I then calculate the local viability of each species with the formula: `(current_AOH/potential_AOH)^0.25)`, where `z = 0.25` (though `z` could take a different value between 0 and 1). This approach, though imperfect, is inspired by Strassburg et al. (2019, 2020) and Durán et al. (2020). The implied biodiversity index is the arithmetic sum of local viability across all species considered. Additionally, I calculate the marginal benefit of one additional unit of habitat (in km^2) for each species: `(0.25 * (1/current_AOH^(1 - 0.25)) * (1/potential_AOH^(0.25)))`. 

The opportunity cost of land, taken from Spencer et al. (2024), constitutes the cost layer. 

The aim is to maximise biodiversity gain, subject to a budget constraint, where the gain is quantified by the change in viability due to AOH change, summed across all species. Selecting planning units for restoration changes the marginal benefits, requiring the problem to be solved in multiple steps, updating the marginals after each solution. 

**Set up**

I am creating this problem using data tables, as follows: 

```
p0 <- problem(prioritisation_cost_dt, crosswalk, cost_column = "cost", rij = prioritisation_potential_dt_melted) 

# investigate total cost to consider useful budget. 
total_cost <- prioritisation_cost_dt[ , sum(cost)]
total_cost # 6386.491 billion EUR per year 

p1 <- p0 %>%
  add_max_utility_objective(budget = 1000) %>% # 1 billion (cost units: million EUR/pu/year)
  add_feature_weights(marginal_benefit_weights_0.25_vector)
```

**Issue**

I receive a warning that (some) features have negative values. This is expected since some species might loose habitat if a planning unit is restored (e.g., species living on agricultural land but not in forests). These negative feature values are necessary to accurately represent the scenario, I think.

The problem passes the `presolve_check()`, but when attempting to `solve()`, I get an error stating  the model is infeasible. This is the output: 

```
> # ----- initialise problem -----
> # base problem - just loading data really 
> p0 <- problem(prioritisation_cost_dt, crosswalk, cost_column = "cost", rij = prioritisation_potential_dt_melted) 
Warning: `rij$amount` has negative values.
> # investigate total cost to consider useful budget. 
> total_cost <- prioritisation_cost_dt[ , sum(cost)]
> total_cost # 6386.491 billion EUR per year 
[1] 6386491
> p1 <- p0 %>%
+   add_max_utility_objective(budget = 1000) %>% # this is a budget of 1000 * 1,000,000 = 1 billion
+   add_feature_weights(marginal_benefit_weights_0.25_vector)
> # solve
> presolve_check(p1)
[1] TRUE
> s1 <- solve(p1)
Set parameter Username
Set parameter TimeLimit to value 2147483647
Set parameter MIPGap to value 0.1
Set parameter Presolve to value 2
Set parameter Threads to value 1
Academic license - for non-commercial use only - expires 2025-07-04
Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 21.6.0 21H1123)

CPU model: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
Thread count: 2 physical cores, 4 logical processors, using up to 1 threads

Optimize a model with 152 rows, 126069 columns and 4946622 nonzeros
Model fingerprint: 0x7cce09d7
Variable types: 151 continuous, 125918 integer (125918 binary)
Coefficient statistics:
  Matrix range     [6e-06, 1e+03]
  Objective range  [9e-15, 1e+05]
  Bounds range     [1e+00, 3e+06]
  RHS range        [1e+03, 1e+03]
Presolve removed 3 rows and 12 columns
Presolve time: 0.40s

Explored 0 nodes (0 simplex iterations) in 0.50 seconds (0.14 work units)
Thread count was 1 (of 4 available processors)

Solution count 0
No other solutions better than -1e+100

Model is infeasible
Best objective -, best bound -, gap -
Error in `solve()`:
! Can't find a solution!
ℹ This is because it is impossible to meet the targets, budgets, or constraints.
Run `rlang::last_trace()` to see where the error occurred.
> 
```

**Unappealing solutions**

The problem can be solved if I filter out rows with negative (feature) `amount` in my `rij` object, but this does not strike me as desirable. I also tried using raster data, but the same issue occurred: errors with negative values, no errors when these were set to zero.  Disregarding all cells where any species would be negatively affected would eliminate about 90% of planning units, which is not useful. 

A colleague of mine is using similar approach to study the Colombian Andes, and is encountering the same error when negative features are included and also able to solve the problem when not. 

Is there something we are missing or should consider? Would setting up the problem directly using the Gurobi package circumvent this issue? (I am not all too familiar with linear programming, so find the grammar of prioritizr particularly helpful.) 

Apologies for the lengthy explanation; I hope the context helps. Thank you for any advice! 

Best wishes, 
Hannah

**Comment by jeffreyhanson** [comment]
Hi,

Thanks so much for reaching out @hannahmp! I'm sorry, I'm a bit busy for the next couple of days, but I'll try and respond as soon as I can. 

Briefly, it sounds like there might some bug in max utility that's preventing it from working with the negative values (it should work with negative values) - I'll look into it that when I can. I'll provide more details later, but I would generally suggest approaching this as a multiple zones problem (e.g., with zones related to "keeping current habitat" and "restoring habitat"). This way you can set targets to try provide each and every species with an adeqaute amount of habitat. If focussing on some measure of species richness, this might cause problems with complementarity (e.g., see https://doi.org/10.1073/pnas.1509189112) -- where the prioritization might focus on (i) restoring areas that contain habitat types that contain more species (e.g., if forests have higher species richness then deserts, then the prioritization might only focus on forests and ignore deserts) , or (ii) restoring areas that contain taxa that end to contain more species (e.g., if there aremore bird then reptile species, then the prioritization might focus only on potential bird species hotspots and ignore reptiles). Sorry if this explanation doesn't have enough detail - I'll try and explain in more detail when I get a chance.

**Comment by hannahmp** [comment]
Hi, 

Thank you so much for your quick response @jeffreyhanson! 

The point about needing to be careful with species richness measures is well taken, thank you. The idea was to circumvent the issue to some extent by taking the marginal of the probability of (local) survival as weight per species, such that those with relatively less habitat receive greater weights. I'll also explore zones and the alternative objectives, however.

Just to note, we were able to implement a version of this problem using the gurobi package directly, including negative values, and it didn't cause any issues when solving. We each used the same underlying data, so it does seem as though there might be an issue with the function. 

Thanks again!

**Comment by jeffreyhanson** [comment]
Sorry I wasn't able to provide more details earlier. I just wanted to follow up and ask how the prioritizations are going and if you had any further questions? Were you able to get a multiple zones version of the analysis running?

**Comment by hannahmp** [comment]
Hi @jeffreyhanson - thank you so much for addressing the issue and the follow-up. 

We ended up altering our method for other reasons, so that we are no longer using an optimisation algorithm after all. Hence we haven't explored the multiple zones just yet. I'm happy to close this issue from my side. 

Thank you again!
