### ISSUE TITLE
testthat version update

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#34]
I received an automated email notifying me that a new version of the _testthat R_ package will be made available on CRAN on November 13th. Apparently, the new version will change the behaviour of _testthat's_ functions such that code that currently works will fail upon the release of the new version. As a consequence, the unit tests in _prioritizr_ will need to be rewritten to be compatible with the new version of _testthat_. Also, we should probably hold off on submitting _prioritizr_ to CRAN until the new version of _testthat_ is on CRAN to avoid having to do multiple submission in a short period of time.

**Comment by ricschuster** [comment]
Thanks for bringing this up Jeff. I'm happy to hold off with submitting `prioritizr` until the new version of testthat is out and `prioritizr` is rewritten.
