### ISSUE TITLE
Equations not rendering correctly in html

### ISSUE THREAD

**Issue by jaseeverett** [prioritizr/prioritizr#344]
@jeffreyhanson @sandra-neubert 

When I look at the pkgdown site in Chrome and Safari on MacOS, the equations are not rendered. 

![Screenshot 2024-09-30 at 09 45 49](https://github.com/user-attachments/assets/a5014499-a014-4d5d-b558-cfe21d95ad70)

I think you have hit upon this [issue](https://github.com/r-lib/pkgdown/issues/2704) when you updated to `pkgdown 2.1.0` in [PR #366](https://github.com/prioritizr/prioritizr/pull/336)

Currently I think the solutions are to downgrade to `pkgdown 2.0.9` or include `  math-rendering: mathjax` in the `pkgdown.yml`
```
template:
  bootstrap: 5
  math-rendering: mathjax
```

Thanks to @ric325 for highlighting this first

**Comment by jeffreyhanson** [comment]
Thanks very much @jaseeverett abnd @ric325! I'll look into the suggested fixes and see what I can do.

**Comment by ric325** [comment]
Thx Jeff

From: Jeff Hanson ***@***.***>
Reply to: prioritizr/prioritizr ***@***.***>
Date: Monday 30 September 2024 at 10:56 am
To: prioritizr/prioritizr ***@***.***>
Cc: Anthony Richardson ***@***.***>, Mention ***@***.***>
Subject: Re: [prioritizr/prioritizr] Equations not rendering correctly in html (Issue #344)


Thanks very much for reporting this @jaseeverett<https://github.com/jaseeverett> abnd @ric325<https://github.com/ric325>! I'll look into the suggested fixes and see what I can do.
