### ISSUE TITLE
publication record [documentation proposal]

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#35]
Hi,

I was wondering if it would be worth keeping a record of all the publications that use _prioritizr_? This could be a useful resource for users, and for promotional purposes in the future. 

If you think it would be useful, how do you think this record should be organised? Should it be a vignette available in the package? This has the advantage of it easily being incorporated into the package's website. A wiki page on the GitHub repository? This has the advantage of being more easily editable by other people. 

Thoughts?

**Comment by ricschuster** [comment]
I think this is a great idea.

As for how this should be organized: I'm not sure about the best way to do this. I think at least for now a vignette might be good, as it will be us adding publications I assume. Over time maybe (also) a wiki page, but I think for now vignette would be good.

**Comment by jflowernet** [comment]
Yes, strongly agree that this would be excellent to have. And agree with @ricschuster that a vignette is good for now, though wiki would be good in future. I think this will be a good resource for people like me who want to see how people have used prioritizr in different locations and scenarios. 
Thanks!

**Comment by jeffreyhanson** [comment]
Ok - sounds like a plan. I've just added the new vignette to the package, with a new paper by @DanRosauer that used some of the phylogenetic functionality. I can't think of any other publications that use _prioritizr_, so feel free to add them or post them in a new issue.

**Comment by ricschuster** [comment]
Nothing out yet, but I will be submitting a paper using prioritizr in hopefully less than a month.
