### ISSUE TITLE
Logo link broken

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#36]
Looks like the prioritizr logo file has disappeared. Any chance we could get it back - I'd like to include it in a conference talk I'm giving next week!

**Comment by ricschuster** [comment]
Hi Jason,

You should be able to download the logo from here [https://github.com/prioritizr/logo](url)

**Comment by ricschuster** [comment]
Hi Jason,

You should be able to download the logo from here: https://github.com/prioritizr/logo

**Comment by jflowernet** [comment]
Many thanks @ricschuster!
