### ISSUE TITLE
Optimization software

### ISSUE THREAD

**Issue by momeni133** [prioritizr/prioritizr#39]
Hello All
I tried to get an academic license for Gurobi, but because our institute is a research center and is not a university the company disagreed with my request. 
On the other hand, I tried to use Symphony software instead of Gurobi but it seems very very slow for me.
Do you have any suggestions to solve the problem? Do you know any other optimization core to use?

Best regards
Iman

**Comment by jeffreyhanson** [comment]
Yeah that's a limitation with _prioritizr_, it really needs _Gurobi_ to be installed to tackle large problems. 

If you want to try using _prioritizr_ without _Gurobi_, I would recommend trying it with the _lpsymphony_ solver, since it can use multiple cores on some systems to reduce run time, using proportion decision variables, and keeping the problem as simple as possible (eg. no boundary penalties).

**Comment by ricschuster** [comment]
Hi Iman,

What's the size of your conservation problem (number of planning units and features)?
What system are you on (Win, Mac, Linux plus details)?

**Comment by momeni133** [comment]
Dear Jeffrey
Thank you for your answer. I'll try lpsymphony solver and will inform you about it.


Dear Richard, I'll try with 100,000 and 1,000,000 PUs. 
I'm using windows 64b as an operating system but I can also install the Linux on my computer.
CPU is: Core i7 6700hq
RAM is: 24 Gb ddr4

**Comment by momeni133** [comment]
Dear Jeffrey
Below is comparison of rsymphony and lpsymphony on same system and same time:
time: 360 s
Done by rsymphony = 689729
Done by lpsymphony = 505953

**Comment by ricschuster** [comment]
Thanks Iman. With that many pu's Symphony is really sluggish compared to Gurobi. That being said its still faster than Marxan. 

Using Linux you might be able to take advantage of more than just the one core that Windows will use for solving the conservation problems.

As Jeff mentioned, the speed of open source solver compared to Gurobi is a current limitation of prioritzr, but hopefully this will change over time as open source solvers get more efficient.

**Comment by momeni133** [comment]
Dear Richard
So if I run the prioritzr on linux using rsymphony or lpsymphony it will use multi-core automatically. Am I right?
when I ran it on windows I think it used multi core also.

**Comment by ricschuster** [comment]
I'm not sure, but would think that you would get multi-core use in Linux 'automatically'.
As for multi-core use on Windows, this is still not very common and usually requires user effort.
