### ISSUE TITLE
specifying time limit for the solver

### ISSUE THREAD

**Issue by momeni133** [prioritizr/prioritizr#42]
Dear prioritizr users and developers
Could you please help me to find the method to specify a good “time limit” when the solver is trying to generate a solution?
When I don’t define this time limit, even with a small number of planning units (tutorial), after a long time the solver couldn’t reach to the optimum solution. But I don’t know how much time is enough for the solver, 10 min, 100 min or 1000 min?
  
Best regards
Iman

**Comment by mstrimas** [comment]
Hi Iman,

Do you have access to Gurobi, or are you using one of the open source solvers (lpsymphony or Rsymphony)?

Also, you say the examples from the tutorial are taking a long time to run. Regardless of which solver you're using, these simple examples should only take a couple seconds to run. For example, this comes from the tutorial and runs quite quickly for me:

```
library(prioritizr)
p4 <- problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>% 
  add_boundary_penalties(penalty = 500, edge_factor = 0.5) %>% 
  add_gurobi_solver()
solve(p4)
```

Can you share some code for one of these simple examples that are taking a long time for you?

**Comment by momeni133** [comment]
Dear Matt
Thank you for your answer. 
I used Rsymphony in blow script. After 2h I didn't receive any answers.

library(prioritizr)
data(sim_pu_polygons)
data(sim_features)
p1 <- problem(sim_pu_polygons, features = sim_features,
              cost_column = "cost") %>%
      add_min_set_objective() %>%
      add_relative_targets(0.2) %>%
      add_binary_decisions()
s <- p1 %>% add_rsymphony_solver() %>%
             solve()

**Comment by momeni133** [comment]
Dear Richard
Thank you for your answer,
Yes, I know how to set time limit. I don't know how much time will be enough. this is my problem.

**Comment by ricschuster** [comment]
There is no perfect answer to this question I'm afraid. It will depend on your data and problem.

You could try `first_feasible` for a start, but that would only work for smallish problems I think.

For the example you used its pretty good though:

```library(prioritizr)
data(sim_pu_polygons)
data(sim_features)

p1 <- problem(sim_pu_polygons, features = sim_features,
cost_column = "cost") %>%
add_min_set_objective() %>%
add_relative_targets(0.2) %>%
add_binary_decisions() %>%
add_rsymphony_solver(first_feasible = 1)

s1 <- solve(p1)


p2 <- problem(sim_pu_polygons, features = sim_features,
cost_column = "cost") %>%
add_min_set_objective() %>%
add_relative_targets(0.2) %>%
add_binary_decisions() %>%
add_gurobi_solver

s2 <- solve(p2)

table(s1$solution_1 == s2$solution_1)

#FALSE  TRUE 
#   4    86 
```

I did notice though that specifying gap for `add_rsymphony_solver` has an issue though (can't use values >1)

**Comment by momeni133** [comment]
![prioritz](https://user-images.githubusercontent.com/33343341/32624356-508acc84-c589-11e7-93db-24008f4050fd.jpg)

For only 90 planning units, after 12576s, still working!! It seems multi-cores are also working. :(

**Comment by jeffreyhanson** [comment]
I'm not sure if that does mean that multiple-cores are working, if the solver was using all the cores on your system I would expect the CPU usage to be much higher than 14 %. So, I think this does confirm that _Rsymphony_ will only use 1 core on Windows.

**Comment by momeni133** [comment]
Dear Jeffrey
I tested the package on Linux. It found the solution in less than 1 sec!
