### ISSUE TITLE
Edge factor error

### ISSUE THREAD

**Issue by momeni133** [prioritizr/prioritizr#43]
Dear prioritizr users and developers
I want to test different BLM values. When I tested the below script I received an error: “Error in isTRUE(all(is.finite(edge_factor))) : argument "edge_factor" is missing, with no default”
In the reference webpage (https://prioritizr.github.io/prioritizr/reference/) I didn’t find how to define edge factor.
Could you please help me to solve the problem?
  
Best regards
Iman

Script:
# load data
data(sim_pu_raster, sim_features)
 
# create base problem
p <- problem(sim_pu_raster, sim_features) %>%
     add_min_set_objective() %>%
     add_relative_targets(0.1) %>%
     add_binary_decisions()
 
# define blms
blms <- c(0.001, 0.1, 1, 10)
 
# create a list with the solutions
results <- lapply(blms, function(x) {
     p %>% add_boundary_penalties(x) %>% solve()
})

**Comment by mstrimas** [comment]
Hi Iman,

`edge_factor` is an argument to [add_boundary_penalty()](https://prioritizr.github.io/prioritizr/reference/add_boundary_penalties.html) and is defined in the help for that function: 

> proportion to scale edges that do not have any neighboring planning units. For example, an edge factor of 0.5 is commonly used for planning units along the coast line.

If `edge_factor` wasn't used, or is set to 1, planning units with external edges (e.g. coastline) will be disfavored because these edges can never be removed by adding a neighboring planning unit.  

Use it as follows:

```
p %>% add_boundary_penalties(x, edge_factor = 0.5) %>% solve()
```

**Comment by momeni133** [comment]
Dear Matt
Thanks!
Now I can run it without any problems.
So this value should be between 0 to 1? 
How to find a suitable value?

**Comment by mstrimas** [comment]
Yes, this value should be between 0 (don't count external edges at all) and 1 (count external edges the same as internal ones). 0.5 is a typical value, but you could try a sensitivity analysis, i.e. run for a few values and see if planning units on the edges are being over or under selected relative to internal ones.
