### ISSUE TITLE
add_rsymphony_solver gap > 1 error

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#44]
When trying to use a gap > 1 `add_rsymphony_solver` throws an error, but according to the [help page](https://prioritizr.github.io/prioritizr/reference/add_rsymphony_solver.html) users should be allowed to specify gaps > 0 for this solver:
_But for other solvers (e.g. Rsymhpony), this gap is absolute and expresses the acceptable deviance from the optimal objective. For example, solving a minimum set objective problem with a gap of 5 will cause the solver to terminate when the cost of the solution is within 5 cost units from the optimal solution._

```
library(prioritizr)
data(sim_pu_polygons)
data(sim_features)

p1 <- problem(sim_pu_polygons, features = sim_features,
cost_column = "cost") %>%
add_min_set_objective() %>%
add_relative_targets(0.2) %>%
add_binary_decisions() %>%
add_rsymphony_solver(gap = 2)

# Error: isTRUE(x = gap <= 1) is not TRUE
```

**Comment by mstrimas** [comment]
Also, the following:

> a gap of 5 will cause the solver to terminate when the cost of the solution is within 5 cost units from the optimal solution.

Would more correctly be expressed with "cost" replaced by "objective function", which reduces cost in the simple case of a minimum set cover problem with no boundary term.

**Comment by momeni133** [comment]
![prioritz](https://user-images.githubusercontent.com/33343341/32624153-b2f058b8-c588-11e7-8df8-2b748c837d47.jpg)

For 90 Planning units after 12576s, still working. Please see above image. I think multi-core are working!
