### ISSUE TITLE
prioritizr / gurobi uses only one thread

### ISSUE THREAD

**Issue by domisch** [prioritizr/prioritizr#46]
Dear prioritizr-team,
I'm running a Marxan problem using Gurobi on a Linux VM with 32 cores. I've read that Gurobi should use all available resources automatically, but apparently only one thread is used (as printed in the console and also shown in the system monitor, and thus solving the problem takes a very long time). Is there a way I could specify the number of threads? Below is the code I use (and I've sent the data to Jeff in a previous email a while ago), but the problem also persists when using the examples from the manual/vignette.
Thanks a lot in advance, Sami

mp02 <- marxan_problem(x = pu, spec = spec_02, puvspr = puvspr, bound = bound, blm = 0.3, 
                        asymmetric_connectivity=T, add_gurobi_solver)
ms_02 <- solve(mp02)

Console output:
Optimize a model with 715517 rows, 365092 columns and 1646043 nonzeros
Variable types: 0 continuous, 365092 integer (365092 binary)
Coefficient statistics:
  Matrix range     [2e-03, 1e+00]
  Objective range  [6e-05, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+01, 2e+03]
.....
Explored 1 nodes (704823 simplex iterations) in 42843.74 seconds
Thread count was 1 (of 32 available processors)

**Comment by mstrimas** [comment]
Hi,

You'll need to use the `threads` argument of `add_gurobi_solver()`:

```
library(prioritizr)
p <- problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions() %>% 
  add_gurobi_solver(threads = 6)
solve(p)
```

**Comment by domisch** [comment]
Thanks a lot, I must have missed that one. Works perfectly!
