### ISSUE TITLE
Saving and loading problem object 

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#47]
Creating and saving a problem object:

```
library(prioritizr)
p1 <- problem(sim_pu_polygons, features = sim_features,
              cost_column = "cost") %>%
      add_min_set_objective() %>%
      add_relative_targets(0.2) %>%
      add_binary_decisions()
save.image("temp.RData")
```

Subsequently quitting the R session and opening a new one:

```
library(prioritizr)
load("temp.RData")
```

When trying to access `p1` I get this error message:
**Error in vapply(list(self$objective, self$targets), function(x) { : 
  argument "self" is missing, with no default**

I'm wondering if prioritzr is saving to the R temp folder and storing the folder name, which breaks the connection to `p1` once a new R session is started?

**Comment by jeffreyhanson** [comment]
Hmm, that's strange. No, _prioritizr_ stores everything in memory (with exception to file-backed raster data sets), so I don't think it's a temporary directory issue. I'm pretty busy at the moment, and I'll try to get to this when I can.

**Comment by ricschuster** [comment]
No worries Jeff. Its not at all urgent, but I thought I'd record the issue here as it is strange.

**Comment by jeffreyhanson** [comment]
Loading the _proto_ package seems to fix the problem on my system:

```
library(prioritizr)
library(proto)
load("temp.RData")
print(p1)
```
Does that work for you?

If so, one fix might be to move the _proto_ package from Imports to Depends in the DESCRIPTION? The downside with this putting things in the Depends field is generally discouraged, but I think being able to save prioritizr objects is pretty important? [It seems many of the packages using _proto_ also put _proto_ in the Depends](https://cran.r-project.org/web/packages/proto/index.html), so maybe it really should be in the Depends? What do you think?

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson. This fixes the issue on my system as well. 

I agree, saving prioritzr objects is pretty important. I went ahead and did this with commit https://github.com/prioritizr/prioritizr/commit/34aad396f3352c0064df7f01b2991b81c2635f31

**Comment by jeffreyhanson** [comment]
Awesome - thanks!
