### ISSUE TITLE
Error in defining the problem

### ISSUE THREAD

**Issue by momeni133** [prioritizr/prioritizr#48]
Dear all
Finally I ran the package for sample data without any problem.
But when I'm trying on my own data, I receive the below error in defining the problem:
  "Error in .doRowMax(t(x), narm = na.rm) : 
  object '_raster_doRowMax' not found"
I have 11 features and 54000 PUs.

**Comment by ricschuster** [comment]
Could you post a reproducible example of how the error is generated please?

**Comment by momeni133** [comment]
Dear Richard
Mentioned error was bebause of CRS of raster stack. when I defined the CRS it solved. But after 19h processing with 100% CPU usage, I received another error. 
My code: 

### # load packages
`library(raster)
library(prioritizr)
library('Rsymphony')

### # Add planning units
PUs<- shapefile("~/Desktop/marxan/PUs/pu_cost.shp")

### # Add conservation features
FF <- list.files(path= "~/Desktop/marxan/Features", pattern='asc', full.names=TRUE)
Features<- stack(FF)

### # Define CRS for conservation features
crs(Features) = crs(PUs)

### # Define targets to each species
targets <- c(0.45,0.37,0.27,0.39,0.44,0.35,0.27,0.11,0.37,0.31,0.30)


### # set and check number of threads
set_number_of_threads(8)
get_number_of_threads()
is.parallel()


### # create problem

p <- marxan_problem(PUs, Features, cost_column ="cost") %>%
  
  add_min_set_objective() %>%
  
  add_relative_targets(targets) %>%
  
  add_binary_decisions() %>%
  
  add_locked_in_constraints("locked_in") %>%
  
  add_rsymphony_solver()
`




My error:

"Error in add_relative_targets(., targets) : 
  argument "targets" is missing, with no default
In addition: Warning messages:
1: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
 
2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
 
3: In if (targets_type == "relative") p <- p %>% add_relative_targets(targets) :
  the condition has length > 1 and only the first element will be used"

**Comment by momeni133** [comment]
> Features
class       : RasterStack 
dimensions  : 1687, 2179, 3675973, 11  (nrow, ncol, ncell, nlayers)
resolution  : 250, 250  (x, y)
extent      : 373034.3, 917784.3, 3396760, 3818510  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=39 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
names       : Acinonyx_//vores_prey, Capra_aeg//imious_avg, Caracal_c//imious_avg, Felis_mar//imious_avg, Felis_sil//imious_avg, Gazella_b//imious_avg, Gazelle_s//imious_avg, hyeana_carnivores_prey, Ovis_orie//imious_avg, Pantera_p//ivores_avg, Vulpes_ru//imious_avg

**Comment by momeni133** [comment]
> PUs
class       : SpatialPolygonsDataFrame 
features    : 54301 
extent      : 373034.3, 917534.9, 3396760, 3818408  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=39 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
variables   : 3
names       :              AREA, locked_in, cost 
min values  : 0.000503855632219,         0, 0.02 
max values  :               200,         1,  500

**Comment by ricschuster** [comment]
Thanks very much for posting your code.
The error you are getting is because there is a mix of the `marxan_problem` specification and the `problem` specification.

The `marxan_problem` specification does not allow the use of the `add_xy` functions at this point. You have to specify the entire problem in the `marxan_problem` function call, as shown in on the [help page](https://prioritizr.github.io/prioritizr/reference/marxan_problem.html).

Essentially you need to use either `marxan_problem` and no piping **or** `problem` and piping.
