### ISSUE TITLE
solving with 1 core in Linux

### ISSUE THREAD

**Issue by momeni133** [prioritizr/prioritizr#49]
Dear all
In the Linux, the problem created with 100% CPU usage and 8 cores. When the job finished (after 26 h) I received two warnings:
Warning messages:
1: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
 
2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’

Now I'm trying to solve the created problem. But Rsymphony is using only 1 core. Why in the problem creating step it used 8 cores but in the solving step only one?

**Comment by jeffreyhanson** [comment]
The `set_number_of_threads` is used to globally control the number of threads used for processing GIS data  prior to solving reserve selection problems. If multiple cores are specified for pre-processing data (set via the `set_number_of_threads` function), then _R_ will create the warnings you're seeing. You can safely disregard these warnings. 

To set the number of threads used for solving a problem, check out the `add_*_solver` functions (e.g. `add_gurobi_solver`). Unfortunately, _Rsymphony_ package does not allow users to control the number of threads to use for solving problem, so the `add_rsymphony_solver` function does not have a `threads` argument. It seems that on certain systems the _Rsymphony_ and _lpsymphony_ packages will only use one thread for solving problems, and on other systems these packages will automatically use all of the threads for solving problems - but there is not yet an mechanism to control this within _R_.
