### ISSUE TITLE
package authors and citation

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#5]
Hi,

I think it would be good to sort out the proper citation for the package and it's authors. To my knowledge, I've included everyone whose involved with the project in the citation section of the readme. I've copied it below.

```
Hanson JO, Schuster R, Strimas-Mackey M, Arcese P, Bennett J (2017). prioritizr: Systematic 
Conservation Prioritization in R. R package version 1.0.0. 
https://github.com/prioritizr/prioritizr.
```

 What does everyone think? Is anyone missing? Is the ordering correct?

**Comment by mstrimas** [comment]
This reminds me, the old prioritizr is archived on CRAN and has my email associated with submission. At some point I think I'll need to let them know to change the corresponding author so someone else can submit to CRAN. Jeff, will this be you?

**Comment by ricschuster** [comment]
Given comments via email, how about the following for now:

Hansen, Schuster, Strimas-Mackey, Watts, Arcese, Bennett, Possingham

We will of course have to ask Matt W and Hugh if that's okay with them.

**Comment by jeffreyhanson** [comment]
@ricschuster Ok, I'll update the citation accordingly.

@mstrimas Yeah, you'll need to email CRAN that a new person will be maintaining the _prioritizr_ package when this version is submitted. Yeah, I can be the package maintainer if that's the best. What do you think @ricschuster? I understand if you'd rather be the maintainer since this is you've been spearheading this project.

**Comment by ricschuster** [comment]
@jeffreyhanson Thank you.

re: maintainer. With the 3+ packages we will have under the prioritizr package, do you think its makes sense to have individual maintainers per package or should we try to have one for all? Not sure what your near to mid-term plans are @jeffreyhanson, but I should be able to continuously dedicate work to this project over the next ~3 years. Given that I would be happy to act as maintainer over that time, if that means the most consistency. Depending on what I will do after that time we might want to move this over to Joe or a person in his lab for consistency. What do you guys think?

**Comment by jeffreyhanson** [comment]
Yeah, I think it makes sense to have the same maintainer for all the packages. I'm not sure how much time I'll have in the future to help maintain this pkg. So, I think having @ricschuster as the pkg maintainer would be great.

**Comment by mstrimas** [comment]
Alright, sounds good, once you're getting close to CRAN submission let me know and I'll email to transfer the maintainer over to Richard.

**Comment by jeffreyhanson** [comment]
I'll close this issue since we seem to have resolved this.
