### ISSUE TITLE
Two question about gurobi solver and relative targets

### ISSUE THREAD

**Issue by momeni133** [prioritizr/prioritizr#51]
Dear developers
Finally, I installed Gurobi solver successfully but I have a problem. For setting gurobi solver to use 8 threads I used below code:
` add_gurobi_solver(threads = 8, first_feasible = 1)`
But windows task manager (attached) shows that only 1 thread is working (other threads use 0% of cpu). 1 thread is not enough for me because today after 13 days of processing of Rsymphony (1 thread) without any results, I killed the processing.
What is the problem of Gurobi?
![gurobi](https://user-images.githubusercontent.com/33343341/33518452-6e4f9a7e-d795-11e7-8f42-b8f6b36249bc.jpg)

My second question is about "relative targets" for continuous features. I defined the relative targets for 11 species using below codes:
`targets <- c(0.45,0.37,0.27,0.39,0.44,0.35,0.27,0.11,0.37,0.31,0.30)
  add_relative_targets(targets) %>%`
Could you please tell me how prioritizr knows how much area is enough for each species when we are using continuous features instead of binary features? I think this needs defining a threshold to convert continuous features to the binary. I mean how prioritizr finds how large 45% of a continuous feature is?

**Comment by mstrimas** [comment]
The relative targets are based on the sum of the representation across all the planning units. This sum works regardless of whether the representation is binary or continuous. for example if you had 4 planning units with representation levels 0.25, 0.1, 0.5, and 0.75 and a relative target of 0.5, then the target would be set to 0.5 * (0.25 + 0.1 + 0.5 + 0.75) = 0.8.

I can't comment on the number of cores issue because I don't use windows. You might try solving a simple problem with 1 vs 8 cores and see if there's a difference in time.

**Comment by jeffreyhanson** [comment]
Ok, so I think there's a few things might be worth mentioning for future reference.

* Gurobi has multiple stages when it solves problem. It first does a "presolve" stage where it tries to simplify the problem, and then it has a stage where it actually tries solving the simplified problem. The presolve step only uses 1 core (even if you specify multiple cores),  and Gurobi will start using multiple cores later when  it starts trying to solve the problem.

*  ILP solvers can take a long time to solve problems when there is large variance in the objective function. In other words, if there is a large difference between the `planning unit costs` and the `blm * planning unit edges`, then the problem will take longer to solve. So, when dealing with large problems, I would try solving it first with a really small blm (e.g. 1e-9; note that values smaller than 1e-10 are treated as equal to zero), then try increasing the blm gradually to find reasonable blms 

With regards to  the problem at hand:

* Looking at your screenshot, I can't see any output from Gurobi in the console. This suggests to me that prioritizr hasn't started using Gurobi to solve the problem, and that the main bottle neck might be compiling the spatial data. You could test this by running `x <- p %>% add_boundary_penalties(1e-5, 0.5) %>% compile()` and seeing how long that takes. Also, could you please remind me how many planning units you are working with, and if they are in vector or raster format? If possible, I would strongly recommend using raster data for planning units.

**Comment by momeni133** [comment]
Dear Matt
Thank you very much. So the concept of the relative target is different is not equal to the percent of suitable habitats which we want to conserve. If it is the case, to define a suitable relative target the only way is trial and error with evaluating the results. Am I right? Also my another problem with the relative targets is about different targets for different features. I mean imagine I have 3 species to study and I want to define 0.3, 0.2, and 0.1 relative targets for species 1:3 respectively. My concern is when I define target using the code `add_relative_targets c(0.3,0.2,0.1) %>%`,prioritizr will assign 0.3 to the first species, 0.2 to second species and 0.1 to the last species or not.


Dear Jeffrey
Thank you for the clarifying.  My problem has 50000 PUs in vector format. I also defined "cost" and "locked in" as two columns of the shapefile. I have 11 species to study and I tried relative targets for these species. I also defined the BLM as `blms <- c(0, 0.1, 10, 100, 1000)`. The problem compilation for whole of the problem using 8 threads takes 23 hours. I ran this problem using Rsymphony and I killed the process after 13 days without any results!
I will add the line which you said and will inform you about the time.

**Comment by momeni133** [comment]
Dear Jeffrey
I think as you mentioned, the problem is compilation step. After 5 hours, it is still processing to add `x <- p %>% add_boundary_penalties(1e-5, 0.5) %>% compile()` and compile. 
I think I should convert all of the data to raster format, hope to shorter processing time.

**Comment by momeni133** [comment]
Is it possible to create a raster planning unit layer which each planning unit consists more than one pixel (pixels with same values show the same planning unit) and then add a separate cost layer?
I found the below text in quick start part of prioritizr:
_"If the planning unit data input is a raster, then the argument to x should be a single-band raster where each pixel is a planning unit containing the corresponding cost information. For example, in the sim_pu_raster object, the cell value denotes the simulated cost of acquiring that pixel. Raster-class problem objects have the advantage of solving more efficiently than spatial-class problem objects, but planning units must be regularly shaped, which is not always feasible."_
So, if it is not possible at the moment, consider my question as a suggestion.

**Comment by jeffreyhanson** [comment]
Ok, thanks for confirming that. Yeah, using raster data is one strategy. 

Could you verify if the issue is with generating the shared boundary data? For instance, try running code `x <- boundary_matrix(pus)` and seeing how long that takes? If  generating the shared boundary data is the bottleneck, one strategy could be simplify the geometry of the planning units if they have complex geometries (i.e. have lots of vertices).

If the issue isn't the shared boundary data, try manually generating the pu vs. species data and seeing how long that takes with `x <- rij_matrix(pus, features)`.

Yeah, _prioritizr_ assumes that each cell in a raster layer corresponds to a different planning unit. That's an interesting suggestion. Thanks for baring with this and helping us diagnose these issues.

**Comment by momeni133** [comment]
Dear Jeffrey 
I created 50000 hexagonal PUs.
I just have been running `<- boundary_matrix(pus)`, But again it only uses 1 thread. I will inform you about the results.

**Comment by momeni133** [comment]
Dear Jeffrey
the mentioned code again took a lot of time to run. so I change PUs to raster and I increased the total number of planning unit from 50000 to 1700000 in raster format! Gurobi solved the problem in less than 1 day!
