### ISSUE TITLE
Relative targets

### ISSUE THREAD

**Issue by momeni133** [prioritizr/prioritizr#52]
Dear Developers
Do you know any references for the concept of relative targets? I cannot understand it. In my previous question, Matt said: _"The relative targets are based on the sum of the representation across all the planning units. This sum works regardless of whether the representation is binary or continuous. for example if you had 4 planning units with representation levels 0.25, 0.1, 0.5, and 0.75 and a relative target of 0.5, then the target would be set to 0.5 * (0.25 + 0.1 + 0.5 + 0.75) = 0.8."_
I'm so sorry but I have confused completely. Imagine I have 3 continuous layers which show the probability of occurrence of 3 different species. In this example, if I use the relative targets, for example c(0.1,0.2,0.3), then what do these numbers mean?

**Comment by mstrimas** [comment]
For each layer, begin by calculating the total representation across all planning units. In this case, this is the sum of the probability of occurrence values across all planning units. Then the absolute target is the relative target multiplied by this sum. 

Example: imagine there are only 4 planning units and, for species 1, the probabilities of occurrence in these PUs are: 0.25, 0.1, 0.5, and 0.75. Then the total representation is 0.25+0.1+0.5+0.75=1.6. If you set the relative target to 0.1, then the actual target will be 0.1 * 1.6 = 0.16. So the algorithm will select a set of planning units for which the sum of the probabilities is at least 0.16.

If you would prefer to plan in terms of the number of planning units that a species occurs in, which may be more intuitive, you'll need to convert the occurrence probabilities into binary presence/absence values using some threshold.

**Comment by momeni133** [comment]
Thanks dear Matt
Your answer made this concept clear to me.
