### ISSUE TITLE
problem too large error when trying to solve Marxan problem with lpsymphony

### ISSUE THREAD

**Issue by ninsbl** [prioritizr/prioritizr#53]
When I try to solve a Marxan problem with lpsymphony I get a "problem too lagre" error. It has only 94577 PUs and my box has lots of RAM...

Is that number of PU not supported?

```
 p2 <- marxan_problem("pr/input.dat")
>
> add_lpsymphony_solver(p2, gap = 0.1, time_limit = -1, first_feasible = 0,
+                       verbose = TRUE)
Conservation Problem
  planning units: data.frame (94577 units)
  cost:           min: 1000, max: 2000
  features:       Jerv_habitat (1 features)
  objective:      Minimum set objective
  targets:        Relative targets [targets (min: 0.25, max: 0.25)]
  decisions:      default
  constraints:    <none>
  penalties:      <Boundary penalties [edge factor (1), penalty (1)]>
  portfolio:      default
  solver:         Lpsymphony [first_feasible (0), gap (0.1), time_limit (-1), verbose (1)]
> s <- solve(p2)
Error in asMethod(object) :
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
```

**Comment by ricschuster** [comment]
The problem size shouldn't be an issue. At the moment we discourage use of `lpsymphony` though as there are some issue with the package and recommend `Rsymphony` for open source solvers. The Gurobi solver would be ideal, but I'm assuming you can't get a free academic license at your institution?

**Comment by ninsbl** [comment]
Thanks for your swift reply.
No, we do only very little education and do not have that as one of our mandatory tasks. So I dont expect that it would be possible to get an academic gurobi license.
Anyway, I would prefer Open Source solvers also as a matter of principle ;-).
Will try Rsymphony and try to change my problem definition (reading it from polygon and not Marxan input files).
Thanks again, I report back...

**Comment by ninsbl** [comment]
OK, seems like a badly formulated problem on my side.
Maybe some mess in my Marxan input files (e.g. bound.dat wrongly sorted or the like)...
The Error message does not tell very much, but I would say the issue can be closed as wontfix never the less...

**Comment by ninsbl** [comment]
BTW: prioritizr is really a cool piece of software! Thanks for developing it!
Will share a case study as soon as we have a report!
Merry Christmas!

**Comment by jeffreyhanson** [comment]
Thanks for getting in touch. I just thought I'd chime in and say that you might be able to solve the problem using  lpsymphony or Rsymphony if you don't include boundary penalties. Merry Christmas!

**Comment by ricschuster** [comment]
Thanks @ninsbl and Merry Christmas!

**Comment by ninsbl** [comment]
For the record: it seems to be a memory limitation with the add_neighbor_constraint. After I reduced the number of PUs to 3000 it worked on a box with 32gb memory but not on a box with "only" 8gb ram...
add_boundary_penalty was less memory demanding in comparison...

**Comment by ricschuster** [comment]
Thanks for letting us know @ninsbl. Would you be able to share a subset of your data, so we can investigate this further? If there are memory limitation issues we need to generate a warning message at least.
