### ISSUE TITLE
RStudio/Gurobi(?) error / fixed

### ISSUE THREAD

**Issue by lizlaw** [prioritizr/prioritizr#55]
Hi gang,

Just had a lovely day on an issue with running prioritizr in RStudio + Gurobi, and mentioning it here in case other people have the same problem. 

I started off running the quickstart example (and numerous other data examples, incl. the pu_polygon form):

```
require(prioritizr)
require(gurobi)

data(sim_features)
data(sim_pu_raster)

p1 <- problem(sim_pu_raster, sim_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions() %>%
  add_gurobi_solver()

s1 <- solve(p1)
```

Through RStudio Version 1.1.383,
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree", 
an older version of Gurobi (6.0), and 
on a mac Platform: x86_64-apple-darwin15.6.0 (64-bit)

This seemed to run (it gave me the normal output Gurobi does when solving, and produced an optimal outcome) but this was followed by the error:

> Error in vapply(sol, `[[`, numeric(1), 4) : values must be length 1, but FUN(X[[1]]) result is length 0

And there was no solution written. 
Note: running through lpsymphony worked fine. 

After consulting with RS, I updated Gurobi to 7.5-2. Which resulted in the same error message. 
Then finally *brainwave* I ran it direct through R. 

It worked fine. And now running through RStudio is also fine. 

I don't know. But it works now. Thanks again for an amazing package! 

Liz

**Comment by jeffreyhanson** [comment]
Thank you for reporting this issue. I don't really have any idea what caused this but I'm glad you got it working. Maybe it had something to do with how Rstudio manages libraries and you had to rerun it through R before Rstudio would load the new version?

**Comment by lizlaw** [comment]
No idea either. Just glad it's working :) Thanks!

**Comment by jeffreyhanson** [comment]
I'm closing this now because we can't really work out what went wrong, but if anyone has any ideas on diagnosing or fixing this issue, please feel free to reopen it.
