### ISSUE TITLE
strange results by testing different BLMs

### ISSUE THREAD

**Issue by momeni133** [prioritizr/prioritizr#56]
Dear PrioritizR Users and Developers,
I used this package by applying Gurobi solver. I ran it 18 times for the same data-set and same cost layer (BLM is the only variable). Because I have some experiences by using Marxan, I expect that increasing BLM value, cause the decrease in the total boundary of selected reserve in one hand and increase in total cost of selected reserve on the other hand (most optimum solution should be when BLM=0). But I found some strange behavior in my solutions.  Could you please take a look at the attached figure? What do you think about this? Did you see this problem before?
![error](https://user-images.githubusercontent.com/33343341/35442905-3b665230-02a9-11e8-9637-46106b5bbb22.jpg)

Best regards

**Comment by jeffreyhanson** [comment]
Thank for you very much for looking into this and reporting this strange result. Yeah, I would expect the cost of the solution to increase as the BLM increases. Would you mind sharing the code you used to run this?

The only thing I can think of at the moment is that the default behaviour is to solve the problems to within 10 % of optimality, and not to search for the optimal solution. Did you set the gap to 0 when running this (e.g. `add_gurobi_solver(gap = 0)`)?

**Comment by momeni133** [comment]
Dear Jeffrey
Thank you for your answer. I used the below code:
`setwd("C:/Users/iman/Desktop/marxan_gurobi/500m_results")

# load packages
library(raster)
library(prioritizr)
library('gurobi')

# Add planning units
PUs<- raster("C:/Users/iman/Desktop/marxan_gurobi/500m_asc/PUs/cost.asc")

locked_in<- raster("C:/Users/iman/Desktop/marxan_gurobi/500m_asc/Lock/locked_in.asc")
locked_in <- as.logical(locked_in)

locked_out<- raster("C:/Users/iman/Desktop/marxan_gurobi/500m_asc/Lock/locked_out.asc")
locked_out <- as.logical(locked_out)

# Add conservation features
FF <- list.files(path= "C:/Users/iman/Desktop/marxan_gurobi/500m_asc/Features", pattern='asc', full.names=TRUE)
Features<- stack(FF)

# Define CRS for conservation features
crs(Features) = crs(PUs)

# Define targets to each species
targets <- c(0.45,0.37,0.27,0.39,0.44,0.35,0.27,0.11,0.37,0.31,0.30)


# set and check number of threads
set_number_of_threads(8)
get_number_of_threads()
is.parallel()


# create problem

p <- problem(PUs, Features) %>%
  
  add_min_set_objective() %>%
  
  add_relative_targets(targets) %>%
  
  add_binary_decisions() %>%
  
  add_locked_in_constraints(locked_in) %>%
  
  add_locked_out_constraints(locked_out) %>%
  
  add_gurobi_solver(threads = 8)



# define blms
blms <- c(0.09,0.1)


# create a list with the solutions

results <- lapply(blms, function(x) {
  
  p %>% add_boundary_penalties(x, edge_factor = 0.5) %>% solve()
  
})


plot(results[[2]])

outputnames <- paste(seq_along(results), ".tiff",sep="")
for(i in seq_along(results)){writeRaster(results[[i]], file=outputnames[i])}
`

**Comment by jeffreyhanson** [comment]
Thank you for sharing this. Could you try running the code below and see if that fixes the problem? There might be a few typos because I haven't run it. The main changes are that this version sets the gap to zero in `add_gurobi_solver` and calculates the total cost of each solution, and plots solution cost vs. BLM.

```
setwd("C:/Users/iman/Desktop/marxan_gurobi/500m_results")

# load packages
library(raster)
library(prioritizr)
library(gurobi)

# Add planning units
PUs <- raster("C:/Users/iman/Desktop/marxan_gurobi/500m_asc/PUs/cost.asc")

locked_in <-  raster("C:/Users/iman/Desktop/marxan_gurobi/500m_asc/Lock/locked_in.asc")
locked_in <- as.logical(locked_in)

locked_out<- raster("C:/Users/iman/Desktop/marxan_gurobi/500m_asc/Lock/locked_out.asc")
locked_out <- as.logical(locked_out)

# Add conservation features
FF <- list.files(path = "C:/Users/iman/Desktop/marxan_gurobi/500m_asc/Features",
                 pattern = "asc", full.names = TRUE)
Features<- stack(FF)

# Define CRS for conservation features
crs(Features) = crs(PUs)

# Define targets to each species
targets <- c(0.45, 0.37, 0.27, 0.39, 0.44, 0.35, 0.27, 0.11, 0.37, 0.31, 0.30)

# set and check number of threads
set_number_of_threads(8)
get_number_of_threads()
is.parallel()

# create problem
p <- problem(PUs, Features) %>%
     add_min_set_objective() %>%
     add_relative_targets(targets) %>%
     add_binary_decisions() %>%
     add_locked_in_constraints(locked_in) %>%
     add_locked_out_constraints(locked_out) %>%
     add_gurobi_solver(gap = 0, threads = 8)

# define blms
blms <- c(0, 0.00001, 0.0001, 0.0002, 0.001, 0.002, 0.003, 0.004,
          0.005, 0.007, 0.009, 0.01, 0.02, 0.03, 0.05, 0.07, 0.09, 0.1)

# create a list with the solutions
results <- lapply(blms, function(x) {
  p %>% add_boundary_penalties(x, edge_factor = 0.5) %>% solve()
})

# create a table with the blms and solution costs
result <- data.frame(
  blm = blms,
  cost = sapply(results, function(x) cellStats(PUs * x, "sum")))

# plot the relationship between blm and cost
plot(cost ~ blm, data = result, type = "b")
```

**Comment by momeni133** [comment]
Dear Jeffrey
I just have run the code. It will take a long time to finish and I will inform you about the results when it finished.
Thank you

**Comment by momeni133** [comment]
Dear Jeffrey
Thank a lot. It think the problem was solved by your code
below is the graph of BLM-Cost
![blm](https://user-images.githubusercontent.com/33343341/35469842-38f5e052-033e-11e8-9f77-4e57c249c447.png)

**Comment by jeffreyhanson** [comment]
Awesome! Glad it worked - thanks for posting the graph. I think we've resolved this issue so I'll close it now, but feel free to re-open it if needed.

**Comment by jeffreyhanson** [comment]
Just in case anyone comes across this issue when googling for help, we recently wrote up a new tutorial to help with running the calibration analysis discussed in this issue (see https://prioritizr.net/articles/calibrating_trade-offs_tutorial.html).
