### ISSUE TITLE
website

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#57]
I was thinking it might be nice to have a custom domain for _prioritizr_. I had a look on AWS Route 52, and it looks like prioritizr.com is taken, but the following domains are free:

- prioritizr.org 
- prioritizr.net
- prioritizr.info

What do people think? I'm happy to cover the registration + hosting costs (~$15 AUD per year).

**Comment by ricschuster** [comment]
I like 

prioritizr.net

As for hosting, I'd be happy to add this to my current hosting account, as I'm already having a number of dommains/websites running through that.

**Comment by jeffreyhanson** [comment]
Awesome, I've got an AWS account too so which ever is easier. 

I looked up the [whois for prioritizr.com](https://dig.whois.com.au/whois/prioritizr.com) and it's set to expire this year in March if the owner doesn't renew it. Do you think it's worth waiting to see if they don't renew it in case we can grab it?

**Comment by ricschuster** [comment]
How easy is it to add a user to your AWS account, i.e. could we have more than one person edit the website? I'm not sure how easy it is with my hosting provider.

Waiting till March would be a good idea I think, thanks for checking.

**Comment by jeffreyhanson** [comment]
I'm not sure how easy it is to add multiple people to an AWS account, but I'm not sure if that's necessary.

I was thinking we could run the website as a GitHub repo, set it up with GitHub Pages, and add a custom domain. This way we get all the collaborative + version controlled benefits of GitHub, and the website gets automatically updated when changes are made to the repo. My personal website uses this strategy (https://github.com/jeffreyhanson/jeffreyhanson.github.io). The only trick is setting up a CNAME file in the repo and configuring AWS Route 52 to point to it. We could probably set the website up so that it uses the pkgdown website (https://prioritizr.github.io/prioritizr), but if we could also expand on this later on if we wanted to.

Ok, let's wait and see what happens to prioritizr.com before exploring other options.

(Apologies if I'm using the wrong terminology, I'm not very experienced with website hosting)

**Comment by ricschuster** [comment]
The GitHub repo route sounds good to me, thanks for explaining.

I've set myself an alarm for the expire date. Lets see if we can get .com

**Comment by mstrimas** [comment]
I'll just chime in here to agree that GitHub pages + a custom domain is the way to go. I have the same set up for my web site. Also, Jeff could add new IAM Roles to his AWS account to grant access to others to the web site administration. But agree that it wouldn't be necessary with the GitHub pages route.

**Comment by ricschuster** [comment]
It looks like nobody has renewed prioritizr.com (expired March 17), but so far the domain name still shows up as being taken. Should we wait another couple weeks to see if it becomes available or just go with .net or one of the other suggestions?

**Comment by ricschuster** [comment]
Just checked prioritizr.com again. Its renewed. Lets pick another domain name and register. You up for this Jeff?

**Comment by jeffreyhanson** [comment]
Yeah, sounds great. I can update all the links in the docs to point the new url after it's registered.

**Comment by jeffreyhanson** [comment]
Just to keep everyone in the loop, I've purchased `prioritizr.net` on AWS, so I'll begin updating the package website when it's finished registering.
