### ISSUE TITLE
Suggestion: Solution status and settings

### ISSUE THREAD

**Issue by lizlaw** [prioritizr/prioritizr#63]
Hi gang,
Wondering if the solve() could also output attributes such as the problem settings (e.g. the files specified and constraints etc) and especially the result status of the optimization (whether Optimal, Time-Out, etc). 
The latter could be simply added to the solution names (e.g. "solution_1_OPTIMAL"), and would save having to dig through the logs. The former I guess is a little more work and not a huge priority, but would help clarify things for the less experienced user and maintain this info attached to the solution data. 
Otherwise, my colleague here that I'm helping is super impressed with things so far :) Hope to be adding to the 'publication' list soon!
Cheers, 
Liz

**Comment by jeffreyhanson** [comment]
Hi, 

Yeah the outputs from `solve` contain information like that stored in attributes (e.g. `attr(solution, "status")`; [see examples in the help file for problem](https://prioritizr.github.io/prioritizr/reference/problem.html)). Maybe this feature hasn't been documented well enough though, where do you think it would best to document this? In the help file for `solve`?

Awesome - I can't wait to read about how you've using prioritizr!

**Comment by mstrimas** [comment]
I had no idea this info was stored in the attributes either. Documenting this under the `@return` section for `solve()` sounds like a good idea to me.

**Comment by lizlaw** [comment]
Hi Jeff,
Fantastic! Yes - in the reference for `solve()` but perhaps also in the quickstart? 
Thanks a million!
Liz

**Comment by jeffreyhanson** [comment]
Since I'm pushing some fixes to the master branch to address the recently raised bugs, I'll just address these issues in the same commit.
