### ISSUE TITLE
Zones coding interface

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#66]
Hi, 

I'm working on adding "zones" functionality to _prioritizr_ and I'm having trouble coming up with a consistent and useful interface. So, I thought I would post some ideas here and see what everybody thinks. It would be great if people with experience in using MarZone could post their thoughts too (@lizlaw, @jflowernet, @ninamorrell, @momeni133  do you have experience with MarZone?). 

The main conceptual issue I'm having, for the moment at least, is the idea that MarZone supports two different types of targets. MarZone supports (i) zone-feature targets (i.e. a target amount for each feature for in each zone) and (ii) "tandem" feature target (i.e. a target amount for each feature which can be met using the total amount held in multiple zones). 

To help illustrate what I mean, let's pretend we're working with raster data, 3 features, and 2 zones. The planning unit data is in the `pu` object. This is a `RasterStack` object with two layers (one for each zone) and pixel values correspond to costs. The feature data are stored in the `RasterStack` objects  `features_zone_1` and `features_zone_2`. These `RasterStack` objects contain three layers (one for each zone). For example,  `features_zone_1[[1]]` contains abundance data for the first feature in zone 1, `features_zone_2[[1]]` contains abundance data for the first feature in zone 2, and `features_zone_1[[2]]`  contains abundance data for the second feature in zone 1.

So, if implemented feature-zone targets (i.e. target type 1) the code might look something like the code below. First, we create a matrix with our targets (where each row is for a different feature and each column is for a different zone), and then we create a minimum set problem to a ensure that the solution contains a certain percentage of feature in a given zone.

```
targets <- matrix(c(0.01, 0.02,
                    0.03, 0.04, 
                    0.05, 0.06), ncol = 2, byrow = TRUE)

p <- problem(pus, zones(features_zone_1, features_zone_2)) %>%
   add_min_set_objective() %>%
   add_relative_targets(targets) %>%
   add_binary_decisions()
```

But, if we implemented the "tandem" feature targets (i.e. target type 2), we need to set targets for each feature for some combinations of zones. Here, we create a vector `targets` with the targets amounts (expressed as proportions), a vector `spp_ids` with the indices for different features that each target corresponds to, and a matrix `zone_ids` specifying which zones each target corresponds to (since a single "target" can be met by allocating different areas to multiple zones). So, our first target says that we need 10 % of the habitat in zone 1 for species 1 to be met, the second targets says that we need 5% of the combined habitat in zone 1 and zone 2 for species 1 to be allocated in zones 1 or 2, and so on.

```
targets <- c(0.1, 0.05, 0.2, 0.3)
spp_ids <- c(1, 1, 2, 3)
zone_ids <- matrix(c(TRUE, FALSE,
                     TRUE, TRUE,
                     FALSE, TRUE,
                     TRUE, FALSE),  ncol = 2, byrow = TRUE)

p <- problem(pus, zones(features_zone_1, features_zone_2)) %>%
     add_min_set_objective() %>%
     add_relative_targets(targets, spp_ids, zone_ids) %>%
     add_binary_decisions()
```

It's worth noting that type 1 targets could be seen as a specialised case of type 2 targets. But type 2 targets require a lot more inputs and it would be pretty annoying to have to specify the `spp_ids` and `zone_ids` for basic problems with just one zone (aka current prioritizr). 

So, how can we reconcile this? I guess we could have `add_relative_targets` accept a broad range of inputs. Below are some potential function definitions.

```
# all feature/zone targets are given the same number
add_relative_targets(numeric single-number) 

# each number in the vector assigns a different target for each feature and if multiple
# zones are present then the same target is applied to each zone
add_relative_targets(numeric vector) 

# as in previous code block
add_relative_targets(numeric vector, integer vector, logical matrix) 
```

Or perhaps this is really confusing for the user? So alternatively we might consider creating a special target class that lets users write out their targets manually when they need to. Eg. something like this:

```
p <- problem(pus, zones(features_zone_1, features_zone_2)) %>%
   add_min_set_objective() %>%
   add_manual_targets(target(feature = 1, zones = 1, value = 0.1, type = "relative"),
                      target(feature = 1, zones = 1:2, value = 0.05, type = "relative"),
                      target(feature = 2, zones = 2, value = 0.2, type = "relative"),
                      target(feature = 3, zones = 1, value = 0.3, type = "relative")) %>%
        add_binary_decisions()
```

And so, the following the two sets of code could be used to define the same problem:

```
p <- problem(pus, zones(features_zone_1, features_zone_2)) %>%
     add_min_set_objective() %>%
     add_relative_targets(0.1) %>%
     add_binary_decisions()

p <- problem(pus, zones(features_zone_1, features_zone_2)) %>%
     add_min_set_objective() %>%
     add_manual_targets(target(feature = 1, zones = 1, value = 0.1, type = "relative"),
                        target(feature = 1, zones = 2, value = 0.1, type = "relative"),
                        target(feature = 2, zones = 1, value = 0.1, type = "relative"),
                        target(feature = 2, zones = 2, value = 0.1, type = "relative"),
                        target(feature = 3, zones = 1, value = 0.1, type = "relative"),
                        target(feature = 3, zones = 2, value = 0.1, type = "relative")) %>%
     add_binary_decisions()
```

But this could also be really annoying for problems dealing with hundreds or thousands of features? So maybe this makes more sense? We could have `add_manual_targets` require a list of targets that the user could create using their own code (e.g. using *apply functions or loops).

```
p <- problem(pus, zones(features_zone_1, features_zone_2)) %>%
        add_min_set_objective() %>%
        add_manual_targets(list(target(feature = 1, zones = 1, value = 0.1, type = "relative"),
                                target(feature = 1, zones = 2, value = 0.1, type = "relative"),
                                target(feature = 2, zones = 1, value = 0.1, type = "relative"),
                                target(feature = 2, zones = 2, value = 0.1, type = "relative"),
                                target(feature = 3, zones = 1, value = 0.1, type = "relative"),
                                target(feature = 3, zones = 2, value = 0.1, type = "relative"))) %>%
        add_binary_decisions()
```

Personally, I think I like the verbosity offered by the `add_manual_targets` and rewriting the existing `add_relative_targets` and `add_absolute_targets` to simply generate separate `target` objects. But I really want to hear from other users and members of the development team? Do you prefer inputting a few "complex" objects or many "simple" objects? What does everyone think?

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson for starting this discussion. Not having used MarZone myself, my comments might not be all that useful, but from a user input standpoint I do like the `add_manual_targets` approach. How to best specify this function is less clear to me and maybe we should also make the function name more specific to Zones, e.g. `add_zone_specific_targets`. 

I think it would also a good idea to post this issue or a more generalized version of it to the Marxan mailing list, as this would get the attention and hopefully input of a large number of MarZone users.

**Comment by lizlaw** [comment]
Hi Jeff, I think the beauty of zones is in its flexibility, so I too like the add manual targets option for adding more complex target options. If there is an easy way of coercing e.g. a data frame into the right format for the targets the better (easy for the less adept like me to make, easy to share and discuss with others as a spreadsheet). 

I also agree with Richard that keeping the language emphasizing the zones is useful - avoids any confusion with the non-zone option targets (i.e. no noob like me is going to try and apply them to a non-zone problem accidentally). 

Super excited for Zones!

**Comment by jeffreyhanson** [comment]
Hmm, I suppose we could have data.frames as an input with something like this:

```
data.frame(feature = 1, zone = 1, value = 0.1, type = "relative")
```

But then it gets tricky for type 2 zones where a single target affects multiple zones. I suppose we could implement list columns using _tibble_, with something like this:

```
tibble(feature = 1, zone = list(1:2), value = 0.1, type = "relative")
```

What does everyone think? Would it worth supporting both the list of special target class objects, or just use a `data.frame`/`tibble` for input? The more I think about the `data.frame` input, the more I like it. I think it'll work nicely with _dplyr_ workflows.

I'm not sure if I agree with separating zones from non-zones. My understanding, though please correct me if I'm wrong, is that the classic Marxan and current implementation of _prioritzr_ just use one zone, and adding "zones" just means adding the functionality for multiple zones. If we go with the `data.frame`/`tibble` input then we could just code it so that a zone column isn't needed when specifying targets for problems with only one zone? I was thinking of converting "non-zones"/"single zone" problems to a "zone" problem internally with just one zone so that I don't have to write a version of code for "no zones" and a version of the code for "multiple zones".

**Comment by lizlaw** [comment]
Re separation I guess I mean in name only. Behind the scenes I think it makes sense to formulate the classic single/non-zones problems as a single 'protected' zone (with zero value for conservation features outside of this).  But then I don't actually know what's going on behind the scenes! Adding more complex targets (i.e. via your proposed `add_manual_targets`) I think would only ever be done  when there are multiple zones to consider; the current ` add_relative_targets` specified as a list of numbers is adequate for single zone problem complexity, or? Therefore calling it `add_zone_targets` I think is valid.

**Comment by ricschuster** [comment]
I like the `data.fram/tibble` style for inputs. Also, thinking about folks using the GUI/Shiny, allowing them a `data.frame` type input would make a lot of sense I think. As for list columns, I think that's a good idea, but also wonder if there might be a way to 'flatten' that into a classic `data.frame` somehow. Not necessarily for R users, but for GUI users. It would be easy enough to have one entry vector (feature, zone, value, type) per row and check for repeat occurrences of features to catch type 2 zones you mentioned above.

re: separation. Good point @jeffreyhanson How about we keep the current `add_relative_targets` et al. functions and don't add the `add_manual_targets' function. Maybe we could even consolidate the `add_targets` functions into one? If we keep the current functions (or consolidate) we could have single values be targets for all, vectors individual targets for 1 Zone (i.e. classic prioritization) problems and `data.frames` for multi-Zone problems. If we consolidate we would also require the user to specify the target type. What do you think about that idea? It would be kind of neat to only have one `add_targets` function or set of functions, instead of having different functions for different problem types.

**Comment by jeffreyhanson** [comment]
To recap, I think we all agree that having the following functionality is useful (1) backwards compatibility for the `add_relative_targets` and `add_absolute_targets` functions in the zones update and (2) specifying targets for features in zones using `data.frame` and/or `tibble` objects.  I think the main points that we disagree on are (3) should we have a dedicated zones function for targets or (4) should we have a general targets function (and if so what should it be called)? Please let me know if I've missed anything.

So, based on the points that we agree on, it looks like _prioritizr_ would need target function definitions that look something like this:

```
add_relative_targets(numeric)
add_relative_targets(character)
add_absolute_targets(numeric)
add_absolute_targets(character)
add_manual_targets(data.frame) # or add_targets(data.frame) or add_zone_specific_targets(data.frame) 
add_manual_targets(tibble) # or add_targets(data.frame) or add_zone_specific_targets(data.frame) 
```

I think one of the main ideas behind _prioritizr_ is that (almost) all constraints, targets, penalties, and solvers should work regardless of the input data and the other properties of the problem. So, for example, the `add_boundary_penalties` function should be able to work with `Raster`, `Spatial` and `data.frame` data sets and should also work in a problem regardless if it has a minimum set objective, a maximum utility objective, or multiple zones. I don't really like the idea of a function like  `add_zone_specific_targets` that is designed only to work with a specific type of problem unless we can avoid it (granted, the `add_feature_weights` function is also designed to work with a specific type of problem so if we can make exceptions if needed). I guess choosing (3) to me would be like if _ggplot2_ had a `geom_point` function to add black points to a graph and a `geom_coloured_points` function to add different coloured points to a graph. I like the idea of having "a few general purpose functions" rather than "a lot of specific functions functions". So with regards to (3) and (4), I still prefer (4). Does that sense?

If we agree that having a general purpose function to add targets is useful, then I think we just need to agree on a name for it. I think having a 3-word name (i.e. `add_adjective_targets`) for the function is useful, to keep in line with `add_relative_targets` or `add_absolute_targets`. I originally proposed `add_manual_targets` (in reference to [scale_fill_manual](http://ggplot2.tidyverse.org/reference/scale_manual.html) from _ggplot2_), but maybe there's a better name? Maybe `add_generic_targets`? Can anyone think of a better name?

This is a bit tangential to the main issues outlined above, but I think for problems with multiple zones, and where each target corresponds to a single zones, it might be useful to allow users to specify a `matrix` (rows = features, columns = zones) of targets. So, I suggest the following function definitions:

```
add_relative_targets(numeric)
add_relative_targets(matrix)
add_relative_targets(character)
add_absolute_targets(numeric)
add_absolute_targets(matrix)
add_absolute_targets(character)
add_manual_targets(data.frame) # or better name 
add_manual_targets(tibble) # or better name
```

Additionally, in the current version of _prioritizr_, problems that use `data.frame` data for features can use a column name to indicate the feature targets (e.g. `add_absolute_targets(character)`). So, in a problem with multiple zones, I think it would be nice if this definition could be generalized to multiple zones by allow users to input a vector of column names (where if element corresponds to a column containing targets for a single zone).

I think the benefit of this extra functionality is that it enables users to keep using `add_relative_targets` and `add_absolute_targets` for problems with multiple zones, without having to use a different function for problems with multiple zones unless they really want targets that can be met through allocations to multiple zones (e.g. the target corresponds to the total amount needed for the feature and this could be met through allocating planning 10 planning units to zone 1 or 30 planning units to zone 2).

Thoughts?

**Comment by ricschuster** [comment]
Thanks for summarizing this Jeff. I think we should have a general targets function.

Given your suggestion of allowing to specify a matrix in `add_relative_target` and `add_absolute_target` what are your thoughts about wrapping `add_manual_targets` into this, i.e. not including `add_manual_targets`?

We could add a check to `add_relative_target` and `add_absolute_target` and its matrix/data.frame specification that looks at `nrow(df)`. If this value is equal to the number of features the function processes with the 'standard' zones specification. If `nrow(df)` > number of features we know that a user wants targets that can be met through allocations to multiple zones and prioritizr could process the information in `df` accordingly. 

What do you think about that approach? It would allow us to keep with the current fucntions, but maybe its better to put some of the workload on the user? I would think that anyone needing a function like `add_manual_targets` would be able to specify their target matrix in a way that would align with requirements by `add_relative_targets` or `add_absolute_targets`. Am I too optimistic here?

**Comment by lizlaw** [comment]
Never having this sort of experience in programming, I feel a little out of my depth.  I think as long as the documentation explains clearly how to structure inputs, anyone who has gotten this far should be able to manage it. My only other concern as a user is how easy it would be to accidentally enter the wrong format, and it not result in an error, thus I am getting false results without realising it.

**Comment by jeffreyhanson** [comment]
Sorry for the late reply,

@ricschuster I think we still need something like `add_manual_targets` because a single target can pertain to allocations for multiple zones and this is not compatible with a matrix input format (where each row is a feature and each column is for a zone). I've also implemented the functionality to specify the sense of the targets in the dev version of `add_manual_targets` (e.g. specify a constraint as `>=`, `<=`, or `=`) which could make for some interesting ways of exploring trade-offs? 

@lizlaw I agree I think it's very important  to guard against users accidentally inputting objects. At the moment, the `add_absolute_targets` and `add_relative_targets` functions require matrix input (where each row is a feature and each column is a zone) for problems with multiple zones (otherwise these functions will throw an attemptedly helpful error). If the problem has a single zone, then the user can still supply a single number of a vector (where each element corresponds to a feature) to set the targets, similar to the current implementation. So, the only way to add targets for problems with multiple zones is using different code from that which would work in the master version of _prioritizr_.

**Comment by ricschuster** [comment]
Makes sense to me @jeffreyhanson. The way you are implementing this will make it less likely to cause trouble too. The way I had in mind would open _prioritzr_ up to the issue @lizlaw raised, so I agree `add_manual_targets` does make the most sense.

**Comment by jeffreyhanson** [comment]
I think we've resolved the zones interface, so I'm closing this now. Feel free to reopen this anyone would like to chat more about it.
