### ISSUE TITLE
organize function list on pkgdown website

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#67]
It looks like the function reference in pkgdown can be organised to list functions under headings (see http://jranke.github.io/mkin/reference/index.html).  I think would be useful for organising the functions in _prioritizr_. Thoughts?

**Comment by ricschuster** [comment]
Adding headings to the reference section would be a great addition and very useful I think.

**Comment by jeffreyhanson** [comment]
I've added the sections to the pkg website on the zones branch 49c7fa1. This will become live when we merge the zones branch with the master branch.
