### ISSUE TITLE
set max number of planning units

### ISSUE THREAD

**Issue by emmajhudgins** [prioritizr/prioritizr#68]
Hi there, I'm interested in using prioritizr for forest pest management, where I want to minimize future risk if planning units are not managed while taking into account management-related costs in the form of removal of forest volume. Is there currently a way to set a constraint relating to the maximum number of planning units to select (irrespective of cost)?

**Comment by jeffreyhanson** [comment]
Thank you for getting in touch and raising this issue. It's really useful for us to hear about potential problems with using _prioritizr_ and missing functionality.

Currently, there isn't a constraint function that limits the number of planning units selected in a solution ([see here for a list of constraints](https://prioritizr.github.io/prioritizr/reference/constraints.html)). It sounds like you're interested in formulating a budget constrained conservation problem (e.g. using [add_max_cover_objective](https://prioritizr.github.io/prioritizr/reference/add_max_cover_objective.html)), is that right? Assuming you don't have cost data for each planning unit, then you could set all planning unit costs as one and set the budget as the maximum number of planning units permitted in the solution. Would that work for your conservation planning scenario?

**Comment by jeffreyhanson** [comment]
@emmajhudgins and I caught up at UQ, and we worked out that a multi-zone maximum utility problem with connectivity penalties might work for her problem. So, I'm closing this issue now, but feel free to reopen it if anyone would find an `add_maximum_number_of_pu_constraints(n)` function useful.

**Comment by jeffreyhanson** [comment]
Just to follow up in case anyone comes across this issue when googling for help, the `add_linear_constraints()` function could be used to implement this functionality (https://prioritizr.net/reference/add_linear_constraints.html).
