### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#7]
Starting April 10, @ninamorrell will be working on this project for an entire month. Lets start pulling a to-do list together, so we can make sure her time is used effectively.

**Comment by jeffreyhanson** [comment]
Brilliant - yeah that sounds like a great idea.

**Comment by jeffreyhanson** [comment]
Ideas for TODO list:

- create a comprehensive tutorial that introduces conservation planning concepts (eg. feature, planning units), and goes over the functionality of the package. This could also include some examples on calculating metrics from solutions (eg. feature representation). This could re-use some stuff that @mstrimas wrote in his vignette.
- create a tutorial vignette that uses the Tasmania data set.
- add mathematical equations to help pages.
- move each `add_XXXX_objective` function to its own help page.
- add a quick start guide. This could be re-use stuff in the README.
- add a vignette that explains how to install Gurobi and the gurobi R package. This could include screenshots to help users.

**Comment by ricschuster** [comment]
Vignette to install Gurobi and gurobi R package added.
