### ISSUE TITLE
obtain multiple solutions from the solution pool 

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#77]
The R package distributed with Gurobi version 8 now lets R users extract solutions from the solution pool (http://www.gurobi.com/documentation/8.0/refman/gurobi.html). I think it would be great if we could add this functionality to _prioritizr_.

I see two potential ways for adding this functionality:

1. We could add a logical `pool` parameter to the `add_gurobi_solver` function. If TRUE, then multiple solutions are returned. I'm not sure if I like this approach because currently all functionality for creating/handling multiple solutions is specified in the portfolio functions.
2. We could add a `add_pool_portfolio` function to specify that solutions should be returned from the solution pool. I think this approach is more consistent with the current approach. However, this portfolio function would only work when the Gurobi solver is specified. 

What do people think?

**Comment by ricschuster** [comment]
This would be a great addition.  
I'm for option 2.  We can just note in the documentation that this function only works with Gurobi.

Thanks Jeff!
