### ISSUE TITLE
velox package dependency

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#8]
Should
import(velox) 
be added to NAMESPACE?

> p1 <- problem(sim_pu_polygons, features = sim_features, cost_name = "cost") %>%
+   add_min_set_objective() %>%
+   add_relative_targets(0.2) %>%
+   add_binary_decisions()
Loading required namespace: velox
Failed with error:  ‘there is no package called ‘velox’’

**Comment by mstrimas** [comment]
`velox` is meant to be an optional package, the issue was just that one of the `requireNamespace("velox")` calls was missing a `quietly = TRUE`, which I've now fixed. It was sort of a phantom error because the code actually runs just fine despite the error.

**Comment by ricschuster** [comment]
Thanks @mstrimas
