### ISSUE TITLE
Faster cuts portfolio

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#80]
_Gurobi_ has the functionality to return the _n_ different solutions within a pre-specified optimality gap using the solution pool (i.e. when the `PoolSearchMode` parameter is set to two; http://www.gurobi.com/documentation/7.5/refman/subtleties_and_limitations.html). Since this is the purpose of the cuts portfolio, I propose the we modify the cuts portfolio to use the solution pool (with `PoolSearchMode` set to two) when tasked with using _Gurobi_ to obtain solutions (as opposed to repeatedly solving and modifying the problem). I expect/hope that using this method will return the solutions in a much shorter period of time because it will mean that the pre-solve step is only executed once. Hopefully, this will substantially reduce the time needed to generate multiple solutions, and mean that users can quickly generate portfolios containing thousands of solutions for calculating selection frequencies.

**Comment by jeffreyhanson** [comment]
For any one interested, I was playing around with the selection frequency example in the Tasmania Tutorial, and I was able to generate a portfolio containing 1000 solutions within 10 % of optimality using this method in **11 seconds** on a standard laptop.

**Comment by ricschuster** [comment]
This sounds awesome Jeff! Thanks for implementing.
