### ISSUE TITLE
clarification: relative & loglinear targets

### ISSUE THREAD

**Issue by lizlaw** [prioritizr/prioritizr#89]
Hi gang, 
Nice work on the new improvements!
Quick clarification re targets:
The 'relative targets' calculates the target based on the input feature layer, i.e. before things like locked out etc are taken into play, yes? Might be worth clarifying in the reference.
Also, one thing I came up with on the log-linear targets is that sometimes not all of the species distribution is within the study area is not always representative of the global species distribution (and so perhaps it might be useful to be able to input a vector of 'global' range sizes for this task?) Not a high priority, is easy enough to do by hand, but perhaps also worth mentioning in the reference. 
Best,
Liz

**Comment by jeffreyhanson** [comment]
Hey,

Thanks! Yeah that's correct, I'll update the documentation when I get chance.

Yeah I really like your idea for the log-linear targets, and I'll update that when I get a chance.
