### ISSUE TITLE
feature_representation() not working directly with a numeric solution 

### ISSUE THREAD

**Issue by javierfajnolla** [prioritizr/prioritizr#91]
I have notice that the feature_representation() function is not working directly with a numeric solution to a conservation problem. 
The problem seems to be that there are attributes attached to the solution (the attributes "objective", "status" and "runtime").

The error output is:
`Error: solution is not an atomic vector without attributes`

The solution is as easy as input the solution inside `as.numeric()`.
Just reporting!
Javier

**Comment by jeffreyhanson** [comment]
Hey - thanks for reporting this! I'll push a new version that addresses this issue in a few minutes.
