### ISSUE TITLE
Instructions for installing Gurobi on remote machine are incorrect 

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#98]
The command:

```
ssh -L 8080:apps.gurobi.com:80 USER.COMPUTER1@IP.COMPUTER1
```

should be called from COMPUTER1 and be:

```
ssh -L 8080:apps.gurobi.com:80 USER.COMPUTER2@IP.COMPUTER2
```

Additionally, the command:

```
grbgetkey --server=127.0.0.1 --port=8080 --verbose XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

should be 

```
grbgetkey --http --server=127.0.0.1 --port=8080 --verbose XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

**Comment by nealeyoung** [comment]
No longer working as of January 2021.  Here are updated instructions:  https://medium.com/@drfyp/validating-an-academic-gurobi-license-through-a-socks-proxy-on-macos-740f7d9527b4

**Comment by ricschuster** [comment]
Thanks @nealeyoung.
As far as I know validating an academic Gurobi license doesn't require going through a VPN or proxy anymore. What's your experience @jeffreyhanson ?
We should probably update the vignette?

**Comment by jeffreyhanson** [comment]
Thanks @nealeyoung! 

I just updated Gurobi on my laptop and that;'s that's correct @ricschuster. You don't actually need to be connected to university VPN/proxy anymore. It would also seem that Gurobi's academic licenses now only persist for 2 months now (instead of 1 year).

**Comment by jeffreyhanson** [comment]
Also, yeah, we should update the Gurobi installation vignette too. Since Gurobi redesigned their website (a while ago now I think), I think all the screenshots need updating too.

**Comment by ricschuster** [comment]
Yeah, the switch from 1 year to 2 months isn't great. I hope this doesn't signal that the license program will eventually run out.

**Comment by jeffreyhanson** [comment]
Gurobi no longers requires connection to an academic network for license set up, so these instructions have been removed. So I'll close this issue.
